### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [isogeo/isogeo-plugin-qgis#1]
It is not immediately obvious to the standard user what Isogeo is, and what the plugin does.
If the service requires an access to Isogeo, this should be clearly stated in the About, and its conditions outlined.
Thanks.

**Comment by Guts** [comment]
@pcav tell me if it's enough.
Please keep in mind that this plugin is under active development and once available in experimental channel, it will be beta-tested by our users during 2 months (at least).

**Comment by pcav** [comment]
Done, thanks.
