### ISSUE TITLE
La recherche par système de coordonnées ne fonctionne pas

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#104]
Test réalisé sur la version 1.5 bêta 3

Pour reproduire :
1. Ouvrir la recherche avancée
2. Dans le filtre "Systémes de coordonnées" selectionner WGS84, le nombre de résultats ne varient pas

**Comment by Guts** [comment]
Application utilisée ?
Fichier log siouplé...

**Comment by vblanlot** [comment]
> Application utilisée ?
Plugin QGIS - Dév

Fichier log ci-joint
[log_isogeo_plugin.txt](https://github.com/isogeo/isogeo-plugin-qgis/files/905550/log_isogeo_plugin.txt)
