### ISSUE TITLE
Améliorer et enrichir l'interface de recherche

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#107]
- [x] A l'ouverture du plugin être focus sur la barre de recherche
- [x] Augmenter la hauteur de la barre de recherche et ajouter un bouton GO
- [x] Ajouter un texte "rechercher" ou "pistes cyclables" dans la barre de recherche
- [x] Ajouter la "recherche rapide" et "enregistrer la recherche" à droite de la barre de recherche
- [x] Placer la liste des mots-clés sous la barre de recherche et afficher les mots-clés sélectionnés
- [ ] Placer le bouton "réinitialiser la recherche" à droite du nombre de résultats
- [ ] Réduire la taille des boutons de tri

**Comment by Guts** [comment]
Thanks for your interest and to take the time to report!

To improve our diagnosis, could you join the log file which is located in the root plugin folder:

- `C:\Users\%USERNAME%\.qgis2\python\plugins` on Windows;
- `/home/$USER/.qgis2/python/plugins` or Ubuntu.

**Comment by vblanlot** [comment]
@Guts Voici ma proposition d'interface

![recherche_qgis](https://user-images.githubusercontent.com/14051239/26978430-d052f904-4d2b-11e7-8282-d4707cf5e229.png)

**Comment by Guts** [comment]
> Placer la liste des mots-clés sous la barre de recherche et afficher les mots-clés sélectionnés

Les mots-clés sont en tooltip.
