### ISSUE TITLE
Requête réseau expire lors de l'ajout d'une table PostGIS

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#108]
Pour reproduire

1. Rechercher des données au format PostGIS
2. Ajouter une donnée à la carte, la donnée est bien ajoutée à la carte en revanche un avertissement apparaît systématiquement à l’écran (cf.copie d'écran et fichier de log ci-joint)

![requete_reseau_expire](https://cloud.githubusercontent.com/assets/14051239/24807745/bda03a54-1bb9-11e7-8389-6b835d8ec2a5.png)

[log_isogeo_plugin_cd_calvados.txt](https://github.com/isogeo/isogeo-plugin-qgis/files/906075/log_isogeo_plugin_cd_calvados.txt)

**Comment by Guts** [comment]
La version de QGIS utilisée est inférieure à celle requise dans la recette : 2.14.13 +.
