### ISSUE TITLE
Plantage lorsque l'on tente d'ajouter une table PostGIS qui n'est plus accessible

### ISSUE THREAD

**Issue by lenoxduce** [isogeo/isogeo-plugin-qgis#110]
Bonjour,
Lorsqu'une table est supprimée en base de données et que la fiche de métadonnées n'a pas subi le même sort, le plugin qgis plante. Erreur python et mini dump. Je n'ai plus d'imprim écran car j'ai corrigé le prob. Il peut en rester....
Une alerte plus douce pourrait mettre en évidence le fait que la table n'existe plus et donc que la métadonnée n'est plus à jour.

Sylvaine

**Comment by Guts** [comment]
Merci pour votre intérêt et d'avoir pris le temps de tester et surtout celui de signaler !

Pour améliorer notre diagnostic, merci de joindre le fichier **log_isogeo_plugin.log** situé dans le dossier d'installation du plugin:

- `C:\Users\%USERNAME%\.qgis2\python\plugins` sur Windows;
- `/home/$USER/.qgis2/python/plugins` sur Ubuntu.

**Comment by Guts** [comment]
Sans fichier log c'est compliqué de travailler sur ce genre de problème.
Il sera pris en compte dans une évolution.

**Comment by SimonSAMPERE** [comment]
L'étudier pour la 3.1.0
Vérifier que la table existe dans la base avant de l'ajouter

**Comment by leodarengosse** [comment]
Corrigé, la table manquante en base n'est pas ajoutable

**Comment by SimonSAMPERE** [comment]
super
