### ISSUE TITLE
Multiplication des barres de chargement

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#111]
![capture_plugin](https://cloud.githubusercontent.com/assets/20684784/25267193/24191c0a-2674-11e7-8b3a-355e31b07c5a.PNG)

Après utilisation du plugin, je me retrouve avec une multitude de barre d'attente en bas de ma fenêtre de QGIS. Ça semble apparaitre suite à un plantage du plugin du à un lien WFS non fonctionnel  (config : Windows 10 64 et version 2.14.13 de Qgis

**Comment by Guts** [comment]
Merci pour votre intérêt et d'avoir pris le temps de tester et surtout celui de signaler !

Pour améliorer notre diagnostic, merci de joindre le fichier **log_isogeo_plugin.log** situé dans le dossier d'installation du plugin:

- `C:\Users\%USERNAME%\.qgis2\python\plugins` sur Windows;
- `/home/$USER/.qgis2/python/plugins` sur Ubuntu.

De même, une capture d'écran avec la fenêtre des messages de QGIS serait d'une grande aide. Merci :)

**Comment by Guts** [comment]
Ajout du fichier log déposé dans une issue à part (#118) 


[log_isogeo_plugin.txt](https://github.com/isogeo/isogeo-plugin-qgis/files/952239/log_isogeo_plugin.txt)

**Comment by smavd** [comment]
Lien [vers la fiche APP](https://app.isogeo.com/groups/d960ae611b9345f69da57f42565ebbc3/resources/18ba566405624c4f82d6520ac550091c/resources).

A noter que ce comportement peut aussi se produire lors d'une recherche rapide cf. #116

**Comment by Guts** [comment]
Anomalie reproduite une seule fois sur une dizaine de tests.
QGIS ne plante pas. Le ticket pourra être réouvert quand le problème sera de nouveau constaté.

**Comment by Guts** [comment]
Duplicate of #127
