### ISSUE TITLE
Type de format à afficher par défaut

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#113]
Pourrait-on avoir les "data file" proposés  par défaut au lieu des flux WFS ou WMS ?
![capture_plugin2](https://cloud.githubusercontent.com/assets/20684784/25267672/fd425284-2675-11e7-9b6a-e6d2bf2587df.PNG)

**Comment by Guts** [comment]
En fait c'est lié à #112

**Comment by vblanlot** [comment]
Par défaut "WFS" est proposé avant "Données fichiers" (cf.copie d'écran ci-jointe)

Test réalisé sur la donnée "Attractions" dans l'application "Plugin QGIS - Dév"
![actions](https://cloud.githubusercontent.com/assets/14051239/25520152/2dd1ed44-2bfb-11e7-9b00-8acdcfff4f89.PNG)

**Comment by Guts** [comment]
En effet.

Quel ordre dans les possibilités d'ajout doit-je implémenter ?

**Comment by vblanlot** [comment]
Je propose l'ordre suivant

- Donnée fichier
- WFS
- WMTS
- WMS
