### ISSUE TITLE
recherche rapide

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#114]
![capture_plugin3](https://cloud.githubusercontent.com/assets/20684784/25267868/d385ab2a-2676-11e7-952f-3541ea7b404d.PNG)

Le pugin plante parfois (toutes les fonctions sont grisées) après test de recherche rapide

**Comment by Guts** [comment]
Merci pour votre intérêt et d'avoir pris le temps de tester et surtout celui de signaler !

Pour améliorer notre diagnostic, merci de joindre le fichier **log_isogeo_plugin.log** situé dans le dossier d'installation du plugin:

- `C:\Users\%USERNAME%\.qgis2\python\plugins` sur Windows;
- `/home/$USER/.qgis2/python/plugins` sur Ubuntu.

De même, une capture d'écran avec la fenêtre des messages de QGIS serait d'une grande aide. Merci :)

**Comment by Guts** [comment]
Non reproduit ce jour.
Pourra être réouverte quand le problème sera de nouveau constaté.
