### ISSUE TITLE
Multiplication de barre d'attente

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#116]
![capture_plugin4](https://cloud.githubusercontent.com/assets/20684784/25268397/dff32b74-2678-11e7-8686-a9d958de1805.PNG).

j'ai de nouveau plusieurs barres d'attente, suite au plantage "recherche rapide". Les barres semblent apparaitre après un tous les plantages.

**Comment by smavd** [comment]
Dupliquée cf. #111

**Comment by Guts** [comment]
Duplicate of #127
