### ISSUE TITLE
Probléme d'affichage du plugin lors de son ancrage à QGIS

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#122]
A son ouverture, le plugin s'ancre à droite dans une fenêtre dédiée. L'ancrage n'est pas correctement dimensionner. La fenêtre est rognée dans sa hauteur et sa largeur. Ainsi liste des résultats est rognée, la pagination et le bouton fermer ne sont pas visibles (voir la copie d'écran ci-jointe)

- Anomalie identifiée dans la version 1.5 du plugin 
- QGis 2.14.15 Essen
- Ecran utilisé 15'
- Résolution 1366 * 768

![ancrage_plugin](https://cloud.githubusercontent.com/assets/14051239/26622217/ed366cf2-45e9-11e7-859a-bcb9ac544a0c.PNG)

**Comment by Guts** [comment]
Pour traiter cette demande, il faudrait pouvoir disposer des informations sur l'écran utilisé (multi-écran ? redimensionnement ? résolution ?)

**Comment by Guts** [comment]
A reproduire @vblanlot

**Comment by Guts** [comment]
Bug non reproduit et certainement indépendant du plugin, mais plutôt de QGIS et de la gestion de l'interface graphique.
