### ISSUE TITLE
Ajouter des couches Oracle via le plugin

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#124]
## Mise en contexte technique

> Permettre d'ajouter les données Oracle référencées dans Isogeo.
> Doc QGIS : http://docs.qgis.org/2.14/fr/docs/user_manual/working_with_vector/supported_data.html#oracle-spatial-layers

Le morceau de code suivant permet d'ajouter une couche Oracle via la console et l'interpréteur Python de QGIS pendant une session d'utilisation : 

``` python
from qgis.core import QgsDataSourceUri, QgsProject
import db_manager.db_plugins.oracle.connector as oracle_con

uri = QgsDataSourceUri()
host = "***.***.**.**"
port = "1521"
user = "****************"
password = "****************"
base_name = "isoora"

uri.setConnection(host, port, base_name, user, password)
c = oracle_con.OracleDBConnector(uri, "Oracle_Isogeo")

uri.setDataSource("ISOGEO_TEST_SPATIAL", "DEPARTEMENT", "GEOM")

layer = QgsVectorLayer(uri.uri(), "admin_express_DEPARTEMENT", "oracle")

lyr = QgsProject.instance().addMapLayer(layer)
```

Cela confirme que l'ajout de couche Oracle est possible une fois qu'on dispose de toutes les informations nécessaires à la connexion à la base de données.

## Fonctionnement attendu

On emploierait un **fonctionnement analogue à celui de l'ajout de couche provenant d'une base de données PostGIS**.

En premier lieu, l'utilisateur devra avoir enregistré une connexion à la base de données Oracle en question : 
![image](https://user-images.githubusercontent.com/41120579/103878424-b41db000-50d6-11eb-95d2-bb08bfabf0e9.png)

Les mot de passe et identifiant devront avoir était enregistrés. Selon l'avancement du développement sur #321 , la connexion aura pu être configurée via un "Service" (fichier de configuration). 

De cette manière, le plugin QGIS pourra accéder à toutes les informations nécessaires pour se connecter à la BDD Oracle via les QSettings (Oracle>connections>*nom donné à la connexion par l'utilisateur*) : 
![image](https://user-images.githubusercontent.com/41120579/103879022-94d35280-50d7-11eb-8541-399ad7a681f3.png)

Au moment du remplissage du tableau des résultats, chaque fiche de métadonnées utilisée pour remplir la page du tableau est "inspectée" à la recherche des différentes options d'ajout disponibles : 
1. si le format de fiche est "Oracle", on parcourt les connexions à une BDD Oracle enregistrée dans QGIS (via les QSettings), alors ;
2. si la valeur de la **variable "database"** (dans les QSettings : Oracle>connections>*nom donné à la connexion par l'utilisateur*>database) d'une des connexions est égale à celle de l'**attribut "path"** de la fiche, alors ;
3. on utilise cette connexion pour parcourir les tables de la BDD Oracle accessibles ;
4. si le schéma d'une des tables correspond à la valeur de l'attribut "name" de la fiche de métadonnée Isogeo, alors ;
5. on considère que la couche pourra être ajoutée via le plugin en utilisant la connexion sélectionnée sur le critère du **nom** de la BDD Oracle.

## Implémentation

Cela impliquera notamment trois modifications du code : 

- [ ] Afin de récupérer les informations de connexions aux BDD Oracle enregistrées par l'utilisateurs, on pourra, au choix (préférence pour la deuxième option):

  * ajouter une méthode analogue à la méthode *build_postgis_dict()* du module **ResultsManager**, intitulée *build_oracle_dict()*

  * remplacer la méthode *build_postgis_dict()* par une méthode *build_connection_dict()* qui devra gérer les connexions aux BDD PostGIS et Oracle et éventuellement rajouter des sous-méthodes pour rendre le code plus lisible.

- [ ] Afin de détecter la nouvelle option d'ajout de couche au canevas (via une table Oracle), au cours du remplissage du tableau des résutats : il faudra modifier la méthode *show_results()* du module **ResultsManager** de manière à gérer le cas des fiches de format "oracle". Si possible, il faudrait modifier le morceau de code en charge de la gestion des fiches de format "postgis" de manière à le rendre générique et à le faire fonctionner pour les formats "oracle" et "postgis".

- [ ] Afin d'effectuer l'ajout de la couche au canevas via une table Oracle, le morceau de code en charge de cette opération (actuellement c'est la méthode **LayerAdder**.*adding()*) devra être modifié de manière à gérer le cas des tables Oracle. Il s'agirait de modifier le code de manière à rendre générique l'ajout d'une couche à partir d'une table, qu'il s'agisse d'une BDD PostGIS ou Oracle. Cela pourra passer par l'ajout d'une méthode dédiée au module **LayerAdder** qu'on pourra intituler *add_from_database()*.

**Comment by SimonSAMPERE** [comment]
A priori c'est faisable et ça ressemble à ce qu'on fait déjà avec PostGIS, à voir si on a les infos nécessaire dans les fiches de métadonnées pour retrouver la bonne connexion.

**Comment by SimonSAMPERE** [comment]
@mathieubecker

**Comment by Mouzzi-C** [comment]
La connexion à la base Oracle est bien configurée avec l'utilisateur de test. Aucune base de données n'est détectée alors qu'il existe 7 données dans le partage du GT Isogeo TEST.

![image](https://user-images.githubusercontent.com/63340073/122246266-b296b600-cec6-11eb-93a2-a6db348a83d3.png)

**Comment by Mouzzi-C** [comment]
Voilà le fichier de logs 
[log_isogeo_plugin.log](https://github.com/isogeo/isogeo-plugin-qgis/files/6668938/log_isogeo_plugin.log)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C en fait ce comportement est normal, vu que tu as une seule connexions configurée pour cette base de données Oracle, pas besoin de proposer de choisir une connexion.

Est-ce-que tu peux : 
* voir dans le tableau des résultats si les couches Oracles sont ajoutables (normalement si ya qu'une seule connexion elle est proposée par défaut)
* configurer une autre connexion à la même base (idéalement avec un autre user) et regarder si l'interface de configuration des connexions Oracle se remplie, auquel cas, en choisir une et vérifier que ton choix se répercute dans les options d'ajout de couche

**Comment by Mouzzi-C** [comment]
Ça fonctionne bien sur QGIS 3.16.

Sur la 3.10 par contre : 
1. Lorsqu'un seul utilisateur est configuré, le choix d'ajouter la donnée en passant par la base Oracle n'est pas proposé
2. Lorsqu'un deuxième utilisateur est configuré, les choix ne sont pas proposés dans le plugin (même quand on recharge les connexions)

[log_isogeo_plugin.log](https://github.com/isogeo/isogeo-plugin-qgis/files/6671597/log_isogeo_plugin.log)

Je vais tester sur une autre machine pour voir si je peux reproduire le comportement de la 3.10

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, normalement ça y est ça fonctionne sur QGIS 3.10.

Est-ce-que les données du user Isogeo_DEMO_SPATIAL sont partagées à une Appli ? ça serai bien de vérifier que telle connexion permets bien d'ajouter tel table.

**Comment by Mouzzi-C** [comment]
Yes, je les ai ajouté au partage de test. C'est tout bon sur la 3.10 et la 3.16 👍
