### ISSUE TITLE
Filtres - Ajouter la possibilité de filtrer sur les données

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#125]
Il est désormais possible de filtrer sur les données, sans distinction de vecteurs et raster. Ça répond parfaitement à une demande récurrente de pouvoir afficher les résultats des vecteurs ET des rasters ET des ensembles de série.

Je propose donc de l'ajouter aux filtres par types. Reste à voir l'intitulé qui peut être touchy.
Est-il possible d'avoir une petite hiérarchie dans ce menu là ? genre :

Données
-- Vecteurs seulement
-- Images (raster) seulement

**Comment by vblanlot** [comment]
Filtre "donnée" dispo est fonctionnel
Le ticket peut-être fermé

ps : pour une meilleure ergo, il serait peut-être pertinent d'afficher ce filtre avant "Donnée (vecteur)" et "Donnée (raster)".

**Comment by Guts** [comment]
> ps : pour une meilleure ergo, il serait peut-être pertinent d'afficher ce filtre avant "Donnée (vecteur)" et "Donnée (raster)".

J'ai essayé mais c'est assez compliqué en fait. A voir dans un second temps.
