### ISSUE TITLE
Bug sur filtre géographique

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#126]
Le filtre géographique ne fonctionne pas, il me ressort des données qui ont une emprise qui n'intersecte en aucun cas l'emprise de la carte.

**Comment by Guts** [comment]
Merci pour votre intérêt et d'avoir pris le temps de tester et surtout celui de signaler !

Pour améliorer notre diagnostic, merci de respecter [les recommandations détaillées sous ce lien](https://github.com/isogeo/isogeo-plugin-qgis/wiki/Questions-fr%C3%A9quentes#comment-signaler-un-comportement-anormal-).

Merci :)

**Comment by Guts** [comment]
Voir la réponse dans le #160
