### ISSUE TITLE
Multiplication des barres de progression

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#127]
Il y a encore le problème de la multiplication des barres de progression.
![bug_barre_de_chargement](https://user-images.githubusercontent.com/20684784/30100240-77612872-92e8-11e7-82ef-b5ef99189b8a.PNG)

**Comment by Guts** [comment]
Merci pour votre intérêt et d'avoir pris le temps de tester et surtout celui de signaler !

Pour améliorer notre diagnostic, merci de respecter [les recommandations détaillées sous ce lien](https://github.com/isogeo/isogeo-plugin-qgis/wiki/Questions-fr%C3%A9quentes#comment-signaler-un-comportement-anormal-).

Merci :)

#111 #116
