### ISSUE TITLE
Recherche par thème

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#128]
Peut-on rajouter la recherche par thématique (proposition remplacer "propriétaire" par thématique si il y a un problème de place sur l'interface)

**Comment by Guts** [comment]
Qu'entendez-vous par recherche par thématique ? A quel filtre Isogeo cela correspondrait ?

**Comment by smavd** [comment]
Bonjour,

Cela correspond aux catalogues virtuels dans app

**Comment by Guts** [comment]
Les catalogues sont des étiquettes destinées uniquement aux admininistrateurs et non aux utilisateurs en consultation. Ils n'apparaissent donc pas dans l'API en lecture et par conséquent dans les applications tierces de consultation tel le plugin QGIS.
