### ISSUE TITLE
erreur python au chargement d'un fichier

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#129]
Nota : le fichier se charge bien, malgré l'erreur

![bug_chargement_ecw](https://user-images.githubusercontent.com/20684784/30100511-6ba90972-92e9-11e7-940b-99ffb4cab2c1.PNG)

**Comment by Guts** [comment]
Merci pour votre intérêt et d'avoir pris le temps de tester et surtout celui de signaler !

Pour améliorer notre diagnostic, merci de respecter [les recommandations détaillées sous ce lien](https://github.com/isogeo/isogeo-plugin-qgis/wiki/Questions-fr%C3%A9quentes#comment-signaler-un-comportement-anormal-).

Merci :)
