### ISSUE TITLE
Données non ajoutable

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#130]
J'ai des couches mis en non ajoutables dans le plugin, alors que tout semble bon 
- Couches dans même répertoire que d'autres couches ajoutables
- Couche avec le bon lien dans l'APP Isogeo
- Couche qui s'ouvre bien manuellement

![bug_donnees_ajoutable](https://user-images.githubusercontent.com/20684784/30101204-b8616ff0-92eb-11e7-9bb6-d5f906d401fc.PNG)

**Comment by Guts** [comment]
Pour améliorer notre diagnostic, merci de respecter [les recommandations détaillées sous ce lien](https://github.com/isogeo/isogeo-plugin-qgis/wiki/Questions-fr%C3%A9quentes#comment-signaler-un-comportement-anormal-).

Merci :)

Pouvez-vous aussi donner les liens APP des données concernées svp ?

**Comment by smavd** [comment]
Bonjour,

https://app.isogeo.com/groups/d960ae611b9345f69da57f42565ebbc3/resources/861aa4c444bc4ba1adb6c9929dfa7dac/identification

https://app.isogeo.com/groups/d960ae611b9345f69da57f42565ebbc3/resources/fb53017f2dd5469cb259a1881ce00fe3/identification

Voici deux liens posant problème

Cordialement

**Comment by Guts** [comment]
Lié à la façon dont les chemins de fichiers/dossiers Windows, notamment sur les réseaux locaux, sont gérés par Python 2.x. Vivement QGIS 3 !

Corrigé par f680783f26fad8df42af2d58fbcdedf0a3b377f1.
