### ISSUE TITLE
Possibilité de requêter uniquement les entités dans la vue courante (WFS)

### ISSUE THREAD

**Issue by admagt** [isogeo/isogeo-plugin-qgis#131]
Sous QGIS, lorsqu'on ajoute manuellement une couche WFS on peut choisir l'option "Requêter uniquement les entités dans la vue courante" qui ajoute un paramètre  restrictToRequestBBOX='1' à la source de la couche.
Est-il possible d'activer une telle option lorsqu'on charge un couche WFS depuis le plugin Isogeo ? Notamment pour éviter de charger des données France entière alors que la vue courante se situe à l'échelle d'une ville.

Nous rencontrons notamment ce souçi sur la couche france_shops_point (cf screenshot et fichier de logs) : quelque soit la vue courante au moment de l'appel de la couche, QGIS cherche à récupérer toutes les données d'un coup (environ 130 000 points ici), toujours dans le même ordre. Il est finalement limité à 100'000 objets par Geoserver et ne charge donc jamais l'Est de la France même si on a zoomé sur Strasbourg au préalable.

![captureqgis](https://user-images.githubusercontent.com/31856613/30282095-91f7a30c-9714-11e7-8f09-be496daf3b21.PNG)

Si on a créé manuellement une couche WFS dans QGIS ayant pour source 
`restrictToRequestBBOX='1' srsname='EPSG:3857' typename='magosm:france_shops_point' url='http://magosm.magellium.com/geoserver/wfs?' version='auto' table="" sql="`
alors la requête se limite bien à la vue courante.

Voici un extrait du fichier log_isogeo_plugin.log :
[log_isogeo_plugin_extrait.txt](https://github.com/isogeo/isogeo-plugin-qgis/files/1293012/log_isogeo_plugin_extrait.txt)

Merci

**Comment by Guts** [comment]
Paramètre "restrictToRequestBBOX" vu dans https://qgis.org/api/classQgsVectorLayer.html

**Comment by Guts** [comment]
Le paramètre est automatiquement ajouté lors de la construction des URLS WFS (voir https://github.com/isogeo/isogeo-plugin-qgis/blob/master/modules/url_builder.py#L208) et EFS (voir https://github.com/isogeo/isogeo-plugin-qgis/blob/master/modules/url_builder.py#L153).
