### ISSUE TITLE
Basculer l'aide en ligne sur GitBook

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#132]
- [x] rédiger l'aide en ligne sur gitbook
- [x] changer les liens dans le plugin (onglet settings)
- [x] changer les liens dans Manager pour pointer sur https://isogeo.gitbooks.io/app-plugin-qgis/content

**Comment by Guts** [comment]
@vblanlot : tu peux te charger de changer le lien dans les applis dans Manager stp ?

**Comment by vblanlot** [comment]
Le lien vers l'aide en ligne fonctionne
Le lien à été mis à jour dans les applis dans Manager
Ce ticket peut être fermé
