### ISSUE TITLE
Améliorer les performances du test d'emplacement des fichiers

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#135]
Lors de l'affichage des résultats, le plugin teste l'accès aux données de type fichier (vecteurs et rasters) en essayant d'atteindre le chemin stocké dans le champ emplacement (_path_) des métadonnées. Problème : c'est très long et chaque chemin est testé à chaque fois que l'utilisateur demande à afficher les résultats, alors que bien souvent ce sont des répertoires entiers qui ne sont pas accessibles par l'utilisateur ayant lancé QGIS.

Mettre en cache les répertoires déjà testés permettrait de réduire le temps d'affichage des résultats au fur et à mesure de l'utilisation du plugin.

Recharger le plugin doit vider ce cache.

**Comment by vblanlot** [comment]
RAS
Le ticket peut passer dans "Done" je n'ai pas les droits pour le faire moi-même
