### ISSUE TITLE
Faciliter le rapport d'anomalie

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#139]
- [x] créer un modèle de rapport d'issue (voir [doc github](https://help.github.com/articles/creating-an-issue-template-for-your-repository/))
- [x] ajouter un bouton pour localiser le fichier log
- [x] ajouter une option permettant d'activer un mode debug - uniquement pour le canal expérimental ?
- [x] améliorer bouton de signalement dans l'interface QGIS pour lancer une fenêtre dédiée plus détaillée

**Comment by Guts** [comment]
A partir de la version 1.6.1 :

- les fichiers de logs sont situés dans un sous-dossier `_logs` dans le dossier du plugin.
- un bouton dans l'interface permet à l'utilisateur d'accéder directement au dossier (voir capture)
- en cliquant sur le bouton de signalement, le ticket est d'ores et déjà préparé : [url test](https://github.com/isogeo/isogeo-plugin-qgis/issues/new?title=TITRE%20DU%20PROBLEME%20SIGNALE%20-%20plugin%20v1.6.1-beta1%20QGIS%202.18.21%20(Windows-10-10.0.17134)&labels=bug&milestone=4)
- le niveau de log est automatiquement déduit à partir de la version du plugin (selon ce qu'il y a d'indiqué dans le fichier `metadata.txt`)

![image](https://user-images.githubusercontent.com/1596222/42762756-66d7aefc-8911-11e8-9c05-ec53172a7ac0.png)

**Comment by vblanlot** [comment]
C'est tout bon, ça veut dire quoi > le niveau de log est automatiquement déduit à partir de la version du plugin (selon ce qu'il y a d'indiqué dans le fichier metadata.txt) ?
Merci
