### ISSUE TITLE
Utiliser les icônes par défaut de QGIS

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#140]
Actuellement, le plugin utilise ses propres icônes, même pour celles déjà présentes dans QGIS (wfs, wms, etc.), alors que celles-ci sont donc déjà chargées par le logiciel.

Pour gagner en performances (très légèrement) et en cohérence avec le reste de l'interface, il s'agit de basculer sur les icônes intégrées à QGIS.

Fichier de référence : https://github.com/qgis/QGIS/blob/master/images/images.qrc

**Comment by vblanlot** [comment]
J'ai testé sur quelques icônes (formats de données notamment) ça semble fonctionner normalement. En revanche je souhaiterais être exhaustif dans mon test et m'assurer que le plugin utilise bien la bibliothèque intégrée à QGIS. Quelle procédure dois-je suivre ? Merci

**Comment by Guts** [comment]
Ouvrir le fichier de référence indiqué en ouverture du ticket et comparer :) 
Sinon surtout vérifier qu'il n'y a rien de manquant dans les différentes UI.

**Comment by vblanlot** [comment]
Il ne manque rien dans la UI
Avec quoi comparer le fichier de référence (un fichier dans le dossier du plugin...) ?

**Comment by Guts** [comment]
S'il n'y a rien de manquant alors c'est que c'est bon.
Pour le reste, il faut se pencher sur la structure du plugin et c'est lié aux compétences de dév.
