### ISSUE TITLE
Service licence

### ISSUE THREAD

**Issue by pcav** [isogeo/isogeo-plugin-qgis#146]
Thanks for the new service. Did you check the licence for it? Sorry to bother, I just want to double check.

**Comment by Guts** [comment]
So, I've missed something. I didn't know that use these API method was under licensing. How can we make us compliant?

**Comment by pcav** [comment]
I'm not a lawyer, but normally services have a licence associated. I would suggest to check ESRI licence, and eventually issue a warning for the user "Please check that your use is compliant with the licence", better if with a link to the licence.
Thanks.

**Comment by Guts** [comment]
I'm not a lawyer either, but we do not embed Esri services, we just use `QgsVectorLayer(uri, name, 'arcgisfeatureserver')` and `QgsVectorLayer(uri, name, 'arcgismapserver')` ability to allow our end-users add their own services to the map canvas without setting anything in QGIS.

Maybe do you want API keys to test our plugin?

**Comment by pcav** [comment]
Well, if you are confident there is no problem, just disregard my notes - I might have been overcautious.

**Comment by Guts** [comment]
Thanks you to trust me. i'll send you some demo API keys in case of you would want to test by yourself this release or a future one :).
