### ISSUE TITLE
Les mots-clés ne sont pas cochés au chargement d'une recherche enregistrée - plugin v1.6.1-beta1

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#159]
Pour reproduire :

1. faire une recherche avec au moins un mot-clé
2. sauvegarder la recherche
3. réinitialiser la recherche
4. sélectionner la recherche précédemment sauvegardée

=> les mots-clés sont bien ajoutés à la requête mais ne sont pas cochés dans la liste déroulante.

**Comment by vblanlot** [comment]
Ok c'est tout bon.

Petite remarque UX : une fois la recherche sauvegardée, il faut nécessairement "rafraîchir le plugin" pour la voir apparaître dans la liste des recherches rapides et dans l'onglet paramètres > recherches sauvegardées
