### ISSUE TITLE
Add data through an OGC geographical service

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#16]
- [X] WMS
- [X] WFS
- [ ] WMTS

**Comment by TheoSinatti** [comment]
Now works for WMS and WFS. 
Adding WMTS layers should come soon. But it does not appear in PyQGIS documentation, so I am waiting for new informations from here : http://gis.stackexchange.com/questions/207995/how-to-load-a-wmts-layer-in-qgis-using-pyqgis

**Comment by Guts** [comment]
It dosen't work if web service requires an authentication (which could be managed in QGIS). @TheoSinatti : plugin should handle this case, no? Test with PPIGE.

**Comment by Guts** [comment]
The new services URLs are not taken in account.
Example with this metadata which has a WFS and a WMS as it can be seen here: http://open.isogeo.com/s/344d51c3edfb435daf9d98d948fa207e/Sbd1w7PgqE8n7LDq3azRqNhiMHZf0/m/eeeb7a31c27145e2a3c0f08415f38aed

But it's not available within the plugin:

![plugin_qgis_services](https://cloud.githubusercontent.com/assets/1596222/19034436/bb2e1b1c-8963-11e6-9469-0eb063b15b07.PNG)

**Comment by Guts** [comment]
Closed.
WMTS needs a dedicated study => #79
