### ISSUE TITLE
Ajouter une information sur les conditions et limitations pour les utilisateurs finaux

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#164]
Demande effectuée par le @smavd.

## Description du besoin

Certaines données sont soumises à des restrictions fortes en termes d'usage ou de diffusion. Cette information peut être documentée par l'administrateur/éditeur dans Isogeo et apparaît aujourd'hui lors de la consultation de la métadonnée détaillée (cf [doc](http://help.isogeo.com/qgis/fr/usage/metadata.html#display)).

Le besoin est d'attirer davantage l'attention de l'utilisateur final **au moment de l'ajout d'une couche au canevas**.

### Aucune alerte

Lorsque la métadonnée contient :

* aucune limitations.
* ou aucune restriction et "directive INSPIRE = pas de restriction au sens de la directive"

### Information temporaire non bloquante

Lorsque la métadonnée contient :

* type légal et n'importe laquelle des restrictions
* et/ou n'importe laquelle des directives

Le nom de la limitation (voire sa description) s'affiche alors dans la messagebox de QGIS.

### Avertissement - popup bloquante

Lorsque la métadonnée contient :

* type = sécurité

Un avertissement s'affiche dans une popup message : attention, usage et diffusion soumis à de fortes restrictions de sécurité.

Le message est systématique.

### Options

Cette évolution pouvant poser des problèmes au niveau de l'expérience de l'utilisateur final mais ne devant pas être facile à désactiver via une simple case à cocher, cela passera par des recherches spécifiques :

* désactivable : `:internal-disable-cgus-alerts'
* réactiver : `:internal-enable-cgus-alerts'

**Comment by Mouzzi-C** [comment]
Environnement : Windows 10, QGIS 3.4.9

Tests effectués avec le partage d'[Isogeo Test](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/admin/shares/3270d22682224ed4b928b62491f260ad) sur les fiches suivantes : 
 * [b359a036282142a0a51464f188edf413](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/b359a036282142a0a51464f188edf413/identification) : Fiche avec limitations non renseignées
 * [f4b13ddcba244f6c96e8890b52c01cee](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/f4b13ddcba244f6c96e8890b52c01cee/identification) : Fiche avec limitation de type : légale et une directive.
 * [2a14bea741ee423c8ec83bd8993cfa5f](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/2a14bea741ee423c8ec83bd8993cfa5f/constraints) : Fiche avec limitation  de type : légale sans directive
 * [c1dc83779f0a4b449b747e544392c22f](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/c1dc83779f0a4b449b747e544392c22f/identification) : Fiche avec limitation de type : Sécurité

Ces trois fiches sont étiquetées "qgis" afin de les trouver plus facilement dans le plugin.

## Comportements constatés
1. Lorsque que l'on clique sur la fiche avec limitation de type sécurité, rien ne s'affiche. On obtient cette erreur : 
2020-12-01T17:51:39     WARNING    Traceback (most recent call last):
              File "C:/Users/CarloMOUZANNAR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\metadata_display.py", line 292, in show_complete_md
              s_in.get("specification").get("published"), "%Y-%m-%dT%H:%M:%S"
             TypeError: strptime() argument 1 must be str, not None

2. Lorsque l'on clique sur la fiche avec limitation de type légale avec un directive, aucun message ne s'affiche.
3. Lorsque l'on clique sur une fiche avec aucune limitation renseigné, rien ne s'affiche.

**Comment by SimonSAMPERE** [comment]
Merci pour ta remarque, je vais créer une issue concernant l'erreur Python que tu as remarqué. 

Concernant la fonctionnalité "Ajouter une information sur les conditions et limitations pour les utilisateurs finaux" décrite par ce ticket, elle est sensée se déclencher quand on ajoute une donnée à la carte et pas lorsqu'on affiche la fiche de métadonnées détaillée.
Les fiches utilisées pour le test doivent donc au moins être associées à une couche WMS ou à une donnée fichier accessible depuis ton ordinateur afin que tu puisses les ajouter à la carte.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, concernant la fonctionnalité "Ajouter une information sur les conditions et limitations pour les utilisateurs finaux" décrite par ce ticket, elle est censée se déclencher quand on ajoute une donnée à la carte et pas lorsqu'on affiche la fiche de métadonnées détaillée.

Je me suis rendu compte suite à ta remarque que ça n'était pas clair, j'ai donc mis à jour la description du ticket : 
![image](https://user-images.githubusercontent.com/41120579/100868772-5f19c900-349c-11eb-8eac-fe0e4106154a.png)

Les fiches utilisées pour le test doivent donc au moins être associées à une couche WMS ou à une donnée fichier accessible depuis ton ordinateur afin que tu puisses les ajouter à la carte.
