### ISSUE TITLE
Module indépendant de recherche par mots-clés

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#194]
**Livrable :** Un module développé dans la même version de Python que celle utilisée dans QGIS (3.7 à date), en dehors de QGIS et utilisant seulement PyQt5. Il sera contenu dans un dossier `test/dev/search_by_keyword` dans le dépôt du plugin.

**Objectif :** Tester l'utilisation de PyQt pour fournir une interface de sélection de mots-clés Isogeo

**Fonctionnalités :**

- Remplissage d'une liste déroulante (QComboBox) avec les mots-clés renvoyés par l'API suite à une requête et dont les lignes sont cochables

- Sélection (cochage) de plusieurs mots-clefs en même temps

- La sélection (cochage) d'un des items de la liste déroulante lance une requête à l'API portant sur les fiches de métadonnées auxquelles sont associés les mots-clés cochés

- Suite à la requête, le nombre de fiches de métadonnées renvoyé par l'API s'affiche dans l'interface et le contenu de la liste déroulante s'adapte à la réponse de l'API

**Comment by Guts** [comment]
Déterminer si une requête est lancée à chaque mot-clé coché ou si l'utilisateur peut sélectionner plusieurs mots-clés puis lancer la recherche.

**Comment by SimonSAMPERE** [comment]
Une requête est lancée à chaque mot-clé coché et la liste déroulante s'actualise à chaque requête. Les mots-clés proposés à l'utilisateurs dépendant donc de sa sélection. Cela permet d'éviter qu'aucune fiche de métadonnées ne corresponde à la sélection de mots-clés de l'utilisateurs

**Comment by Guts** [comment]
Finitions :

- les mots-clés sélectionnés doivent être remontés
- le _place holder_ `-- Keywords --` ne devrait pas être cochable

**Comment by Guts** [comment]
done with #206
