### ISSUE TITLE
Ajouter une couche au canevas - Toutes les options

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#196]
Le plugin doit permettre d'**ajouter au canevas une couche** décrite par une fiche de métadonnées **depuis le tableau des résultats**. A condition que les informations nécessaires à l'ajout apparaissent dans la fiche ou lui soient associées. Il existe **plusieurs options d'ajout** possibles qui doivent toutes fonctionner dans QGIS 3 :

- [x] via une **table PostGIS** (lorsque la connexion à la BD a déjà été fait dans QGIS et que les informations de connexion apparaissent dans les QSettings)

- [x] via le chemin local d'un **fichier** (lorsque le fichier est stocké sur l'ordinateur et que le chemin vers le fichier est valide et renseigné dans la fiche)

- via un **Service OGC** (lorsqu'une fiche de service est associée à la fiche de métadonnées)
 
  - [x] WMS #337

  - [x] WFS #300 

  - [x] WMTS #336 

- via un **Service ESRI** (lorsqu'une fiche de service est associée à la fiche de métadonnées)

  - [x] EFS #300 

  - [x] EMS

**Comment by Guts** [comment]
Utiliser les services existants. Par exemple : https://cms.geobretagne.fr/services
Pour les Esri, chercher sur les Internets.
