### ISSUE TITLE
Tester 'plugin_dependencies'

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#208]
https://qgis.org/en/site/forusers/visualchangelog38/index.html#feature-support-for-plugin-dependencies

**Comment by SimonSAMPERE** [comment]
doesn't work

**Comment by Guts** [comment]
> Ah ! non ! c’est un peu court, jeune homme ! On pouvait dire… Oh ! Dieu !… bien des choses en somme.

Il s'agit en fait d'un mécanisme permettant à un plugin de déclarer sa dépendance à d'autres plugins QGIS et non pas à des packages Python. Cela ne présente donc aucun intérêt pour le cas du plugin Isogeo.
