### ISSUE TITLE
Error when QGIS is launched : No module named resource_rc

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#25]
Doesn't affect the plugin functioning though.

**Comment by TheoSinatti** [comment]
Error reappeared... Seems like manually modifying a resource / ui file induces this problem.

**Comment by TheoSinatti** [comment]
Found the root of the problem, and a work-around.
http://gis.stackexchange.com/questions/139625/qgis-plugin-problems-importing-resources-resources-rc-file-plugin-doasnt-l

**Comment by Guts** [comment]
The plugin published as version beta 0.2.1 crashes at the QGIS boot. Maybe [automate Qt compilation](https://bitbucket.org/isogeo/isogeo-plugin-qgis/src/4bd7016a5199cd98f25d096c285452d8aaadf43a/Isogeo/qt2pyqt.bat?at=master&fileviewer=file-view-default).

> Impossible de charger l'extension isogeo_search_engine provoque une erreur lors de l'appel de sa méthode classFactory()
> 
> 
> Traceback (most recent call last):
>   File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 219, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "C:/Users/$USER/.qgis2/python/plugins\isogeo_search_engine\__init__.py", line 34, in classFactory
>     from .isogeo import Isogeo
>   File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/Users/$USER/.qgis2/python/plugins\isogeo_search_engine\isogeo.py", line 32, in 
>     from isogeo_dockwidget import IsogeoDockWidget
>   File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/Users/$USER/.qgis2/python/plugins\isogeo_search_engine\isogeo_dockwidget.py", line 30, in 
>     os.path.dirname(__file__), 'isogeo_dockwidget_base.ui'))
>   File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
>     exec(code_string.getvalue(), ui_globals)
>   File "", line 548, in 
>   File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ImportError: No module named resources_rc
> 
> 
> Version de Python :
> 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
> 
> 
> Version de QGIS :
> 2.8.9-Wien Wien, 26c3ece
> 
> Chemin vers Python : ['C:/OSGEO4~1/apps/qgis-ltr/./python', u'C:/Users/$USER/.qgis2/python', u'C:\\Users\\$USER\\Documents\\GIS\\Plugins\\Isogeo', u'C:/Users/$USER/.qgis2/python/plugins', 'C:/OSGEO4~1/apps/qgis-ltr/./python/plugins', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\setuptools-0.9.8-py2.7.egg', 'C:\\OSGEO4~1\\bin\\python27.zip', 'C:\\OSGEO4~1\\apps\\Python27\\DLLs', 'C:\\OSGEO4~1\\apps\\Python27\\lib', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\plat-win', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\lib-tk', 'C:\\OSGEO4~1\\bin', 'C:\\OSGEO4~1\\apps\\Python27', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/$USER/.qgis2//python']

**Comment by Guts** [comment]
Not reproduced with version 0.3.0-beta
