### ISSUE TITLE
Ajouter un script de reset des paramètres avancés de QGIS

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#256]
### Objectif

Pour **tester l'authentification à l'API Isogeo via le plugin QGIS**, il faut pouvoir simuler une première utilisation et donc une première authentification.

### À faire

- [x] **Créer** le script `modules/api/reset_qsettings.py` permettant de supprimer le groupe 'isogeo' des paramètres avancés de QGIS

- [x] **Documenter** l'existence et l'utilisation du script dans le [wiki](https://github.com/isogeo/isogeo-plugin-qgis/wiki/tests)

**Comment by Guts** [comment]
Utiliser les services existants. Par exemple : https://cms.geobretagne.fr/services
Pour les Esri, chercher sur les Internets.

**Comment by Guts** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/wiki/modules_dir#reset_qsettingspy
