### ISSUE TITLE
[SettingsManager] Création d'un module héritant de PyQt.QtCore.QSettings

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#258]
## Objectif

Modulariser et centraliser la gestion des *`QSettings`*. Gérer la persistence des différents paramètres. Dans certains cas, on veut que les paramètres puisse être inscrit dans un fichier JSON en plus des *`QSettings`* et inversement. Deux cas de figure :

1. Plugin configuré sur un poste puis zippé et installé sur un autre poste. Pour que le paramétrage effectué sur le premier poste se répercute sur le second, il faut que les paramètres en question aient été stockés dans des fichiers JSON qui se trouvent dans le ZIP.

2. Plugin mis à jour. Il y a un risque que tous les paramètre stockés dans des fichiers JSON soient supprimés lorsque ces fichiers seront écrasés. Il faut donc les stocker également dans les *`QSettings`* pour pourvoir les remettre dans les fichiers JSON lors du premier re-démarrage du plugin après la mise à jour.

L'idéal serait donc de dupliquer tous les paramètres et de décider pour chacun si c'est le JSON ou le QSetting qui doit prévaloir dans chaque situation.

Il faut également penser à la récupération de la valeur des paramètres stockés dans le format de la précédente version du plugin Isogeo.

## Principe

Créer une nouvelle classe pour gérer le stockage et la récupération de tous les paramètres dans les *`QSettings`*, cela concerne :

* les paramètres d'authentification
* les recherches rapides et la recherche par défaut
* les paramètres de connexion aux bdd
* l'url du portail
* le cache fichiers et services et PostGIS
* les URLs Isogeo (API, app et help)

Le **`SettingsManager`** serat instancié dans le script de chaque module ayant besoin d’interagir avec les paramètres, comme c'est le cas avec le **`IsogeoPlgTools`**.
Dans chaque configuration, vérifier que la valeur des paramètres après installation/mise à jour est conforme aux SPEF.

## Inventaire des paramètres

<details>
<summary>Paramètres natifs de QGIS</summary>
<ul>
<li><code>locale/userLocale</code></li>
<li><code>proxy/proxyEnabled</code></li>
<li><code>proxy/proxyType</code></li>
<li><code>proxy/proxyHost</code></li>
<li><code>proxy/proxyPort</code></li>
<li><code>qgis/style</code></li>
<li><code>PostgreSQL/connections/.../database</code></li>
<li><code>PostgreSQL/connections/.../host</code></li>
<li><code>PostgreSQL/connections/.../port</code></li>
<li><code>PostgreSQL/connections/.../username</code></li>
<li><code>PostgreSQL/connections/.../password</code></li>
<li><code>PostgreSQL/connections/.../service</code></li>
<li><code>PostgreSQL/connections/.../savePassword</code></li>
<li><code>PostgreSQL/connections/.../saveUsername</code></li>
<li><code>Oracle/connections/.../database</code></li>
<li><code>Oracle/connections/.../host</code></li>
<li><code>Oracle/connections/.../port</code></li>
<li><code>Oracle/connections/.../username</code></li>
<li><code>Oracle/connections/.../password</code></li>
<li><code>Oracle/connections/.../savePassword</code></li>
<li><code>Oracle/connections/.../saveUsername</code></li>
<li><code>projections/layerDefaultCrs</code></li>
<li><code>app/projections/defaultProjectCrs</code></li>
</ul>
</details>

<details>
<summary>Paramètres du plugin Isogeo</summary>
<ul>

<li><code>isogeo/user/editor</code></li>
<li><code>isogeo/settings/portal_base_url</code></li>
<li><code>isogeo/settings/add_metadata_url_portal</code></li>
<li><code>isogeo/settings/georelation</code></li>
<li><code>isogeo/env/api_base_url</code></li>
<li><code>isogeo/env/api_auth_url</code></li>
<li><code>isogeo/env/app_base_url</code></li>
<li><code>isogeo/env/help_base_url</code></li>
<li><code>isogeo/settings/background_map_url</code></li>
<li><code>isogeo/auth/app_id</code></li>
<li><code>isogeo/auth/app_secret</code></li>
<li><code>isogeo/settings/invalid_pgdb_conn</code></li>
<li><code>isogeo/settings/prefered_pgdb_conn</code></li>
<li><code>isogeo/settings/invalid_ora_conn</code></li>
<li><code>isogeo/settings/prefered_ora_conn</code></li>
<li>fichier <code>config.json</code></li>
  <ul>
    <li><code>api_base_url</code></li>
    <li><code>api_auth_url</code></li>
    <li><code>app_base_url</code></li>
    <li><code>help_base_url</code></li>
    <li><code>background_map_url</code></li>
  </ul>
<li>fichier <code>db_connections.json</code></li>
<li>fichier <code>quicksearches.json</code></li>
</ul>
</details>

## SPET

- [x] Créer la classe **`SettingsManager`** héritant de **`PyQt.QtCore.QSettings`**. - **0,25j**
- [x] Implémenter l'utilisation du **`SettingsManager`** en remplacement de **`PyQt.QtCore.QSettings`** dans tous les modules - **0,25j**
  - [x] **`Isogeo`**
  - [x] **`Authenticator`**
  - [x] **`DataBaseManager`**
  - [x] **`MetadataDisplayer`**
  - [x] **`PortalURLManager`**
  - [x] **`SearchFormManager`**
  - [x] **`IsogeoPlgTools`**
  - [x] **`GeoServiceManager`**
  - [x] **`ResultsManager`**
  - [x] **`UserInformer`** --> nécessaire depuis qu'il ne prend plus la méthode `tr` en argument
- [x] Nettoyer les modules de l'import inutile de **`PyQt.QtCore.QSettings`** - **0,25j**
  - [x] **`LimitationsChecker`**
  - [x] **`LayerAdder`**
- [x] Gérer les recherches rapides : - **2j**
    - [x] déplacer la manipulation du fichier `quicksearches.json` dans le **`SettingsManager`**
    - [x] ajouter la création/renommage/suppression des recherches rapide dans les *`QSettings`* au **`SettingsManager`**
    - [x] récupération si mise à jour du plugin : on fusionne le contenu des *`QSettings`* avec celui du `quicksearches.json`, si doublons, on conserve celui du `quicksearches.json`, sauf pour `_current` et `Dernière recherche`
    - [x] implémenter l'utilisation du **`SettingsManager`** dans le **`QuickSearchManager`**
    - [x] tester
      - [x] création
      - [x] renommage
      - [x] suppression
      - [x] mise à jour via un zip "standard"
        - [x] pas de `quicksearch.json` + pas de *quicksearch* dans les QSettings
        - [x] pas de `quicksearch.json` + des *quicksearches* dans les QSettings
      - [x] mise à jour via un zip "*custom*"
        - [x] `quicksearch.json` sans `_current` et `Dernière recherche` + pas de *quicksearch* dans les QSettings
        - [x] `quicksearch.json` avec `_current` et `Dernière recherche` + des *quicksearches* dans les QSettings
- [x] Gérer l'URL du portail : on ajoute les paramètres concernés dans le fichier `config.json` - **1j**
  - [x] implémenter dans le **`SettingsManager`** une méthode de récupération de la valeur des paramètres concernés depuis le fichier `config.json` ou les *`QSettings`* avec **prévalence des valeurs enregistrées dans le fichier `config.json` sur celles des *`QSettings`* en cas de conflit**
  - [x] implémenter dans le **`SettingsManager`** une méthode d'ajout et de modification des paramètres concernés dans les *`QSettings`* ET dans le fichier `config.json`
  - [x] implémenter dans le **`PortalURLManager`** l'utilisation des méthodes susmentionnées du **`SettingsManager`**
- [x] Gérer les paramètres d'authentification et les URLs Isogeo : voir ce qu'on peut déplacer depuis l'**`Authenticator`** vers le **`SettingsManager`** - **2j**
  - [x] déplacer la manipulation du fichier `config.json` dans le **`SettingsManager`**
  - [x] pour `isogeo/env/api_base_url`, `isogeo/env/api_auth_url`, `isogeo/env/app_base_url` et `isogeo/env/help_base_url` ajouter la **prévalence des valeurs enregistrées dans les *`QSettings`* sur celles du fichier `config.json` en cas de conflit, uniquement si celles du fichier `config.json` sont les valeurs par défaut**
  - [x] pour les *credentials* on a actuellement prévalence des *`QSettings`* sur le fichier `client_secrets.json`, il faudrait faire l'inverse pour permettre d'écraser les *credentials* des utilisateurs via un déploiement massif en utilisant un ZIP
- [x] Gérer les paramètres de connexion aux bases de données - **1j**
  - [x] `invalid_pgdb_conn`, `prefered_pgdb_conn`, `invalid_ora_conn` et `prefered_ora_conn` restent uniquement dans les *`QSettings`*
  - [x] pas de migration du contenu du fichier `db_connections.json` dans les *`QSettings`*
  - [x] déplacer la manipulation du fichier  `db_connections.json` dans le **`SettingsManager`**
- [x] Gérer le cache des ressources inaccessibles (fichiers, services et bases PostGIS) dans le fichier `cache.json` - **2j**
  - [x] passer le cache des fichiers inaccessible uniquement dans les *`QSettings`*, potentiellement sous forme de liste dans `isogeo/user/unreachable_filepath`
    - [x] ajout d'un chemin de fichier inaccessible (attention à la gestion des "\\")
    - [x] récupération des chemins inaccessibles (attention à la gestion des "\\")
    - [x] vider le cache des chemins inaccessibles
  - [x] à gérer en cas de mise à jour (à déterminer : côté  **`SettingsManager`** ou  **`CacheManager`**)
    - [x] migration vers les *`QSettings`* des infos stockées dans le fichier `cache.json`
    - [x] suppression du fichier `cache.json`
  - [x] à voir si actuellement le fichier `cache.json` est vraiment utile pour les services (`cached_unreach_service`) et les bases PostGIS (`cached_unreach_postgis`) inaccessibles, selon il faudra nettoyer le **`CacheManager`** ou faire le passage du cache uniquement dans les *`QSettings`*
- [x] Rationaliser la sollicitation du **`SettingsManager`** en voyant si une même instance ne peut pas être transmise d'un module à l'autre dans certains cas
- [x] Faire des tests de mise à jour depuis un ZIP
- [x] Supprimer du dépôt les fichiers JSON

## Tests

Pour tester correctement il va falloir publier le plugin QGIS dans le dépôt des extensions QGIS sous forme de version expérimentale.

Voici les différentes cas d'installation à tester : 
1. ✔️ première installation du plugin en version 3.5.0, en installant un ZIP non-personnalisé via le gestionnaire des extensions
2. ✔️ première installation du plugin en version 3.5.0, en installant un ZIP personnalisé via le gestionnaire des extensions
3. mise à jour du plugin personnalisé en version 3.4.0, en téléchargeant la version 3.5.0 via le gestionnaire des extensions
4. ✔️ mise à jour du plugin personnalisé en version 3.4.0, en installant un ZIP non-personnalisé de la 3.5.0 via le gestionnaire des extensions
5. ✔️ mise à jour du plugin personnalisé en version 3.4.0, en installant un ZIP personnalisé de la 3.5.0 via le gestionnaire des extensions
6. ✔️ mise à jour du plugin personnalisé en version 3.5.0, en installant un ZIP non-personnalisé de la 3.5.0 via le gestionnaire des extensions

* "ZIP non-personnalisé" : tel qu'on peut le trouver sur le SharePoint

* "ZIP personnalisé" : 
  * avec des recherches rapides enregistrées dans `_user/quicksearches.json`
  * avec un URL de portail renseignée dans `config.json` (`portal_base_url`)
  * avec une option (0 ou 1) d'ajout de l'URL du portail renseignée dans `config.json` (`add_metadata_url_portal`)
  * avec des connections de BDD enregistrées dans `_user/db_connections.json`

* "plugin personnalisé" : 
  * avec des recherches rapides, si cas 4 ou 6 : 
    * certaines avec des noms ne figurant pas dans le `quicksearches.json` du ZIP personnalisé --> elles doivent être conservées
    * certaines avec des noms figurant dans dans le `quicksearches.json` du ZIP personnalisé mais des critères de recherche différents --> le ZIP personnalisé prévaut donc écrasement des recherches rapides initiale au profit de celles issues du ZIP personnalisé
  * avec une URL de portail configurée, si cas 4 ou 6 : 
    * URL du portail différente de celle figurant dans le `config.json` du ZIP personnalisé (`portal_base_url`) --> le ZIP personnalisé prévaut donc la valeur initiale est remplacée par celle figurant dans le `config.json` du ZIP personnalisé
    * valeur de la case "Ajouter l'URL..." différente de celle figurant dans le `config.json` du ZIP personnalisé (`add_metadata_url_portal`) --> le ZIP personnalisé prévaut donc la valeur initiale est remplacée par celle figurant dans le `config.json` du ZIP personnalisé
  * avec des connexions de BDD configurées dans QGIS :
    * certaines ignorées
    * certaines privilégiées
  * des chemins de fichiers inaccessibles enregistrés dans le cache

## Ressources

[dépôt isogeo2office](https://github.com/isogeo/isogeo-2-office)

**Comment by SimonSAMPERE** [comment]
# Point avec Catherine, Gaël et Stéphanie du CD94 concernant le déploiement massif du plugin QGIS via un zip

Au CD 94 ils prépare une version LTR de QGIS qui est configurée et customisée sur un poste "admin", à laquelle ils ajoutent des plugins dont le plugin Isogeo. Ensuite cette version est "chargée" dans un "centre logiciel" à partir duquel elle sera déployée sur les postes des utilisateurs sans nécessiter d'action de leur part. Les plugins sont donc encapsulés dans cette version déployée.

L'objectif c'est de faire en sorte qu'un maximum de configurations communes à tous les utilisateurs puisse être effectué une seule fois. Ce qu'on cherche c'est que les configurations du plugin Isogeo effectuées sur le poste "admin" avant le chargement dans le centre logiciel se répercutent sur les postes utilisateur après le déploiement.

Je pense notamment à l'authentification pour laquelle Stéphanie m'a dit que ça n'était pas le cas alors qu'elle dépose le fichier dans le dossier `_auth` du répertoire du plugin. Je lui ai dit qu'il faudrait essayer de le charger via le plugin mais il faut quand même que je vérifie que ça fonctionne.

Globalement, tout ça confirme la nécessité de se poser la question de où on enregistre les paramètres. J'ai toujours tendance à vouloir les enregistrer dans des fichiers + dans les paramètres de QGIS. Mais se pose la question des conflits, pour chaque paramètre il va falloir décider, si sa valeur dans le fichier est différente de celle des paramètres, quelle valeur conserver.

Le plugin sera prochaine déployé pour plusieurs dizaines d'utilisateurs.

Stéphanie m'a dit, après que je lui ais demandé, qu'on pourrait effectuer des tests de déploiement, une fois que j'aurai une version suffisamment mature du plugin à leur faire tester. Puisque je ne maîtrise pas les modalités technique de leur processus de déploiement, l'idée serait de constater dans leur environnement 2 types de comportement : 
* la répercutions sur les postes utilisateurs d'une configuration effectuée sur le poste admin
* l'écrasement ou non des configurations effectuées sur un poste utilisateur suite à un nouveau déploiement

**Comment by Erzalt** [comment]
Ma version actuelle de QGIS est la `3.32.3`. Est-ce qu'il y a un besoin d'une version particulière pour la recette ?

**Comment by SimonSAMPERE** [comment]
@Erzalt effectivement j'aurais dû le préciser, il faudrait que tu installes la version 3.34.5 (la dernière version LTR)

**Comment by SimonSAMPERE** [comment]
| Version initiale | Version initiale customisée | Version installée | Via un ZIP | Via un ZIP customisé | Via téléchargement |
| ---------------- | --------------------------- | ----------------- | ---------- | -------------------- | ------------------ |
| Aucune           | 0                           | 3.5.0             | 1          | 0                    | 0                  |
| Aucune           | 0                           | 3.5.0             | 0          | 1                    | 0                  |
| Aucune           | 0                           | 3.5.0             | 0          | 0                    | 1                  |
| 3.4.0            | 0                           | 3.5.0             | 1          | 0                    | 0                  |
| 3.4.0            | 0                           | 3.5.0             | 0          | 1                    | 0                  |
| 3.4.0            | 0                           | 3.5.0             | 0          | 0                    | 1                  |
| 3.4.0            | 1                           | 3.5.0             | 1          | 0                    | 0                  |
| 3.4.0            | 1                           | 3.5.0             | 0          | 1                    | 0                  |
| 3.4.0            | 1                           | 3.5.0             | 0          | 0                    | 1                  |

**Comment by Erzalt** [comment]
Gdoc sur les fichiers de configuration à créer pour chaque test : https://docs.google.com/spreadsheets/d/1ulO3ZB4ojbRXu1J-QfDzi0c_v2gzD-fZmytGbvyV7D4/edit#gid=405601901

**Comment by SimonSAMPERE** [comment]
[qsettings_keys_values.json](https://github.com/user-attachments/files/15786573/qsettings_keys_values.json)

checker [les scripts à exécuter dans QGIS](https://github.com/isogeo/isogeo-plugin-qgis/tree/master/tests/dev/qgis_console), notamment : 
* [qsettings_config_check.py](https://github.com/isogeo/isogeo-plugin-qgis/blob/master/tests/dev/qgis_console/qsettings_config_check.py)
* [qsettings_quicksearch_display.py](https://github.com/isogeo/isogeo-plugin-qgis/blob/master/tests/dev/qgis_console/qsettings_quicksearch_display.py)

```python
# -*- coding: utf-8 -*-

from qgis.PyQt.QtCore import QSettings
import json
from pprint import pprint
from pathlib import Path

qsettings = QSettings()

matching = {
    r"C:\Users\SimonSAMPERE\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\isogeo-plugin-qgis\config.json": {
        "api_base_url": "isogeo/env/api_base_url",
        "api_auth_url": "isogeo/env/api_auth_url",
        "app_base_url": "isogeo/env/app_base_url",
        "help_base_url": "isogeo/env/help_base_url",
        "background_map_url": "isogeo/settings/background_map_url",
        "portal_base_url": "isogeo/settings/portal_base_url",
        "add_metadata_url_portal": "isogeo/settings/add_metadata_url_portal",
    },
    r"C:\Users\SimonSAMPERE\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\isogeo-plugin-qgis\_auth\client_secrets.json": {
        "client_id": "isogeo/auth/app_id",
        "client_secret": "isogeo/auth/app_secret",
    },
    r"C:\Users\SimonSAMPERE\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\isogeo-plugin-qgis\_user\quicksearches.json": "isogeo/user/quicksearches/"
}

for config_file_path in matching:
    if Path(config_file_path).stem == "quicksearches":
        keys = matching[config_file_path]
        with open(Path(config_file_path), "r") as json_file:
            config_json_content = json.load(json_file)
    elif Path(config_file_path).stem == "config":
        keys = matching[config_file_path]
        with open(Path(config_file_path), "r") as json_file:
            config_json_content = json.load(json_file)
        for key in keys:
            qsettings_key = keys[key]
            json_value = config_json_content.get(key)
            qsetting_value = qsettings.value(qsettings_key)
            if qsetting_value == json_value:
                print("☻ {} : '{}'".format(qsettings_key, json_value))
            else:
                print("Ø {} : '{}' vs '{}'".format(qsettings_key, json_value, qsetting_value))
    else:
        keys = matching[config_file_path]
        with open(Path(config_file_path), "r") as json_file:
            config_json_content = json.load(json_file)
        for key in keys:
            qsettings_key = keys[key]
            json_value = config_json_content.get("web").get(key)
            qsetting_value = qsettings.value(qsettings_key)
            if qsetting_value == json_value:
                print("☻ {} : '{}'".format(qsettings_key, json_value))
            else:
                print("Ø {} : '{}' vs '{}'".format(qsettings_key, json_value, qsetting_value))
```

**Comment by Erzalt** [comment]
## Recette
Se référer à ces [tableaux](https://docs.google.com/spreadsheets/d/1ulO3ZB4ojbRXu1J-QfDzi0c_v2gzD-fZmytGbvyV7D4/edit#gid=405601901).

Les informations sur les résultats des scripts se trouvent dans les [dossiers associés](https://drive.google.com/drive/folders/15YbFSsA65C0i47IXRnVR_OKvHy8iuQE4?usp=sharing). 
Dans `qsettings_keys_values` se trouvent les valeurs attendues, dans `result_conformity` le résultat du script `check_conformity.py` (comparaison entre les qsettings et les `qsettings_keys_values`). Dans `result_equal` le résultat du script `check_conformity.py`  (correspondance entre les qsettings et les fichiers).

### Cas correspondants aux attendus
Les cas **1**, **3**, **4** et **6** sont ok ✔️

### Cas ne correspondants pas aux attendus

Pour les cas **2** et **5**, je remarque que les urls des quicksearches ne sont pas récupérés tel quels. Ils sont regénérés en fonction de l'url entré dans api_base_url. (c'est un comportement qui me semble logique, mais il n'est pas spécifié donc je le remonte)

Pour le cas **7**, les quicksearches ne sont pas récupérées. 
Protocole suivi : 
* Suppression du dossier du plugin ;
* Suppression des qsettings ;
* Téléchargement de la version [3.4.0](https://plugins.qgis.org/plugins/isogeo_search_engine/version/3.4.0/) ;
* Ajout des fichiers quickseraches.json, client_secret.json et config.json au endroits prévus, et zip du [dossier](https://drive.google.com/file/d/1bReEx0Ms7fnXubUmC9mtKhM3cm1kONvk/view?usp=drive_link) ;
* Téléchargement par zip du plugin personnalisé créé ; 
* Vérification de la présence des informations : 
![version 3 4 0](https://github.com/isogeo/isogeo-plugin-qgis/assets/82826196/c17c8c7d-b30b-4e11-b4bf-e032669e960f)
* Téléchargement de la version [3.5.0](https://plugins.qgis.org/plugins/isogeo_search_engine/version/3.5.0-beta2/) ;
* Téléchargement par zip du plugin 3.5.0 ;
* Lancements des scripts, récupération des résultats, [qsettings ==fichiers](https://drive.google.com/file/d/1aMn2IRYH2PIoHRNrhpmP5NsnXfekv8HQ/view?usp=drive_link), [qsettings ==attentes](https://drive.google.com/file/d/1Lp2U7ChzwotnZvOKtd_wTHIIxMVbstJy/view?usp=drive_link)
* Les quicksearches ne sont pas fusionnées, la rechercher "education" n'est pas récupérée : 
![version 3 5 0](https://github.com/isogeo/isogeo-plugin-qgis/assets/82826196/20692874-89a6-4187-90e2-eb8d4dca549f)

**Comment by SimonSAMPERE** [comment]
@Erzalt , merci pour ce magnifique et réjouissant premier retour de recette ✨ 

Comme tu l'avais pressenti pour les cas 2 et 5, le comportement est conforme à ce qui est attendu mais j'avais effectivement oublié de t'indiquer cette subtilité. Pour que les recherches rapides restent fonctionnel, le plugin remplace la base de l'URL de l'API s'il a changé.

Venons-en maintenant au 📼. Figure-toi que la encore le comportement est attendu mais que je l'avais mal décrit dans [ce commentaire](https://github.com/isogeo/isogeo-plugin-qgis/issues/258#issuecomment-2122656053). Puisque les recherches rapides sont initialement (3.4.0) uniquement stockées dans le fichier `quicksearches.json`, elles sont irrémédiablement perdues lorsqu'on installe la version 3.5.0 du plugin. Lors de la mise à jour, tout le répertoire est écrasé donc le fichier `quicksearches.json` est supprimé et la version 3.5.0 n'a aucun moyen de récupérer les recherches rapides qui ne figuraient même pas dans les QSettings. C'est justement pour ça qu'elles y figurent depuis la version 3.5.0, pour avoir une persistance avec les futurs versions. Ce comportement sera donc valable également pour les cas 8 et 9. Voilà, j'espère que c'est à peu près claire. 

Du coup tu peux poursuivre la recette puisque tous les comportements sont conformes (c'est juste moi qui les avais mal décrit, sorry).

**Comment by Erzalt** [comment]
Résumé état actuel de la recette : 
- [ ] 1✔️
- [ ] 2✔️
- [ ] 3✔️
- [ ] 4✔️
- [ ] 5✔️
- [ ] 6✔️
- [ ] 7✔️
- [ ] 7.2✔️
- [ ] 8✔️
- [ ] 8.2✔️
- [ ] 8.3✔️
- [ ] 8.4
- [ ] 8.5
- [ ] 9
- [ ] 9.2
- [ ] 10
- [ ] 10.2
- [ ] 11
- [ ] 11.2
- [ ] 11.3
- [ ] 11.4
- [ ] 11.5
- [ ] 12
- [ ] 12.2

**Comment by Erzalt** [comment]
### Cas 10.2
Version de base [3.5.0 personnalisées](https://drive.google.com/file/d/1vmBlfBY_DRK35aXXDkz9mxf7eqTnrKpA/view?usp=drive_link), mise à jour via zip vers une [version 3.5.0 ](https://plugins.qgis.org/plugins/isogeo_search_engine/version/3.5.0-beta2/).

Les urls de la version personalisées sont les suivants : 
![3 5 0 base](https://github.com/isogeo/isogeo-plugin-qgis/assets/82826196/b1e32d0b-021f-4ce5-8efb-82666e27c9c2)

Malgré cela les urls présents après la mise à jour sont les urls de base, alors que selon les spef : 
si la valeur est différente entre le fichier `config.json` et les `QSettings` et que la valeur présente dans le fichier `config.json` est différente de `https://id.api.isogeo.com/`, alors la valeur du fichier `config.json` écrasent celle des `QSettings`, sinon la valeur des `QSettings `écrasent celle du fichier `config.json`.

**Comment by Erzalt** [comment]
Bravo ! Pas de bugs à déclarer ! 🎉

**Comment by SimonSAMPERE** [comment]
Merci beaucoup @Erzalt et bravo pour cette recette menée d'une main de maître 🦾

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
