### ISSUE TITLE
Erreur python à l'authentification - plugin v2.0.0-beta2 QGIS 3.4.5-Madeira (Windows-7-6.1.7601-SP1)

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#259]
###  Contexte

Beta-testing chez Lorient Agglo @siglagglo.
Proxy configuré sur QGIS mais pas dans Windows.

### Reproduire le bug :

1. Lancer le plugin sur QGIS 3 pour la première fois --> La fenêtre d'authentification s'affiche
2. Indiquer l'emplacement du fichier d'authentification 
3. Cliquer sur "Enregistrer" --> le formulaire d'authentification se ferme
4. Ouvrir le formulaire d'authentification
5. Cliquer sur "Vérifier" --> l'erreur Python suivante est déclarée. Le formulaire d'authentification est toujours accessible ainsi que l'onglet "Paramètres" mais l'onglet "Recherche" est grisé

### erreur python :
```python
2019-09-24T11:06:02     WARNING    Traceback (most recent call last):
              File "C:/Users/sduceux/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\api\request.py", line 293, in handle_reply
              self.iface.mainWindow(),
             AttributeError: 'ApiRequester' object has no attribute 'iface'
```
### fichier `.log` : 
[log_isogeo_plugin.log](https://github.com/isogeo/isogeo-plugin-qgis/files/3646567/log_isogeo_plugin.log)

**signalement d'une erreur 302** pouvant provenir du proxy ou directement de l'API Isogeo via le protocole oAuth2

**Comment by Guts** [comment]
Il y a 2 problèmes :

- [ ] le proxy du client renvoie [un code 302](https://fr.wikipedia.org/wiki/Erreur_HTTP_302) qui n'est pas géré dans le plugin
- [ ] un bug dans l'affichage de l'erreur - c'est ce bug qui fait planter le plugin : https://github.com/isogeo/isogeo-plugin-qgis/blob/master/modules/api/request.py#L290-L299

**Comment by Guts** [comment]
A vérifier, il y a une incohérence à vérifier : le contexte contient une configuration derrière un proxy mais le log indique :

`2019-09-24 11:05:22,843 || INFO || tools - 299 || test_proxy_configuration || No proxy found on the OS: OK.`

Etudier la fonction test_proxy_configuration : https://github.com/isogeo/isogeo-plugin-qgis/blob/master/modules/tools.py#L290-L399
