### ISSUE TITLE
Message d'erreur au lancement du plugin "Problème de proxy"

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#27]
Bonjour,

Ci-joint un dossier zippé avec le message d’erreur « msg1.png » qui s’affiche lorsque je lance le plugin, le fichier activity.log et une impression écran des paramètres proxy « parametreproxy.png » .

[activity.log.txt](https://github.com/isogeo/isogeo-plugin-qgis/files/386339/activity.log.txt)
![erreur1](https://cloud.githubusercontent.com/assets/1596222/17179534/dcadf4d0-5419-11e6-9e9d-e957b1c1da1e.png)
![parametreproxy](https://cloud.githubusercontent.com/assets/1596222/17179533/dcabf6da-5419-11e6-8ba5-6e923fe7ea8b.png)

édité par @Guts pour mettre les PJ directement sans zip

**Comment by TheoSinatti** [comment]
La fonction testant la configuration du proxy se contente (au moins pour l'instant) d'envoyer ce message dans le cas où elle détecte une situation anormale. 
Le fonctionnement du plugin a partir du moment où ce message a été affiché ne devrait pas être affecté ; est-ce bien le cas ? Le plugin fonctionne-t-il convenablement après avoir affiché cette erreur ? 

Ensuite, ayant configuré le proxy dans QGIS, il est vrai que cette fenêtre ne devrait logiquement pas s'afficher. Avez-vous relancé QGIS depuis que vous avez renseigné les paramètres du proxy ?

**Comment by smavd** [comment]
Le message n'impacte pas le fonctionnement du plugin. Le plugin fonctionne convenablement.
J'ai relancé QGIS plusieurs fois mais il n'y a rien à faire le message apparait toujours au lancement du plugin.
J'ai désinstaller et réinstaller le plugin, j'ai toujours le même message avec un autre message d'erreur, ci-joint « erreur.png ».
Néanmoins, le plugin fonctionne.
Laurent TORT
Technicien
SMAVD

De : TheoSinatti [mailto:notifications@github.com]
Envoyé : mercredi 27 juillet 2016 16:57
À : isogeo/isogeo-plugin-qgis
Cc : Laurent TORT; Author
Objet : Re: [isogeo/isogeo-plugin-qgis] Message d'erreur au lancement du plugin "Problème de proxy" (#27)


La fonction testant la configuration du proxy se contente (au moins pour l'instant) d'envoyer ce message dans le cas où elle détecte une situation anormale.
Le fonctionnement du plugin a partir du moment où ce message a été affiché ne devrait pas être affecté ; est-ce bien le cas ? Le plugin fonctionne-t-il convenablement après avoir affiché cette erreur ?

Ensuite, ayant configuré le proxy dans QGIS, il est vrai que cette fenêtre ne devrait logiquement pas s'afficher. Avez-vous relancé QGIS depuis que vous avez renseigné les paramètres du proxy ?

-

**Comment by TheoSinatti** [comment]
Il y avait bien un problème dans le code, je l'ai corrigé.
Ne disposant pas d'un proxy pour vérifier, je laisse le ticket ouvert jusqu'à ce qu'on confirme que le problème est bien réglé. La correction sera accessible dans la prochaine release du plugin. Ou dès à présent si vous téléchargez directement le dossier du plugin (Voici le "mode d'emploi" si le coeur vous en dit : https://github.com/isogeo/isogeo-plugin-qgis/blob/master/doc/install_FR.md)

PS : Il me semble que vous n'avez pas joint correctement l'image de la nouvelle erreur !

**Comment by Guts** [comment]
Le plugin a été mis à jour. @smavd : pouvez-vous retester et nous dire ce qu'il en est svp ?
