### ISSUE TITLE
corriger le fichier quicksearches.json

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#273]
Les paramètres par défaut de la recherche par défaut ne sont pas stockés correctement dans le fichier `quicksearches.json`.

remplacer `"datatype": "type:dataset"` par `"types": "type:dataset"` **dans le fichier `plugin_packager.py`** (ligne197)

**Comment by SimonSAMPERE** [comment]
à faire dans la branche [releasing](https://github.com/isogeo/isogeo-plugin-qgis/tree/releasing) avant la publication de la version 2.0.0 stable

**Comment by Guts** [comment]
C'est un bug ou une tâche ? quel est l'impact sur le fonctionnel ? N'y a t'il pas une bonne raison pour laquelle on a écrit `datatype` plutôt que `types` ?

**Comment by SimonSAMPERE** [comment]
La chaîne de caractère `datatype` était utilisée pour une raison non-documentée dans la version 1 du plugin comme clef du dictionnaire de stockage des paramètres choisis par l'utilisateur (voir [ici](https://github.com/isogeo/isogeo-plugin-qgis/blob/59b02a4d3e6e9866b859d9e389025e1e3b5548a4/isogeo.py#L908-L985)).

Durant le refactoring, `types`a remplacé `datatype` (voir [ici](https://github.com/isogeo/isogeo-plugin-qgis/blob/2031cc832283a53854760a809d5579808621ef91/modules/search_form.py#L396-L457)) afin de correspondre avec le lexique de l'API Isogeo. Cela permet d'économiser des lignes de code en bouclant sur les widgets de filtre lors de leur actualisation.

Si le fichier `plugin_packager.py` n'est pas actualisé, le filtre sur le type de données ne sera jamais enregistré dans les recherches rapides ou la recherche par défaut.

**Comment by Guts** [comment]
> Cela permet d'économiser des lignes de code en bouclant sur les widgets de filtre lors de leur actualisation.

? Le mot `types` n'est pas un mot de l'API... Je pensais  surtout que le mot `types` n'est pas vraiment recommandé dans un fichier JSON...

**Comment by SimonSAMPERE** [comment]
Dans ce cas il faut actualiser les scripts en charge de l'interaction avec l'API et de l'actualisation des widgets en remplaçant `types`par `datatype`
