### ISSUE TITLE
Changer le fond de carte de la rubrique "Geographie" des fiches de métadonnées

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#274]
- [x] Trouver un nouveau service WMS libre d'accès --> le même fond de carte utilisé dans app
- [x] Faire en sorte qu'il n'apparaisse pas dans la liste déroulante du champ géographique
- [x] Gérer les enveloppes constituées d'un seul point

**Comment by leodarengosse** [comment]
C'est parfait ! même avec une emprise ponctuelle, bravo
