### ISSUE TITLE
Sauvegarder les paramètres de recherche par défaut

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#3]
Dans le fichier config.ini ou via les classes QSettings (qui semble mieux intégré donc) : http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/settings.html
Pouvoir choisir la première les paramètres de la première requête qui s'exécute au lancement du plugin.

**Comment by mcartoixa** [comment]
I don't understand french. Can you translate, please?

**Comment by Guts** [comment]
@mcartoixa  http://translate.google.fr/

**Comment by TheoSinatti** [comment]
This is planned to be done, but doesn't appear to be a priority right now.
So this will be dealt with later.

**Comment by TheoSinatti** [comment]
0b332a1
