### ISSUE TITLE
Add WMS to map canvas fail when a special character is in the title or the description

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#30]
In some cases, WMS maps are not rendered by QGIS. 
The problem seems to be when the title of the service contains a UTF8 character, like "é". 
It doesn't matter if the script gives another title for the layer, for the problem must come from QGIS built-in method, that fails when parsing the XML documentation. 

![wms_error](https://cloud.githubusercontent.com/assets/20419317/17480290/7877f5b2-5d77-11e6-9993-39d9d350e32b.png)

Raw stack trace:

> 2016-09-16T10:52:05	1	Erreur de requête de carte (Statut : 200; Réponse : <?xml version='1.0' encoding="ISO-8859-1" standalone="no" ?>
> 			<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
> 			<ServiceExceptionReport version="1.1.1">
> 			<ServiceException code="InvalidSRS">
> 			msWMSLoadGetMapParams(): WMS server error. Unsupported SRS namespace (only EPSG and AUTO currently supported).
> 			</ServiceException>
> 			</ServiceExceptionReport>
> 			; Type : application/vnd.ogc.se_xml; charset=ISO-8859-1; URL : http://ws.carmencarto.fr/WMS/105/ONF_Forets?language=fre&&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=-5.58549999999999969,40.92079999999999984,10.75499999999999901,51.44619999999999749&SRS=CRS:84&WIDTH=116&HEIGHT=75&LAYERS=Forets_Publiques&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96)
> 2016-09-16T11:02:35	1	Erreur de requête de carte (Statut : 200; Réponse : <?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://noisy.hq.isogeo.fr:6090/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException code="internalError">
> 			      Rendering process failed
> 			The specified mark slash was not found!
> 			</ServiceException></ServiceExceptionReport>; Type : text/xml; charset=utf-8; URL : http://noisy.hq.isogeo.fr:6090/geoserver/Isogeo/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-61.808647396887757,-30.06558436831620185,55.83904539954382784,51.18236058068361416&CRS=CRS:84&WIDTH=830&HEIGHT=573&LAYERS=Isogeo:DEPARTEMENT_2014&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96)
> 2016-09-16T11:02:40	1	Erreur de requête de carte (Statut : 200; Réponse : <?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://noisy.hq.isogeo.fr:6090/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException code="internalError">
> 			      Rendering process failed
> 			The specified mark slash was not found!
> 			</ServiceException></ServiceExceptionReport>; Type : text/xml; charset=utf-8; URL : http://noisy.hq.isogeo.fr:6090/geoserver/Isogeo/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-61.808647396887757,-30.06558436831620185,55.83904539954382784,51.18236058068361416&CRS=CRS:84&WIDTH=186&HEIGHT=128&LAYERS=Isogeo:DEPARTEMENT_2014&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96)

**Comment by Guts** [comment]
Diagnosis in progress: the important part of the stack trace is that `The specified mark slash was not found!`. That means there is a problem with the default style set in the geospatial server.
