### ISSUE TITLE
avertissement fonctionne avec restriction de sécurité seulement

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#308]
Bonjour Simon,

OK pour les restrictions de type sécurité. Par contre pour les restrictions de type "propriété intellectuelle", je n'ai pas de msgbox dans Qgis.
Test effectué avec la ressource : 229820ed826c466a968667a4ecb9c6ea

[log_isogeo_plugin.log](https://github.com/isogeo/isogeo-plugin-qgis/files/4179319/log_isogeo_plugin.log)

**Comment by SimonSAMPERE** [comment]
Bonjour,

Merci d'avoir pris le temps de le signaler et de joindre le log.
Je vais regarder ça et reviendrai vers vous prochainement.
