### ISSUE TITLE
Ajouter automatiquement le lien vers la fiche de métadonnée du Portail Isogeo

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/isogeo-plugin-qgis#312]
Créer dans l'onglet Paramètres un champs ou on renseigne l'URL du Portail (exemple : https://demo.isogeo.net/les-donnees-isogeo/)

Ajouter aux métadonnées QGIS Server dans le champs **url** : le lien vers la fiche sur le portail concernée https://demo.isogeo.net/les-donnees-isogeo/ + id_md_Isogeo

![image](https://user-images.githubusercontent.com/16936198/79214205-b5bd8e80-7e4a-11ea-9749-1f9d01e1f244.png)

**Vérification à faire au niveau du Partage** 

Mettre en prérequis --> Si la fiche est partagée au Plugin mais pas partagée au Portail alors  le lien vers le portail sera généré mais ne pointera vers aucune fiche.

**Comment by SimonSAMPERE** [comment]
Mise à jour de la demande du client : 
>Dans l'onglet Paramètres, le champ de saisie de l'URL est non seulement visible, mais également modifiable par un clic "malheureux". Il me paraitrait plus judicieux de mettre un bouton "URL" qui ouvrirait une popup de saisie, ainsi l'URL serait "masquée" et protégée de tout clic ou coup de clavier inopportun.
