### ISSUE TITLE
Lenteur de l'affichage des résultats

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#316]
Le remplissage du tableau des résultat est lent. Rendre cette partie du code asynchrone pourrait améliorer ce comportement.

Une autre piste serait de déplacer la génération de l'URL de récupération des couches via les services géographiques. Cet URL est actuellement généré au moment du remplissage du tableau pendant l'inventaire des options d'ajout. Cette opération pourrait expliquer en partie la lenteur de l'affichage du tableau des résultats. Cela impliquerait de procéder au refactoring de l'opération d'ajout de couches (#318).

**Comment by VianneyDoleans** [comment]
Je viens de tomber sur ton issue, je me permets de te donner d'autres pistes de réflexion pouvant s'ajouter à celles que tu as déjà indiquées : 

- Une autre option complémentaire pour améliorer les performances des résultats est de les bufferiser : 
  - En background, tu effectues en asynchrone les recherches des pages suivantes pour ne pas avoir à les charger par la suite.
- Un cache
  - Toutes les recherches déjà effectuées sont sauvegardés pour ne pas avoir à les ré-effectuer auprès de l'API si elles sont redemandés (une base de donnée local sur la machine ou bien un fichier txt)
    - Il peut y avoir par exemple un temps de refresh tous les X temps pour vérifier que les recherches dans le cache sont toujours à jour/valide (pas de nouvelle métadata ajoutée ou supprimée), avec la possibilité pour l'utilisateur de demander la réactualisation du cache (un système dans ce genre)
- Si la construction du visuelle du tableau des résultats (l'ajout dans un tableau de chaque résultat ligne par ligne) est effectué en schynchrone, il peut être intéressant de le rendre aschynchrone pour que chaque résultat s'ajoute de lui même dans le tableau en parallèles, pouvant permettre des gains de performance selon la lourdeur du traitement original (cela peut se mesurer avec des outils).
- Dissocier (toujours en asynchrone) l'affichage du tableau des résultats de l'affichage des filtres, ainsi, même si le tableau n'a pas encore finalisé son traitement (animation de chargement en cours), il est possible de continuer de sélectionner les filtres, permettant de rendre l'expérience plus fluide. Le tableau des résultats devra en conséquence arrêter son chargement en cours, et recommencer avec la nouvelle réponse API provenant de le request effectuée par les filtres.
