### ISSUE TITLE
Problème d'ajout de couche PostGIS lorsqu'il y a plusieurs connexions enregistrées dans QGIS

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/isogeo-plugin-qgis#319]
**Constat**

Le CD 64 a constaté ce phénomène. En effet, ils ont une base de test (s929) qui contient les mêmes tables que la base de prod (s920). Les deux bases ont le même nom mais ne sont pas hébergées par le même hôte. . Cela pose problème lors de l'ajout d'une couche via une table PostGIS puisque plusieurs connexions à des bases portant le même nom et comportant des tables identiques sont enregistrées dans QGIS.

De plus, le plugin ne prends pas en compte les connexions effectuées "via un service".

**Tests**

> Voici les différents tests réalisés :
> 
> - si la seule connexion déclarée (nommée s920 DUR) à PGSQL est une connexion "en dur", avec stockage des logins/pwd dans Qgis, les couches chargées sont bien issues du serveur déclaré dans celle-ci, en l'occurrence le s920.
> 
> - si la seule connexion déclarée (nommée s929 DUR) à PGSQL est une connexion "en dur", avec stockage des logins/pwd dans Qgis, les couches chargées sont bien issues du serveur déclaré dans celle-ci, en l'occurrence le s929.
> 
> - si la seule connexion déclarée à PGSQL est faite via un service (et c'est ce que nous utilisons pour des raisons de sécurité notamment), les couches sont bien affichées dans le plugin, mais ne peuvent être chargées dans Qgis (cf capture de Romain).
> 
> - si je déclare d'abord une connexion en dur au serveur de production s920 (nommée s920 DUR), puis une connexion en dur au serveur de test s929 (nommée s929 DUR), les couches remontées par le plugin sont celles du 929. Si j'ajoute une connexion en dur au s920 (nommée A920), c'est toujours les couches du s929 qui sont remontées par le plugin.
> 

Le plugin ne semble pas répondre à une logique de dernière connexion déclarée ni à l'ordre alphabétique du nom de la connexion.

**Solution**

Il faudrait donc pouvoir déclarer dans le plugin quelle connexion (en dur ou via un service) utiliser pour le chargement des couches.

**Comment by leodarengosse** [comment]
Un peu de doc sur les fichiers de connexion de service 

- https://docs.qgis.org/3.10/fr/docs/user_manual/managing_data_source/opening_data.html#postgresql-service-connection-file
- https://www.postgresql.org/docs/9.1/libpq-envars.html

**Comment by SimonSAMPERE** [comment]
Le troisième test (connexion via un service) ne semble pas respecter les [conditions indiquées dans l'aide en ligne](http://help.isogeo.com/qgis/fr/usage/display.html#add_postgis).

**Comment by SimonSAMPERE** [comment]
Ce constat mène donc à deux potentiels amélioration : 
* [gestion de plusieurs connexions à des bases dont le nom est identique](https://github.com/isogeo/isogeo-plugin-qgis/issues/320)
* gestion des connexions via un fichier de configuration

**Comment by SimonSAMPERE** [comment]
Je clôt ce ticket dont le sujet a été développé dans #320 et #321
