### ISSUE TITLE
Gérer plusieurs connexions à des BDD PostGIS dont le nom est identique

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#320]
# Contexte

*Ce ticket fait suite à une [remarque](https://github.com/isogeo/isogeo-plugin-qgis/issues/319) remontée par le CD64.*

## Mise en situation fonctionnelle

Au moment de remplir le tableau des résultats, le plugin vérifie les différentes options d'ajout pour chaque fiche de métadonnées : 
1. Si la fiche correspond à une table PostGIS, il parcours les connexions à une BDD PostGIS enregistrées dans QGIS.
2. Il teste si la valeur de la **variable "database"** d'une des connexions est égale à celle de l'**attribut "path"** de la fiche.
3. Auquel cas, il parcourt les tables accessibles via la connexion correspondante.
4. Il teste si le schéma d'une des tables correspond à la valeur de l'attribut "name" de la fiche de métadonnée Isogeo.
5. Auquel cas, il considère que la couche pourra être ajoutée via le plugin en utilisant la connexion sélectionnée sur le critère du **nom** de la BDD PostGIS.

Le **nom** de la BDD PostGIS correspond : 
* dans Isogeo : à l'**attribut "path"** de la fiche de métadonnées
![image](https://user-images.githubusercontent.com/41120579/103669531-bf5ac980-4f78-11eb-83d4-3c7e98d78209.png)
* dans QGIS :
  * au champ "Base de données" du formulaire d'édition des connexions aux BDD PostGIS 
  ![image](https://user-images.githubusercontent.com/41120579/103669303-76a31080-4f78-11eb-9ee1-bfb9c70afab7.png)
  * à la **variable "database"** dans les QSettings (PostgreSQL>connections>*Nom donné à la connexion*>database)
  ![image](https://user-images.githubusercontent.com/41120579/103669488-af42ea00-4f78-11eb-9ff7-9c82951d54a1.png)

## Problème

Lorsque plusieurs connexions à des BDD PostGIS qui ont le même **nom** sont enregistrées dans QGIS, le plugin QGIS n'est pas en mesure de choisir celle qui doit être utilisée au moment d'ajouter une couche PostGIS au canevas.

Actuellement, il choisit une des connexions (en fonction de l'ordre dans lequel il les parcours) dont le **nom** de la base correspond. Par conséquent, il arrive qu'il ne s'agisse pas de la bonne connexion et que le plugin cherche une table dans la mauvaise base de données.

Dans ce cas, 2 comportement indésirables peuvent survenir : 
* l'option d'ajout via PostGIS n'est pas proposée à l'utilisateur car le schéma d'aucune des tables accessibles via la connexion choisie ne correspond à la valeur de l'attribut "name" de la fiche de métadonnées
* l'option d'ajout via PostGIS est proposée à l'utilisateur mais elle permet d'ajouter une couche qui ne correspond pas à la fiche car provenant de la mauvaise  base de données

# Solutions possibles

## Sélection de la connexion sur le critère du "nom" et de l'hôte de la BDD PostGIS

**Cette solution consisterait à sélectionner la connexion en se basant sur le **nom** de la BDD PostGIS mais aussi sur son hôte de manière à s'assurer que le plugin cherche une table dans la bonne base de données.**

Actuellement, la valeur de l'hôte est renseignée dans les point d'entrée du scan mais n'est pas remontée dans les champs des fiches de métadonnées. Il faudrait donc [modifier les workbenchs de lookup pour récupérer la valeur de l'hôte dans l'attribut "path"](https://github.com/isogeo/scan-scripts-fme/issues/40) (en plus du nom de la base). L'hôte pourrait ainsi être récupéré dans la métadonnées par le plugin QGIS.

Ainsi, au moment ou le plugin parcours les connexions enregistrées à la recherche de celle qui est susceptible de donner accès à la table, il choisira la connexion sur le double critère du **nom** de la BDD PostGIS et de l'hôte. De cette manière, on s'assure que le plugin utilise la bonne connexion et cherche la table dans la bonne BDD PostGIS.

## Paramétrage par l'utilisateur de la connexion à utiliser

**Cette solution consiste à permettre à l'utilisateur de choisir, parmi les connexions à des BDD PostGIS dont le **nom** est identique, celle qui devra être utilisée pour établir les options d'ajout de la couche au canevas.**

De cette manière, le plugin utilisera directement la bonne connexion et ira cherche la table dans la bonne BDD PostGIS.

Une des manières de procéder serait de parcourir les connexions à des BDD PostGIS dès l'ouverture du plugin. Si plusieurs connexions à des BDD dont le **nom** est identique sont détectées, une fenêtre popup s'ouvre. Y figurerait (sous forme de tableau ou de liste déroulante) la liste des différentes connexions existantes pour chaque **nom** de BDD. L'utilisateur devrait alors choisir, pour chaque **nom** de BDD, la connexion qui sera utilisée par le plugin au moment d'établir les options d'ajout de la couche au canevas. Le nom des connexions choisies par l'utilisateur serait alors enregistrés dans les QSettings de manière à être utilisée par le plugin durant le remplissage du tableau des résultats. Un bouton serait ajouté à l'onglet "Paramètres" afin de permettre à l'utilisateur de modifier son paramétrage au cours d'une session d'utilisation du plugin.

## Opinion du développeur

~~**La première solution ("Sélection de la connexion sur le critère du "nom" et de l'hôte de la BDD PostGIS") est selon moi préférable pour les raisons suivante :**~~
~~* elle semble la plus simple à mettre en oeuvre (pas besoin de modifier l’interface graphique du plugin, de designer une nouvelle boîte de dialogue ou de stocker des informations supplémentaires dans les QSettings)~~
~~* la seconde solution prive l'utilisateur de la possibilité d'ajouter les couches issues de plusieurs connexions différentes à des BDD PostGIS dont le **nom** est identique~~
~~* son implémentation dans le code du plugin QGIS prendrait moins de temps~~
~~Le risque, avec la première solution tient aux effets de bord potentiels pour le scan d'une modification du workbench de lookup PostGIS. Il faudra donc bien recetter cette modification pour s'assurer qu'elle n'entraîne pas la création de doublons ou d'événements indésirables.~~

Finalement, la deuxième solution ("Paramétrage par l'utilisateur de la connexion à utiliser") sera adoptée car la première ne permer pas de gérer le cas de plusieurs connexions à des base de données dont **le nom et l'hôte** sont identiques. Il reste cependant à choisir entre deux possibilités fonctionnelles : 
* demander à l'utilisateur de choisir quelle connexion utiliser avant chaque ajout de table PostGIS
* permettre à l'utilisateur de choisir la connexion à utiliser pour chaque base de données en passant par une interface graphique dédiée accessible à partir de l'onglet "Paramètres"

En définitive, la solution choisit sera un mélange des deux possibilité fonctionnelles ci-dessus et reposera donc sur deux fonctionnalités:

1. Dans l'onglet "Paramètres", un bouton permettra d'ouvrir une fenêtre pop-up contenant un tableau. Ce tableau sera constitué d'une ligne par base de données à laquelle plusieurs connexions ont été configurées et de deux colonnes : 
  * dans la première, le nom de la base de données
  * dans la seconde, une liste déroulante remplie avec le nom des connexions configurées à la base de données dont le nom est inscrit dans la première colonne

  De cette manière, l'utilisateur pourra configurer, pour chaque base de données, la connexion qui sera utilisé par le plugin lorsqu'il aura à ajouter une table issue de cette base.

2. Dans le cas d'une base de données pour laquelle plusieurs connexions ont été configurées sans que l'une d'entre elles n'ai été choisie via la première fonctionnalité, l'utilisateur disposera d'une option d'ajout par connexion. De cette manière, il pourra choisir directement dans la liste déroulante des options d'ajout la connexion qui sera utilisées pour ajouter la table PostGIS.

**Comment by SimonSAMPERE** [comment]
Nouvelle solution envisager : dans la colonne des options d'ajouts, mettre des listes déroulantes contenant une options d'ajout par connexion disponible avec le label :  "Table postGIS - *nom de la connexion*"

**Comment by leodarengosse** [comment]
c'est parfait , par contre il manque la traduction :
![image](https://user-images.githubusercontent.com/16936198/112323703-53078080-8cb2-11eb-9a6f-b81f13173e5c.png)

**Comment by SimonSAMPERE** [comment]
Super, je rajoute la traduction prochainement.
