### ISSUE TITLE
Gérer les connexion à une BDD PostGIS via un fichier de configuration

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#321]
*Ce ticket fait suite à une [remarque](https://github.com/isogeo/isogeo-plugin-qgis/issues/319) remontée par le CD64.*

## Documentations : 

Documentations : 
* https://docs.qgis.org/3.10/fr/docs/user_manual/managing_data_source/opening_data.html#postgresql-service-connection-file
* https://www.postgresql.org/docs/9.1/libpq-envars.html
* https://www.postgresql.org/docs/9.1/libpq-pgservice.html

## Mise en contexte

Comme indiqué par le CD64 (#319) , il est possible de configurer une connexion à une base de données Postgis via un "Service". Pour se faire, il faut : 

1. Remplir un fichier de configuration (`pg_service.conf`) en y indiquant les informations nécessaires à une ou plusieurs connexion(s) :
```
[service de connexion A]
host=hote_de_la_database
port=5432
dbname=nom_de_la_db
user=nom_de_lutilisateur
password=mot_de_passe

[service de connexion B]
host=hote_de_la_database
port=5432
dbname=nom_de_la_db
user=nom_de_lutilisateur
password=mot_de_passe
```

2. Ajouter une variable d'environnement système dont le nom est "PGSERVICEFILE" et dont la valeur correspond à l'emplacement du fichier `pg_service.conf`

3. Ajouter cette même variable à l'environnement de QGIS : Menu "Préférence" > "Options" > onglet "Système" > rubrique "Environnement" > "Ajouter une nouvelle variable" ![image](https://user-images.githubusercontent.com/41120579/103889249-6610a880-50e6-11eb-9367-f8711bfe2d67.png) : 
  ![image](https://user-images.githubusercontent.com/41120579/103889340-8b9db200-50e6-11eb-894e-33aafa606e95.png)

4. Configurer une nouvelle connexion à une base de donnée PostGIS de la manière suivante : 
  ![image](https://user-images.githubusercontent.com/41120579/103889568-ecc58580-50e6-11eb-8970-b16d5364c063.png)

Ce système permet donc de configurer une connexion sans avoir à renseigner les informations sensibles que sont le mot de passe et le nom de l'utilisateur directement dans QGIS.

## Fonctionnement actuel du plugin

Pour pouvoir ajouter une couche au canevas à partir d'une table PostGIS, le plugin a besoin des informations de connexions à la base de données. Actuellement, cela implique que l'utilisateur ait enregistré une connexion à la base de donnée dans QGIS en remplissant le formulaire suivant en configurant l'enregistrement des nom d'utilisateur et mot de passe : 
![image](https://user-images.githubusercontent.com/41120579/103887144-e3d2b500-50e2-11eb-8af5-cd06ea0caa09.png)

Le plugin est en mesure de récupérer ces information via les QSettings (PostrgeSQL>connections>*Nom de la connexion*): 
![image](https://user-images.githubusercontent.com/41120579/103887348-314f2200-50e3-11eb-9115-b5d15b1c6cc2.png)

Ces informations sont utilisées pour : 
* savoir la table PostGIS correspondant à une fiche ajoutée au tableau des résultats est accessible (si l'utilisateur a configuré la connexion à la base de donnée dans laquelle elle est stockée)
* récupérer les données permettant d'ajouter une couche au canevas à partir d'une table PostGIS

Dès l'ouverture du plugin, la méthode *build_postgis_dict()* du module **ResultsManager** est exécutée pour récupérer dans les QSettings les informations de toutes les connexions enregistrées à une base de donnée PostGIS dont l'utilisateur a choisi de stocker les username et password.

## Fonctionnement attendu

Il faudrait permettre à l'utilisateur d'ajouter au canevas (en pasant par le plugin QGIS Isogeo) une couche issue d'une base de données PostGIS dont la connexion a été configurée via un "Service".

## Implémentation

Cette nouvelle fonctionnalité impliquera notamment : 

- [x] de modifier la méthode *build_postgis_dict()* du module **ResultsManager** de manière a ne plus récupérer uniquement les connexions pour lesquelles les username et password ont été stockés mais également celles pour lesquelles le champ "Service" du formulaire de création de la connexion a été rempli. Cela revient à récupérer les connexions respectant un des deux critères suivants : 
  - les variables "savePassword" **et** "saveUsername" sont égale à `true`
  - la variable "service" contient une valeur non null **et** la variable d'environnement "PGSERVICEFILE" existe **et** le plugin a accés au fichier qu'elle désigne 
- [x] d'ajouter une sous-méthode qui serait appelée par la méthode *build_postgis_dict()* et dont le rôle serait d'aller récupérer les informations nécessaires à la connexion directement dans le fichier `pg_service.conf`. Cela impliquera : 
  - [x] d'accéder à la valeur de la variable d'environnement "PGSERVICEFILE"
  - [x] d'ouvrir le fichier `pg_service.conf` en utilisant [cette librairie](https://docs.python.org/3/library/configparser.html)
  - [x] de récupérer les informations de connexion qu'il contient afin d'être en mesure de se connecter à la base de données
- [x] de créer un nouveau module **DatabaseManager** -équivalent du **GeoServiceManager** (#318) pour les bases de données- et d'y incorporer les deux modification sus-mentionnées

**Comment by leodarengosse** [comment]
ok pour moi
