### ISSUE TITLE
Marketing dans la fenêtre d'Authentification

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#325]
rubrique "Pas encore de compte ?" : donner les possibilités de (i)demander un accès gratuit (formulaire) et (ii) prendre RDV : 

"Il est simple et gratuit et tester le Plugin QGIS Isogeo sur un échantillon de données, n'hésitez pas à nous en faire la demande"
Puis mettre 2 boutons côte à côte avec :
* Pour le premier : "Tester gratuitement le Plugin QGIS Isogeo" (avec comme lien le [formulaire](https://webforms.pipedrive.com/f/5kAUlfXAdFfv85vV3Mw1PWOYqOBpD7l9GV9wr0OlOAdmQcdC7DduZ6afScQHHZ))
* Pour le second : "Prendre RDV avec la Team Isogeo" (avec comme lien le [formulaire de prise de RDV](https://isogeo.pipedrive.com/scheduler/lq0ZSm/rendez-vous-isogeo))

**Comment by mathieubecker** [comment]
Validé en version QGIS 3.4
