### ISSUE TITLE
Rendre insensible à la casse et aux accent le tri alphabétique des mots-clés

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/isogeo-plugin-qgis#373]
Actuellement, le tri des mots-clés affiche dans l'ordre

Les majuscules, puis les minuscules et enfin les accents. 

![image](https://user-images.githubusercontent.com/16936198/119126137-f1a22a80-ba32-11eb-9055-6490239f187c.png)
![image](https://user-images.githubusercontent.com/16936198/119126174-fcf55600-ba32-11eb-8180-13fe63275da3.png)
![image](https://user-images.githubusercontent.com/16936198/119126256-16969d80-ba33-11eb-8d53-436a51da1827.png)

**Comment by Mouzzi-C** [comment]
testé sur qgis 3;10 et 3.16
