### ISSUE TITLE
Secondary resources don't appear as available

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#38]
For example, this metadata has 2 webservices available (3 with the Esri one) but none is proposed within the plugin: http://open.isogeo.com/s/344d51c3edfb435daf9d98d948fa207e/Sbd1w7PgqE8n7LDq3azRqNhiMHZf0/m/754209f115c040a48d43ffc262b16500

They belong to the same share: https://app.isogeo.com/groups/08b3054757544463abd06f3ab51ee491/admin/shares/344d51c3edfb435daf9d98d948fa207e
![plugin_qgis_secondary_services](https://cloud.githubusercontent.com/assets/1596222/18136799/4881d1f2-6fa6-11e6-9de1-11969e587cf9.png)

**Comment by TheoSinatti** [comment]
In this metadata (like in many others) the links have not been identified
correctly when created.
The plugin only search for links whose kind is "wms" or "wfs". The "kind"
fields say "url" for both services instead of "wms" and "wfs" like they
should. There is a specific field in app that set the link kind, it hasn't
been filled correctly for this metadata. So the problem here comes from the
metadata, and not the plugin.

We could consider that the plugin has to do something about it, but it
seems rather tedious : the only other way would be parsing every single url
searching for keywords that would indicate the url kind (like "typename"
for wfs) which of course would cause tons of problems due to the syntax
being different from one url to another.


Théo Sinatti


*Développeur - Responsable du plugin QGIS*



*Tél : +33 (0)*
*6 62 63 39 96*




26 rue du Faubourg Saint-Antoine – 75012 Paris

Métro Bastille


Suivez nous sur : *Twitter <https://twitter.com/isogeo>* | *Le blog
<http://blog.isogeo.com/>*| *Le site officiel <http://www.isogeo.com/>*

2016-08-31 18:11 GMT+02:00 Julien <notifications@github.com>:

**Comment by Guts** [comment]
Lack of reading or misunderstanding [API documentation](https://docs.google.com/document/d/11dayY1FH1NETn6mn9Pt2y3n8ywVUD0DoKbCi9ct9ZRo/edit#heading=h.afao07rpoqln)? The secondary resource is always identified as a link (code _url_) in its first level. Then plugin should investigate the second level and check action.

Look at the [metadata links through the API](http://v1.api.isogeo.com/resources/search?ct=Sbd1w7PgqE8n7LDq3azRqNhiMHZf0&s=344d51c3edfb435daf9d98d948fa207e&_limit=10&_lang=fr&_id=754209f115c040a48d43ffc262b16500&_include=links) :

```json
"links": [

    {
        "_id": "95ac9822f7d44d6780a7e4c0a45fc760",
        "type": "hosted",
        "title": "Télécharger les données au format shapefile",
        "url": "/resources/754209f115c040a48d43ffc262b16500/links/95ac9822f7d44d6780a7e4c0a45fc760.bin",
        "kind": "data",
        "actions": [
            "download"
        ],
        "size": 3847983
    },
    {
        "_id": "40c29c8d564c467f9f0c00c5c6ba8ee9",
        "type": "url",
        "title": "Données des départements (ArcGIS Online)",
        "url": "https://services1.arcgis.com/ApmCsFVnpW3bVGYw/arcgis/rest/services/D%C3%A9partementsde_la_France_m%C3%A9tropolitaine_%282014%29/FeatureServer/0",
        "kind": "esriFeatureService",
        "actions": [
            "view"
        ]
    },
    {
        "_id": "0cfbbb300897463ea469072382fcd99f",
        "type": "url",
        "title": "GéoPortail",
        "url": "http://www.geoportail.gouv.fr/",
        "kind": "url",
        "actions": [
            "other"
        ]
    },
    {
        "_id": "a08a73157cf64b0d93a7ebc2752c9296",
        "type": "url",
        "title": "GEOFLA® sur le site de l'IGN",
        "url": "http://professionnels.ign.fr/geofla",
        "kind": "url",
        "actions": [
            "download",
            "other"
        ]
    },
    {
        "_id": "19a3e3fce4d346bab8e1ffa081bfb9aa",
        "type": "url",
        "title": "Télécharger sur le site de l'IGN",
        "url": "https://wxs-telechargement.ign.fr/oikr5jryiph0iwhw36053ptm/telechargement/inspire/GEOFLA_THEME-DEPARTEMENTS_2014_GEOFLA_2-0_DEPARTEMENT_SHP_LAMB93_FXX_2014-12-05/file/GEOFLA_2-0_DEPARTEMENT_SHP_LAMB93_FXX_2014-12-05.7z",
        "kind": "data",
        "actions": [
            "download"
        ]
    },
    {
        "_id": "db19f350cfa84e5384a70962d893a86e",
        "type": "link",
        "title": "Couche des départements de France métropolitaine",
        "url": "http://noisy.hq.isogeo.fr:6090/geoserver/Isogeo/wms?layer=Isogeo:DEPARTEMENT_2014",
        "kind": "url",
        "actions": [
            "view"
        ],
        "link": {
            "_id": "d290c64acf3b46afa38c65f87bfd8019",
            "type": "url",
            "title": "Couche des départements de France métropolitaine (2014)",
            "url": "http://noisy.hq.isogeo.fr:6090/geoserver/Isogeo/wms?layer=Isogeo:DEPARTEMENT_2014",
            "kind": "wms",
            "actions": [
                "view"
            ]
        }
    },
    {
        "_id": "a3d679343b02404891822b87a10591c1",
        "type": "link",
        "title": "Polygones des départements (2014)",
        "url": "http://noisy.hq.isogeo.fr:6090/geoserver/Isogeo/ows?typeName=Isogeo:DEPARTEMENT_2014",
        "kind": "url",
        "actions": [
            "view"
        ],
        "link": {
            "_id": "71bfe70df37647d2abf1f265a952036e",
            "type": "url",
            "title": "Polygones des départements de France métropolitaine (2014)",
            "url": "http://noisy.hq.isogeo.fr:6090/geoserver/Isogeo/ows?typeName=Isogeo:DEPARTEMENT_2014",
            "kind": "wfs",
            "actions": [
                "view"
            ]
        }
    }

],
```

Because I'm really nice, you can check this [sample](https://github.com/Guts/isogeo-api-py-minsdk/blob/master/isogeo_pysdk/samples/related_links.py).

**Comment by TheoSinatti** [comment]
d607738
