### ISSUE TITLE
[métadonnées détaillées] rendre paramétrable le fond de carte de l'onglet "Géographie"

### ISSUE THREAD

**Issue by LucasMercier306** [isogeo/isogeo-plugin-qgis#384]
## CONTEXTE :
Actuellement le plugin requête l'API OpenStreetMap (http://tile.openstreetmap.org/) pour récupérer une couche WMTS servant de fond de carte dans la rubrique "Géographie" des fiches de métadonnées complète.
Or, dans le cadre de l'*on premises*, on prévoit que l'utilisateur ait accès à l'API Isogeo mais pas à Internet.

## OBJECTIF :
Dans un premier temps, il faudrait vérifier le rendu (ce qui s'affiche à la place du fond de carte) et le comportement (message d'erreur indiquant que la requête a échoué) dans le cas où le poste de l'utilisateur ne serait pas connecté à Internet.

Dans un second temps, il faudrait réfléchir à remplacer le fond de carte OpenStreetMap par un autre service accessible sans connexion Internet ou par un Raster à placer dans le répertoire d'installation du plugin. Permettre à l'utilisateur d'indiquer l'URL de son service perso.

**Comment by SimonSAMPERE** [comment]
permettre d'indiquer une URL custom dans `config.json`

**Comment by Mouzzi-C** [comment]
### Recette réalisée sur QGIS 3.16.10 et 3.22.7

Test réalisé avec ce fond de carte "background_map_url": "type=xyz&format=image/png&styles=default&tileMatrixSet=250m&url=https://a.tile.opentopomap.org/0/0/0.png"

Le fond de carte est bien modifié mais n'est pas centré sur l'emprise de la donnée (cf. capture)

![image](https://user-images.githubusercontent.com/63340073/174084556-76b02227-745f-4d50-9493-435ca9ed861d.png)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C mon commentaire de recette n'était pas très claire, les URLs doivent contenir "{z}/{x}/{y}" et non "0/0/0". Est-ce que tu peux me confirmer que ça fonctionne avec les 2 URLs suivantes : 
* type=xyz&format=image/png&styles=default&tileMatrixSet=250m&url=https://a.tile.opentopomap.org/{z}/{x}/{y}.png
* type=xyz&format=image/png&styles=default&tileMatrixSet=250m&url=https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png

**Comment by Mouzzi-C** [comment]
AH yes, on avait vu ça ensemble. my bad. 

ça fonctionne bien. Je le passe en checked.
