### ISSUE TITLE
[On premises] Gestion de l'ouverture des formulaires PipeDrive dans le navigateur sans connexion Internet

### ISSUE THREAD

**Issue by LucasMercier306** [isogeo/isogeo-plugin-qgis#385]
## CONTEXTE :

Actuellement il y a des boutons dans la fenêtre d'authentification du plugin pour ouvrir des formulaires PipeDrive dans le navigateur.
Or, dans le cadre de l'*on premises*, on prévoit que l'utilisateur ait accès à l'API Isogeo mais pas à Internet.

## OBJECTIF :

Dans un premier temps, il faudrait vérifier le comportement dans le cas où le poste de l'utilisateur ne serait pas connecté à Internet.

**Comment by SimonSAMPERE** [comment]
plus nécessaire #451

**Comment by SimonSAMPERE** [comment]
plus nécessaire #451
