### ISSUE TITLE
[On premises] Gestion de l'ouverture de l'aide en ligne dans le navigateur sans connexion Internet

### ISSUE THREAD

**Issue by LucasMercier306** [isogeo/isogeo-plugin-qgis#386]
## CONTEXTE :

Actuellement il y a un bouton dans l'onglet "Paramètre" du plugin pour ouvrir l'aide en ligne dans le navigateur.
Or, dans le cadre de l'*on premises*, on prévoit que l'utilisateur ait accès à l'API Isogeo mais pas à Internet.

## OBJECTIF :

Dans un premier temps, il faudrait vérifier le comportement dans le cas où le poste de l'utilisateur ne serait pas connecté à Internet.

Dans un second temps, il faudrait réfléchir à ajouter les fichiers HTML de l'aide en ligne au répertoire du plugin et configurer le bouton pour qu'il ouvre l'aide en ligne stockée localement dans son navigateur.

**Comment by Mouzzi-C** [comment]
C'est bon pour moi. Je le passe en checked.
