### ISSUE TITLE
Gestion des services ouverts de l'IGN

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#392]
Suite à l'ouverture de nombreuses données, l'IGN semble avoir mis en place de [nouveaux services géographiques](https://geoservices.ign.fr/services-web) dont l'utilisation ne requiert plus de renseigner une clef : 

- [x] ["découverte"](https://geoservices.ign.fr/services-web-decouverte) : [Service d'images tuilées WMTS](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc) `https://wxs.ign.fr/decouverte/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities`
* ["essentiels"](https://geoservices.ign.fr/services-web-essentiels)
  - [x] [Images Tuilées - WMTS (OGC)](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc) `https://wxs.ign.fr/essentiels/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities`
  - [ ] [Vecteur tuilé – TMS/WMTS](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/vecteur-tuile-tmswmts) `http://wxs.ign.fr/CLE/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities`
  - [x] [image WMS Raster](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-wms-ogc) `https://wxs.ign.fr/essentiels/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
  - [x] [image WMS Vecteur](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-wms-ogc) `https://wxs.ign.fr/essentiels/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
  - [x] [Données vecteur - WFS (OGC)](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/donnees-vecteur-wfs-ogc) `https://wxs.ign.fr/essentiels/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
* ["experts"](https://geoservices.ign.fr/services-web-experts)
  * WMTS
    - [x] [Administratif](https://geoservices.ign.fr/services-web-experts-administratif) : `https://wxs.ign.fr/administratif/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Agriculture](https://geoservices.ign.fr/services-web-experts-agriculture) : `https://wxs.ign.fr/agriculture/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Altimétrie](https://geoservices.ign.fr/services-web-experts-altimetrie) : `https://wxs.ign.fr/altimetrie/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Cartes](https://geoservices.ign.fr/services-web-experts-cartes) : `https://wxs.ign.fr/cartes/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Cartovecto](https://geoservices.ign.fr/services-web-experts-cartovecto) : `https://wxs.ign.fr/cartovecto/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Corine Land Cover (CLC)](https://geoservices.ign.fr/services-web-experts-clc) : `https://wxs.ign.fr/clc/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Économie](https://geoservices.ign.fr/services-web-experts-economie) : `https://wxs.ign.fr/economie/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Environnement](https://geoservices.ign.fr/services-web-experts-environnement) : `https://wxs.ign.fr/environnement/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Ortho](https://geoservices.ign.fr/services-web-experts-ortho) : `https://wxs.ign.fr/ortho/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Orthohisto](https://geoservices.ign.fr/services-web-experts-orthohisto) : `https://wxs.ign.fr/orthohisto/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Satellite](https://geoservices.ign.fr/services-web-experts-satellite) : `https://wxs.ign.fr/satellite/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Lambert-93](https://geoservices.ign.fr/services-web-experts-lambert-93) : `https://wxs.ign.fr/lambert93/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Sol](https://geoservices.ign.fr/services-web-experts-sol) : `https://wxs.ign.fr/sol/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Parcellaire](https://geoservices.ign.fr/services-web-experts-parcellaire) : `https://wxs.ign.fr/parcellaire/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
    - [x] [Transports](https://geoservices.ign.fr/services-web-experts-transports) : `https://wxs.ign.fr/transports/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
  * WMS raster
    - [x] [Administratif](https://geoservices.ign.fr/services-web-experts-administratif) : `https://wxs.ign.fr/administratif/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Agriculture](https://geoservices.ign.fr/services-web-experts-agriculture) : `https://wxs.ign.fr/agriculture/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Altimétrie](https://geoservices.ign.fr/services-web-experts-altimetrie) : `https://wxs.ign.fr/altimetrie/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Cartes](https://geoservices.ign.fr/services-web-experts-cartes) : `https://wxs.ign.fr/cartes/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Cartovecto](https://geoservices.ign.fr/services-web-experts-cartovecto) : `https://wxs.ign.fr/cartovecto/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Corine Land Cover (CLC)](https://geoservices.ign.fr/services-web-experts-clc) : `https://wxs.ign.fr/clc/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Économie](https://geoservices.ign.fr/services-web-experts-economie) : `https://wxs.ign.fr/economie/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Environnement](https://geoservices.ign.fr/services-web-experts-environnement) : `https://wxs.ign.fr/environnement/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Ortho](https://geoservices.ign.fr/services-web-experts-ortho) : `https://wxs.ign.fr/ortho/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Orthohisto](https://geoservices.ign.fr/services-web-experts-orthohisto) : `https://wxs.ign.fr/orthohisto/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Satellite](https://geoservices.ign.fr/services-web-experts-satellite) : `https://wxs.ign.fr/satellite/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Lambert-93](https://geoservices.ign.fr/services-web-experts-lambert-93) : `https://wxs.ign.fr/lambert93/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Sol](https://geoservices.ign.fr/services-web-experts-sol) : `https://wxs.ign.fr/sol/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Parcellaire](https://geoservices.ign.fr/services-web-experts-parcellaire) : `https://wxs.ign.fr/parcellaire/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Transports](https://geoservices.ign.fr/services-web-experts-transports) : `https://wxs.ign.fr/transports/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
  * WMS vecteur
    - [x] [Adresse](https://geoservices.ign.fr/services-web-experts-adresse) : `https://wxs.ign.fr/adresse/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Altimétrie](https://geoservices.ign.fr/services-web-experts-altimetrie) : `https://wxs.ign.fr/altimetrie/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Cartes](https://geoservices.ign.fr/services-web-experts-cartes) : `https://wxs.ign.fr/cartes/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Cartovecto](https://geoservices.ign.fr/services-web-experts-cartovecto) : `https://wxs.ign.fr/cartovecto/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Économie](https://geoservices.ign.fr/services-web-experts-economie) : `https://wxs.ign.fr/economie/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Environnement](https://geoservices.ign.fr/services-web-experts-environnement) : `https://wxs.ign.fr/environnement/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Géodésie](https://geoservices.ign.fr/services-web-experts-geodesie) : `https://wxs.ign.fr/geodesie/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Ortho](https://geoservices.ign.fr/services-web-experts-ortho) : `https://wxs.ign.fr/ortho/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Orthohisto](https://geoservices.ign.fr/services-web-experts-orthohisto) : `https://wxs.ign.fr/orthohisto/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Satellite](https://geoservices.ign.fr/services-web-experts-satellite) : `https://wxs.ign.fr/satellite/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Parcellaire](https://geoservices.ign.fr/services-web-experts-parcellaire) : `https://wxs.ign.fr/parcellaire/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
    - [x] [Transports](https://geoservices.ign.fr/services-web-experts-transports) : `https://wxs.ign.fr/transports/geoportail/v/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
  * WFS
    - [x] [Administratif](https://geoservices.ign.fr/services-web-experts-administratif) : `https://wxs.ign.fr/administratif/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Adresse](https://geoservices.ign.fr/services-web-experts-adresse) : `https://wxs.ign.fr/adresse/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Agriculture](https://geoservices.ign.fr/services-web-experts-agriculture) : `https://wxs.ign.fr/agriculture/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Altimétrie](https://geoservices.ign.fr/services-web-experts-altimetrie) : `https://wxs.ign.fr/altimetrie/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Cartes](https://geoservices.ign.fr/services-web-experts-cartes) : `https://wxs.ign.fr/cartes/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Cartovecto](https://geoservices.ign.fr/services-web-experts-cartovecto) : `https://wxs.ign.fr/cartovecto/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Corine Land Cover (CLC)](https://geoservices.ign.fr/services-web-experts-clc) : `https://wxs.ign.fr/clc/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Économie](https://geoservices.ign.fr/services-web-experts-economie) : `https://wxs.ign.fr/economie/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Environnement](https://geoservices.ign.fr/services-web-experts-environnement) : `https://wxs.ign.fr/environnement/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Géodésie](https://geoservices.ign.fr/services-web-experts-geodesie) : `https://wxs.ign.fr/geodesie/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Ortho](https://geoservices.ign.fr/services-web-experts-ortho) : `https://wxs.ign.fr/ortho/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Orthohisto](https://geoservices.ign.fr/services-web-experts-orthohisto) : `https://wxs.ign.fr/orthohisto/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Satellite](https://geoservices.ign.fr/services-web-experts-satellite) : `https://wxs.ign.fr/satellite/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Lambert-93](https://geoservices.ign.fr/services-web-experts-lambert-93) : `https://wxs.ign.fr/lambert93/geoportail/wfs?request=GetCapabilities`
    - [x] [Sol](https://geoservices.ign.fr/services-web-experts-sol) : `https://wxs.ign.fr/sol/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Parcellaire](https://geoservices.ign.fr/services-web-experts-parcellaire) : `https://wxs.ign.fr/parcellaire/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Topographie](https://geoservices.ign.fr/services-web-experts-topographie) : `https://wxs.ign.fr/topographie/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`
    - [x] [Transports](https://geoservices.ign.fr/services-web-experts-transports) : `https://wxs.ign.fr/transports/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities`

**Comment by SimonSAMPERE** [comment]
## Commentaire de recette :

Le code source a été modifié de sorte à gérer les services de l'IGN utilisés au CD31. Tous les services listés dans la description du ticket n'ont donc pas été testés.
Tous ces nouveaux services ont été documentés dans [ce catalogue](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad8cab92c4b6d4066a06c998cc60ba840). Ils peuvent donc être testés dans le plugin QGIS en utilisant directement la fiche de service (pas besoin d'associer les couches pour la recette).

Il faudrait donc valider qu'il est possible d'ajouter les couches de chacun de ces services (en les cochant au fur et à mesure dans la description du ticket) en étant particulièrement attentif à : 
* la possibilité d'ajouter la couche quelle que soit la projection courante du projet
* la possibilité d'ajouter les couches WFS contenant beaucoup d'entités (comme bâtiments) en zoomant sur une petite zone de la carte pour qu'un petit nombre d'entités soit requêté
* valider que le comportement d'ajout d'une couche en passant par le plugin Isogeo est similaire à celui obtenu en passant par le gestionnaire des sources de données de QGIS

**Comment by jgrosmaire** [comment]
# Résultats recette

(en cours)

## Test WFS contenant beaucoup d'entité

Test avec la couche : BDTOPO_V3:batiment title du service Experts - Topographique en zoomant sur une petite zone

Différents comportements ont été observés pour une même emprise : 

* **Comportement 1 :** Affichage sans erreur
* ![image](https://user-images.githubusercontent.com/66669475/145380980-d3573bd2-9bf8-4bda-a2e9-0d84e659ff0c.png)

* **Comportement 2** : Erreur (pas possible d'afficher le journal de bord car freeze général de QGIS). En fonction des cas, ce message s'affiche plusieurs fois. 
![image](https://user-images.githubusercontent.com/66669475/145381787-d2c0ff8e-1908-4796-9a47-bdc568d38eb9.png)
  * Dans certains cas, les bâtiments s'affichent
  * Dans certains cas , ça s'arrête d'essayer mais rajoute un élément dans la légende.
![image](https://user-images.githubusercontent.com/66669475/145382594-09d04b6a-3f13-4446-b83e-64fd07c11cf7.png)
![image](https://user-images.githubusercontent.com/66669475/145383134-99d68966-20c5-4928-b767-48ad80b3b274.png)

* **Comportement 3** : Seulement observé après la suppression de la couche bâtiments et son appel juste après. Cette erreur s'affiche : 
![image](https://user-images.githubusercontent.com/66669475/145381127-06d1ba23-f3e9-49e7-b1b9-25b0ca858aca.png)

**Comment by SimonSAMPERE** [comment]
# Réponses recette

## Services qui ne fonctionnent pas en utilisant le plugin

### [WFS Satellite](https://wxs.ign.fr/satellite/geoportail/wfs) ([fiche APP](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/06d3ac03a3b84a8999b28a80380c49e8/identification)) ✅

J'ai retesté de mon côté et les couches sont ajoutables, il devait s'agir d'un problème momentané d'accessibilité du serveur de l'IGN.

### [WFS Cartes](https://wxs.ign.fr/cartes/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities) ✅

J'ai retesté de mon côté et les couches sont ajoutables, il devait s'agir d'un problème momentané d'accessibilité du serveur de l'IGN.

## Comportements étanges

### Test WFS contenant beaucoup d'entité ✅

J'ai observé le même type de comportements aléatoires, malheureusement je ne vois ps comment le traiter.

### Warning sur la projection ✅

De mon côté j'ai réussi à ajouter les couches. J'aurais eu besoin d'infos sur la configuration de QGIS en termes de SRS. Je pense que les time-out s'expliquent aussi par des soucis côté serveurs de l'IGN.

Étant donné le nombre de couches concernées, je considère que ça n'est pas bloquant pour la mise en prod. Si un utilisateur nous signale le problème je créerai un ticket dédié.

Merci pour la recette.
