### ISSUE TITLE
Gestion des thématiques

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#393]
https://github.com/isogeo/isogeo-app/issues/151

# Affichage dans la fiche détaillée
- [x] Les afficher dans l'onglet général, avant les mots-clefs.

# Ajout d'un filtre dans le moteur de recherche
Réduire la taille du champ de recherche textuelle et du bouton "rechercher". Déplacer la liste déroulante des recherches rapides à droite de la barre de recherche textuelle.
Ajouter une ligne en haut de la rubrique advanced search avec : 
* une liste déroulante comme celle des thématiques Inspire pour les thématiques
* la liste déroulante cochable des mots-clefs

- [x] adapter l'UI
![image](https://user-images.githubusercontent.com/41120579/165502366-583c9a7f-56ec-4e94-a383-c7cf1040159c.png)

- [x] ajuster la ccbb des keywords : 
  - [x] corriger le tooltip indiquant les options sélectionnée
  - [x] traiter les labels comme les titre de fiches détaillées (#406) en ajoutant un tooltip avec le nom complet du mot-clef quand c'est nécessaire
  - [x] vérifier les effets de bord de la suppression de l'option "--- Keywords ---"
- [x] connecter la cbb des group theme comme celle des thèmes INSPIRE

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Vérifier que la recherche sur les thématiques fonctionne comme dans app.
Vérifier que les thématiques sont correctement affichée les fiches détaillée.

**Comment by Mouzzi-C** [comment]
C'est bon pour moi. Je le passe en checked
