### ISSUE TITLE
[Oracle] permettre l'ajout des vues "dynamiques"

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#394]
https://github.com/isogeo/isogeo-plugin-qgis/issues/377
```SQL
select col.owner, col.table_name, column_name, data_type from sys.all_tab_cols col join sys.all_views v on col.owner = v.owner and col.table_name = v.view_name where col.data_type = 'SDO_GEOMETRY' and col.owner not in {} order by col.owner, col.table_name, column_id
```

**Comment by SimonSAMPERE** [comment]
## Commentaire de recette : 

Si j'ai bien compris, les vues "dynamiques" comme `ISOGEO_TEST_SPATIAL.V_DEPARTEMENT_IDF` sont simplement des vues. On rajoute "dynamique" pour les distinguer des vues matérialisées comme `ISOGEO_TEST_SPATIAL.VM_DEPARTEMENT_IDF` (qui sont déjà ajoutables via le plugin). 
Il faudrait donc créer des vues dans la base Oracle et vérifier qu'on peut les ajouter à la carte en utilisant le plugin.

**Comment by SimonSAMPERE** [comment]
* pour créer une vue "dynamique" : https://desktop.arcgis.com/fr/arcmap/10.6/manage-data/using-sql-with-gdbs/example-creating-a-spatial-view-in-oracle-with-sql.htm
* pour référencer la vue dans la table `user_sdo_geom_metadata` de sorte à ce qu'elle soit prise en compte par le Scan : https://community.safe.com/s/article/adding-metadata-entries-for-oracle-spatial-tables
* ne pas oublier `commit WORK;` pour "sauvegarder" la création et le référencement de la vue

**Comment by Mouzzi-C** [comment]
la vue RECETTE_VUES_ENCORE est ajoutées à la carte en deux exemplaires. 
![image](https://user-images.githubusercontent.com/63340073/148198762-e5180c00-ddfd-43e2-a5ba-89994843bb97.png)

utiliser le mot-clé "vue" pour retrouver les 4 vues utilisées dans la recette

**Comment by SimonSAMPERE** [comment]
Le problème vient du fait que la vue "RECETTE_VUE_ENCORE" possède des entités de type polygon et des entités de type mutli-polygone. Dans le cadre de #395, j'ai fait en sorte que dans le cas où une données est constituée de plusieurs types de géométrie, une couche soit ajoutée par type de géométrie. Il faut que je corrige ce comportement pour que ça ne soit pas le cas si les différents types sont : 
* point et multi-point
* ligne et multi-ligne
* polygone et multi-polygone

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C dès que j'aurais fait le correctif je m'occuperait de le recetter. Bien joué en tous cas d'avoir découvert ce comportement !
