### ISSUE TITLE
[Oracle] la couche ne s'affiche pas selon la projection courante du projet 

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#396]
(à partir de QGIS 3.8) en cochant la case "utiliser le SRS par défaut", la couche s'ajoute à la légende mais n'est pas visible si c'est pas la projection sachant que leurs données c'est du 2154 --> faut que la couche s'ajoute quelle que soit la projection

https://stackoverflow.com/questions/60169403/how-to-check-the-srid-of-my-table-oracle

**Comment by jgrosmaire** [comment]
C'est bon pour moi pour les différentes combinaisons.

Juste pour l'info, avec la config SCR par défaut (EPSG:7659), ça ne s'aligne pas avec la donnée importée directement avec l'explorateur que je n'arrive pas à voir. Par contre, ça coïncide avec des services, donc ça semble bien. 

![image](https://user-images.githubusercontent.com/66669475/145554023-a8d54c83-8751-407a-aaff-c88540353a2b.png)
