### ISSUE TITLE
Problème de script

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#40]
J'ai cette fenêtre qui apparait de manière récurrente
![prb_script20160908](https://cloud.githubusercontent.com/assets/20684784/18340718/cfdde414-75a6-11e6-8282-1b02532f236a.JPG)

**Comment by TheoSinatti** [comment]
Utilisez-vous la version disponible dans le canal des extensions de QGIS ou bien la version de développement téléchargée depuis Github ? 
Si vous utilisez la version disponible depuis les extensions de QGIS, il est possible qu'il s'agisse d'un bug connu, et corrigé depuis.
J'avais observé l'apparition fréquente de ce problème lorsque le plugin a été ouvert, puis fermé, puis ouvert à nouveau. 
Plus clairement, le plugin fonctionnait correctement lors de sa première ouverture (après le démarrage de QGIS) mais ce problème apparaissait fréquemment lorsque celui-ci avait été fermé puis ouvert à nouveau dans la même session de QGIS. 
Si vous testez bien sur la version disponible dans le canal des extensions de QGIS, et que ce problème apparait bien selon cette modalité (seulement si le plugin a été fermé puis ré-ouvert), alors le problème a déjà été pris en compte et corrigé. 
Si vous testez sur une version plus récente, ou que le problème apparait même lors du premier lancement du plugin, alors il s'agit bien d'un problème non encore corrigé.
Merci de me préciser les conditions de test afin de pouvoir déterminer de quoi il retourne.

**Comment by Guts** [comment]
Utilisation de la version 0.3-beta sur QGIS 2.14.6 LTR sur Win10.
Ça se produit au moment de la sélection d'un filtre.
Après le message, la liste des filtres est quand même mise à jour et l'utilisation est normale par la suite (jusqu'à réapparition du même message).
Le plugin n'a pas été fermé puis réouvert.

Voici le message qui intervient dans la console Python :

![isogeo_plugin_bug_api](https://cloud.githubusercontent.com/assets/1596222/18442435/0564bb54-7911-11e6-8be9-5dfa45d22a87.png)

**Comment by TheoSinatti** [comment]
Je reconnais les messages d'erreur, le contenu de la console, ... comme les signes du problème récurrent qui apparait lorsque deux requêtes se chevauchent. Je pensais avoir géré la totalité des cas d'apparition.
Si le problème apparait toujours, et qui plus est sans qu'une manipulation "spéciale" n'ait été faite, c'est très mauvais signe.
Cela dit, je n'arrive pas à le reproduire. Sur les 3 ordinateurs (dont un mac) que j'ai testé, tout fonctionne normalement.

**Comment by Guts** [comment]
Plutôt que d'afficher une popup, afficher un QMessageBar

**Comment by TheoSinatti** [comment]
Done.
