### ISSUE TITLE
[métadonnée détaillée] ajouter le nom technique de la donnée dans la fiche de métadonnées détaillée

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#402]
Dans l'onglet général, écrire le nom technique entre parenthèses et pas en gras à la suite du titre (comme dans app)

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Vérifier que le nom de la donnée est bien écrit entre parenthèse et pas en gras après le titre de la fiche dan l'onglet "Général" de la fiche de métadonnée détaillée. Tester avec des titres plus ou moins long occupant une ou plusieurs lignes et vérifier que rien n'est écrit lorsque la fiche n'a pas de nom.

**Comment by Mouzzi-C** [comment]
c'est bon pour moi, je l'ai passé en checked
