### ISSUE TITLE
[métadonnée détaillée] créer un onglet dédié à la Qualité

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#403]
Y mettre la rubrique "Qualité" de l'onglet "Géométrie" (spécifications et cohérence topologique).

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Vérifier pour les différents types de fiches auxquelles on peut associer une spécification ou pour lesquelles on peut définir la cohérence topologique : 
* vecteur
* raster
* service
* dtng
* ensemble de données

...que dans la fiche détaillée, un onglet "Qualité" est présent et contient les informations relatives à la cohérence topologique et aux spécifications.

**Comment by Mouzzi-C** [comment]
ça fonctionne bien mais il faudrait garder ce champ uniquement pour les données vecteur. pour les types de données ce champs ne s'affichera plus à partir la prochaine mise en prod d'app

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

vérifier que la cohérence topologique s'affiche uniquement dans les fiches de métadonnées détaillées de type vecteur.

**Comment by Mouzzi-C** [comment]
ça fonctionne bien par contre

Je passe peut-être pour un chieur mais je viens de voir qu'il manque un espace avant les ":" à chaque fois --> 
![image](https://user-images.githubusercontent.com/63340073/166897474-5dff3b13-6772-4802-90c9-91d3c432ba28.png)
