### ISSUE TITLE
[métadonnée détaillée] Renommer l'onglet "Géométrie" en "Géographie"

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#404]
# commentaire de recette

Vérifier pour les différents types de fiches pour lesquelles on affiche l'onglet géographie : 
* vecteur
* raster
* service
* dtng
* ensemble de données

... que dans la fiche détaillée, le nom de l'onglet est bien "Géographie" et non plus "Géométrie" **lorsque QGIS est en français**.

**Comment by Mouzzi-C** [comment]
C'est bon pour, je le passe en checked
