### ISSUE TITLE
[dtng] intégration dans le plugin

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#405]
# Général
- [x] mettre à jour les modules concernés du `isogeo-pysdk`

# Moteur de recherche
- [x] ~~Ajouter l'option dans le filtre "Type de ressource"~~ (géré nativement)
- [x] Modifier l'option "Données (vecteur et raster)" et la remplacer par "Données (vecteurs, rasters et tabulaires)"

# Affichage des résultats
- [x] Utiliser cette icône native de QGIS : ![image](https://user-images.githubusercontent.com/41120579/148372963-1b8917f8-2f40-45b0-aa27-2336a6da5d2c.png) dans la troisième colonne.

# Affichage de la fiche détaillée
- [x] Adapter l'onglet "Géographie" : 
  - [x] enlever la rubrique "Aperçu de l'enveloppe"
  - [x] suite à #404 on aura pas à renommer l'onglet
  - [x] dans les infos technique, laisser uniquement "format" et "nombre d'objets"
  - [x] ajouter une rubrique "Contexte géographique"

# Ajout à la carte
- [x]  Permettre l'ajout des tables non géographiques : 
  - [x] Oracle
  - [x] PostGIS

**Comment by SimonSAMPERE** [comment]
# commentaire de recherche

Vérifier que la recherche sur le type de métadonnées correspondant aux DTNG fonctionne comme dans app.
Vérifier que les DTNG renvoyées par une recherche s'affichent correctement dans le tableau des résultats.
Vérifier que les fiches de métadonnées détaillées de type DTNG comportement bien toutes les champs de métadonnées et uniquement ces champs là.
Vérifier qu'il est possible d'ajouter une DTNG Postgre ou Oracle

**Comment by Mouzzi-C** [comment]
## Recette

1. ok
2. ok
3. Comportement observé pour les autres type de données : les évènement de type publication ne s'affichent pas dans la liste ([fiche app](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/6ee5687878ad4909a8ee7ca0cfa71742/history)). All good sinon
4. ok
