### ISSUE TITLE
[métadonnée détaillée] gérer les titres trop longs 

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#406]
gérer les titres vraiment trop longs comme ils le sont dans les boutons de la première colonne des résultats pour éviter ça : 
![image](https://user-images.githubusercontent.com/41120579/148544029-a1e9734a-7887-4690-9443-b7013fe139aa.png)

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Vérifier que les titres composés d'un seul mot très très long sont justifiés à gauche et interrompus par "..."

**Comment by Mouzzi-C** [comment]
C'est bon pour moi, je le passe en checked
