### ISSUE TITLE
Le plugin ne permet pas d'ajouter deux couches de service d'un même format et d'un même nom

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/isogeo-plugin-qgis#408]
Dans la fiche complète [Donnée vecteur - Département](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/642815c48f3f4f7fae8c1470ba981267/resources) du partage de Test, plusieurs services sont associés. Cependant certaines couches ont le meme nom et le même format. Or le plugin ne propose d'ajouter à la carte qu'une seule sur les deux. 

![image](https://user-images.githubusercontent.com/16936198/150553015-e1110ec4-fe51-4174-9550-92f07f81c424.png)

Il faudrait gérer le cas ou les couches ont le même nom, le même format mais proviennent pas du même service

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Vérifier dans le cas d'une fiche à laquelle sont associées plusieurs couche ayant le même titre et provenant d'un service dont le format est identique que toutes les couches sont proposées dans la liste déroulante des options d'ajout et que toutes ces couches sont ajoutables.
