### ISSUE TITLE
Actualisation de la liste des résultats

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#41]
Serait-il possible que la liste des résultats s'actualise automatiquement suite au choix d'un paramètre de recherche ou d'un filtre ?

**Comment by TheoSinatti** [comment]
Il s'agit de la manière dont le plugin fonctionnait initialement, mais nous avons préféré changer pour la raison suivante.
Le temps nécessaire pour déterminer si une donnée peut être ajoutée ou non au canevas est important. C'est ce qui ralentit considérablement l'affichage des résultats. Vous avez probablement remarqué que l'attente après avoir cliqué sur "Afficher les résultats" peut être de plus de 5 secondes. 
Mettre à jour la liste de résultat à chaque modification d'un champ reviendrait donc à effectuer ce calcul à chaque fois. Il y aurait une étape de moins, mais paradoxalement, le plugin serait fortement ralenti.
L'idée est que cette lenteur ne soit ressentie qu'une fois et non 3, 4 ou 5 fois selon le nombre de filtres choisi.
Si toutefois vous préférez basculer vers l'affichage automatique des résultats, n'hésitez pas à le faire savoir (en indiquant les raisons qui vous poussent à privilégier ce fonctionnement, si possible) !
