### ISSUE TITLE
[Quicksearch] adapter le contenu du fichier quicksearches.json aux URLs renseignées dans config.json

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#410]
# Commentaire de recette

1. [enregistrer une recherche rapides](https://help.isogeo.com/qgis/fr/usage/advanced/quicksearch.html)
2. [modifier la recherche par défaut](https://help.isogeo.com/qgis/fr/usage/advanced/defaultsearch.html)
3. modifier le fichier `config.json` qui se trouve à la racine du répertoire d'installation du plugin (il est créé lorsque le plugin est activé dans le gestionnaire des extensions) de sorte à indiquer une autre API (modifier les variables `api_base_url` et `api_auth_url`), par exemple celle de QA.
4. redémarrer QGIS et ré-ouvrir le plugin

Comportement souhaité:
* la recherche par défaut et les recherches rapides fonctionnent toujours
* dans le fichier `_user/quicksearches.json`, la valeur des variables `url` contient la dernière URL d'API indiquée dans le fichier `config.json`

**Comment by Mouzzi-C** [comment]
### Recette

Version de QGIS : 3.16.10

L'enregistrement rapide n'a pas fonctionné. cf. erreur ci-dessous : 

Une erreur est survenue lors de l'éxécution du code Python: 

```
KeyError: '' 
Traceback (most recent call last):
  File "C:/Users/CarloMOUZANNAR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isogeo_search_engine\modules\quick_search.py", line 136, in rename
    saved_searches[new_name] = saved_searches[old_name]
KeyError: ''


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.16.10-Hannover Hannover, e5b665e952 

Chemin Python :
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/CarloMOUZANNAR/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/CarloMOUZANNAR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/CarloMOUZANNAR/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C je n'arrive pas à reproduire l'erreur, est-ce que tu pourrais me récapituler les étapes et me mettre le fichier de logs ?

**Comment by Mouzzi-C** [comment]
ça fonctionne bien. 

Il y a juste un comportement bizarre. En effet, lorsque le fichier config.json est modifié, le plugin est automatiquement désactivé à la réouverture de QGIS. 
![image](https://user-images.githubusercontent.com/63340073/174825461-f991f0d7-6ea1-41a9-801d-8509a6ff1c34.png)

Le comportement est le avec la 3.16 et 3.22


Si c'est ok pour toi, tu peux passer le ticket en checked.

**Comment by SimonSAMPERE** [comment]
Ah mais au temps pour moi je croyais que c'était le plugin Isogeo qui faisait planter QGIS mais si c'est Processing c'est good, je passe en check, merci man. 
Ça arrive de temps en temps que Processing fasse planter QGIS je sais pas trop pourquoi, si tu en as besoin il suffit de le réactiver dans le gestionnaire des extensions normalement.
