### ISSUE TITLE
Compatibilité Linux

### ISSUE THREAD

**Issue by jgrosmaire** [isogeo/isogeo-plugin-qgis#416]
## Contexte
 
QGIS peut être installé sur Linux, il faut être sûrs que le plugin peut aussi l'être. Si non, il faudra réaliser les modifications nécessaires. 

Ajouter un tooltip pour expliquer pourquoi ya pas d'Oracle.

**Comment by SimonSAMPERE** [comment]
@LyesIsogeo , aurais-tu une solution à me proposer pour mettre en place facilement un environnement Linux (avec un GUI) dans lequel je pourrai installer QGIS et le plugin Isogeo ?

**Comment by jgrosmaire** [comment]
Je suis pas Lyes mais une VM en local sur ton PC est sûrement le plus facile.

**Comment by LyesIsogeo** [comment]
Totalement d'accord avec Julie !

**Comment by SimonSAMPERE** [comment]
# Commentaire de recette

Il faudrait idéalement faire une recette complète du plugin QGIS dans un environnement Linux. Ou au moins une recette "light" (tester toutes les options d'ajout), tester différentes recherches, tester les recherches rapide, tester la gestion de multiple connexions à une même BDD.

**Comment by Mouzzi-C** [comment]
### Recette

1. Taille du plugin non modulable
qgis sans plugin (fullscreen) : 
![image](https://user-images.githubusercontent.com/63340073/174102771-8fd15788-d5a0-4935-b81c-9cd6e86f6f8d.png)

qgis avec plugin
![image](https://user-images.githubusercontent.com/63340073/174102922-48e62ed7-bce5-4f22-a513-9502680a9439.png)

Il est possible de modifier la taille du plugin latéralement mais pas verticalement.

2. fichier json non trouvé pour modifier le client_secret
![image](https://user-images.githubusercontent.com/63340073/174103416-3ebcf0f8-1dc0-4a22-9ea3-1b17942b9407.png)

**à suivre pour le reste de la recette**

**Comment by Mouzzi-C** [comment]
Pour la suite de la recette, je t'ai mis tous les retours dans [le guide de recette du plugin](https://docs.google.com/spreadsheets/d/1NVfVXIJNysdC9zEwVIRh0G3sOze1xXIBanT1AcBcGkk/edit?pli=1#gid=0).

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C concernant le fichier JSON d'authentification qui n'apparaît pas dans l'explorateur de fichier, le problème est résolu.
Le soucis de l'interface du plugin qui est trop grande et qui ne s'affiche pas en entier vient de la résolution de la machine Ubuntu, je vais voir ce que je peux faire mais je considère que c'est la faute de l'environnement. Concernant le filtre géographique, j'ai créé un [ticket dédié](https://github.com/isogeo/isogeo-plugin-qgis/issues/431)

Pour le reste, je te laisse poursuivre la recette et notamment l'ajout de données.

**Comment by Mouzzi-C** [comment]
Avec la résolution de la machine ubuntu il m'est impossible de recetter ce ticket de la maison. Je ferai ça à mon retrou au bureau, la semaine du 18 juillet

**Comment by SimonSAMPERE** [comment]
# point avec Lyes sur la résolution d'affichage de la VM Ubuntu

```cmd
>cvt xxxx yyyy zz
```
par exemple : 

```cmd
>cvt 2048 1152 50

# 2048x1152 49.98 Hz (CVT 2.36M9) hsync: 59.38 kHz; pclk: 161.50 MHz
Modeline "2048x1152_50.00"  161.50  2048 2168 2384 2720  1152 1155 1160 1188 -hsync +vsync
```

copier tout après "Modeline " puis

```cmd
xrandr --verbose --newmode <coller>
```

par exemple : 
```cmd
xrandr --verbose --newmode "2048x1152_50.00"  161.50  2048 2168 2384 2720  1152 1155 1160 1188 -hsync +vsync
```


```
xrandr --verbose --addmode rdp0 "2048x1152_50.00"
```

puis sélectionner le mode "2048x1152_50.00" dans les "settings/display"

**Comment by SimonSAMPERE** [comment]
# Lancement recette par @jgrosmaire 

* sur QGIS 3.22.
* installer la version zippée du plugin dispo dans le One Drive : "\ISOGEO\Development - Documents\Extensions (Dossier Produit)\QGIS\3.4.0\isogeo_search_engine.zip".
* en cas de problème détecté sur Ubuntu : 
  * si problème également détecté sous Windows --> création d'un ticket dédié
  * sinon --> commentaire dans le ticket

**Comment by SimonSAMPERE** [comment]
# Lancement recette par @jgrosmaire 

* suivre le [guide de recette](https://docs.google.com/spreadsheets/d/1NVfVXIJNysdC9zEwVIRh0G3sOze1xXIBanT1AcBcGkk/edit?pli=1#gid=0)
* sur QGIS 3.22.
* installer la version zippée du plugin dispo dans le One Drive : "\ISOGEO\Development - Documents\Extensions (Dossier Produit)\QGIS\3.4.0\isogeo_search_engine.zip".
* en cas de problème détecté sur Ubuntu : 
  * si problème également détecté sous Windows --> création d'un ticket dédié
  * sinon --> commentaire dans le ticket

**Comment by jgrosmaire** [comment]
Recette faîte sur QGIS 3.22 et Ubuntu 20.04, aucun bug spécifique à Linux (outre ce ticket : https://github.com/isogeo/isogeo-plugin-qgis/issues/435) n'a été trouvé.
