### ISSUE TITLE
Compatibilité QGIS 3.28

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#417]
Il faudrait recetter le plugin Isogeo avec QGIS 3.28

**Comment by jgrosmaire** [comment]
# Recette 21 mars

**Version utilisée :** 3.28.4
**Version de comparaison :** 3.22.4

Recette en cours

## Généralités

Les différentes fonctionnalités testées et les résultats sont présentés dans [ce doc](https://docs.google.com/spreadsheets/d/1NVfVXIJNysdC9zEwVIRh0G3sOze1xXIBanT1AcBcGkk)

## Services

Certains sont affichages avec QGIS 3.22 mais pas avec 3.28 : 

* EFS associé à cette [fiche](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/82ee4f0ebede492da4129f640d396268/resources) -> la majorité des services EFS de ce service semble poser problème
![image](https://user-images.githubusercontent.com/66669475/226580952-ee59cdc3-20b2-4260-bf0f-04a87975c31d.png)
![image](https://user-images.githubusercontent.com/66669475/226580805-9b7882e7-8e81-487b-8757-c2d79c5bc022.png)

## Suite de la recette

Reste à recetter : 

- [ ] Contenu en anglais des métadonnées
- [ ] Affichage donnée raster
- [ ] Affichage des services suivants : 
  - [ ]  WMS AGS
  - [ ] EMS AGS
  - [ ] WMS QGIS Server
  - [ ] WFS ArcGIS Server
- [ ] Base PostGIS
- [ ] Base Oracle

**Comment by Mouzzi-C** [comment]
J'ai vi après coup que julie avait utilisé le guide de recette du plugin ❤️ 💟 ❤️‍🔥 

Avec les tests réalisés dans le commentaire précédent, on aura fait le tour. c'est tout bon ! (à part le petit souci de réinitialisation de la recherche par défaut mais ça n'est pas lié à QGIS 3.28 --> je vais créer un ticket pour ça)

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/issues/466
