### ISSUE TITLE
[ResultsManager] Certains espaces sautent pendant le traitement des titres trop longs

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#418]
![image](https://user-images.githubusercontent.com/41120579/163343894-ee01aced-8763-4c20-b205-700c49543f36.png)
[exemple de fiche concernée](https://app.isogeo.com/groups/8e02046c031a454690efe71692d25db5/resources/23bba041e7444f7d90b08817f1cc62e4/identification)

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Vérifier que les titres occupant plusieurs lignes sont correctement écrits.

**Comment by Mouzzi-C** [comment]
C'est bon pour moi, je le passe en checked
