### ISSUE TITLE
Plugin doesn't support QGIS 2.16 Nødebo

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#43]
Plugin crashes at install on the latest version of QGIS. 
This is caused by the norvegian character ø in the name of the version. 
The plugin tries to log QGIS version which causes an encoding problem (ascii error "Ordinal character not in range").
Of course, this line can be removed, for it is just logging, but a better solution could probably be found.

**Comment by Guts** [comment]
Handle encoding name for example?
With a try/except ?

**Comment by TheoSinatti** [comment]
Failed to reproduce the bug on my computer. (occured on another one)
Installed QGIS Nødebo, but everything works fine. 
So still investigating this.

**Comment by TheoSinatti** [comment]
So the bug occurs on QGIS 2.16.0 but not in QGIS 2.16.2 (don't know about 2.16.1)

In QGIS 2.16.2, `QGis.QGIS_VERSION` returns _2.16.2_, whereas QGIS 2.16.0 returns _2.16.0-Nødebo_
I guessed QGIS changed this to avoid a lot of encoding trouble for plugin devs.
(Will put a try/except anyway)
