### ISSUE TITLE
[geo filter] dans certains cas le filtre n'est pas pris en compte dans la recherche

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#431]
Problème soulevé par @Mouzzi-C en recettant le plugin sur Ubuntu : https://docs.google.com/spreadsheets/d/1NVfVXIJNysdC9zEwVIRh0G3sOze1xXIBanT1AcBcGkk/edit?pli=1#gid=0

# reproduire 

Avec l'appli "Plugin QGIS - Simon" et un l'opérateur géographique "intercte"

1. ajouter la couche KIOSQUES_DE_PRESSE
2. réinitialiser le formulaire
3. sélectionner la couche KIOSQUES_DE_PRESSE dans la liste déroulante "Filtre géographique" --> 178 résultats
4. ajouter la couche ETABLISSEMENTS_SCOLAIRES_COLLEGES
5. réinitialiser le formulaire
6. sélectionner la couche ETABLISSEMENTS_SCOLAIRES_COLLEGES
![image](https://user-images.githubusercontent.com/41120579/175015757-169eba77-c2c9-40b7-95eb-796e2a81ac2f.png)

--> la recherche est comme réinitialisée, d'après les logs, le plugin ne récupère pas l'option sélectionnée par l'utilisateur dans la liste déroulante : 
```
{'datatype': None, 'formats': None, 'owners': None, 'inspire': None, 'groupTheme': None, 'srs': None, 'contacts': None, 'licenses': None, 'geofilter': None, 'favorite': None, 'text': '', 'operation': 'intersects', 'ob': 'relevance', 'od': 'desc', 'keys': []}
```

**Comment by SimonSAMPERE** [comment]
# commentaire de recette

Tester la recherche selon le filtre géographique pour valider que le comportement signalé dans le [guide de recette](https://docs.google.com/spreadsheets/d/1NVfVXIJNysdC9zEwVIRh0G3sOze1xXIBanT1AcBcGkk/edit?pli=1#gid=0) a disparu.
![image](https://user-images.githubusercontent.com/41120579/175091069-aa1e7ff8-4fce-4174-8f95-6845ffdd162f.png)

**Comment by Mouzzi-C** [comment]
## Recette

1. Le choix de la couche ne s'ajoute pas directement à la liste de filtres géographiques. Pour le voir dans la liste, il faut : 
  * ajouter la donnée à la carte ;
  * relancer le résultat de la recherche ;
  * vérifier la liste de filtres géographiques. 
2. La recherche fonctionne bien avec les données vecteur (polygone, point et ligne) mais pas avec du raster. Tests réalisés avec des données vecteurs provenant de la base postgis et de différents services WFS. Le raster ajouté à la carte provenait d'un WMS (donnée zones touristiques internationales)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C le comportement décrit est conforme aux attentes, je le passe donc en checked.
Je vais enrichir la doc en ligne pour y préciser que le moteur de recherche doit être rafraichi pour que les couches soient proposées dans la liste déroulante.

**Comment by Mouzzi-C** [comment]
et pour les données raster c'est normal que ça fonctionne pas ? Si oui, il faudra aussi le préciser dans la doc

**Comment by SimonSAMPERE** [comment]
Yes je vais le rajouter, bien vu.
