### ISSUE TITLE
Plugin version 0.4-beta is approved but not visible in QGIS Extension manager

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#44]
@pcav has approved the new version and it's available on the QGIS plugins website (http://plugins.qgis.org/plugins/isogeo_search_engine/) but it's not available through the QGIS Extension Manager (with experimental channel activated of course).

**Comment by Guts** [comment]
It doesn't appear in the RSS: http://plugins.qgis.org/plugins/plugins.xml

**Comment by pcav** [comment]
True. I suppose this is due to the strange numbering (non numeric), or to wrong metadata.
Please ask the mailing list qgis-dev.

**Comment by Guts** [comment]
>  I suppose this is due to the strange numbering (non numeric), or to wrong metadata.

Strange. We didn't change anything on the semantic versioning style since previous version. Could it be the metadata.txt encoding?

Reported on list qgis-dev: https://lists.osgeo.org/pipermail/qgis-developer/2016-September/044580.html

**Comment by elpaso** [comment]
It might be a problem with latest server updates on plugins.qgis.org , we are aware of the problem and currently trying to address it.

**Comment by elpaso** [comment]
@Guts can you check it now?

**Comment by TheoSinatti** [comment]
The new version is now available in QGIS extension manager. So, whatever you did, it worked.
Thank you for your help !

**Comment by Guts** [comment]
Thanks @elpaso, it works fine!
