### ISSUE TITLE
[MD] Ajustements graphiques

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#448]
- [x] agrandir la taille de la police (demande formulée par Karine Lesage du CD31)
 - [x] rendre les icônes de dates de création/modification de la donnée/métadonnées cohérente avec celles de tri
 - [x] affichage correcte de la période de validité :  
  ![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/41120579/4419ea1d-6a88-4c3d-b663-fc094bae86d4)
  --> passer le commentaire dans une GroupBox dédiée
- [x] passer toutes les groupBoxes à flat
- [x] supprimer les boutons : 
  - [x] OK
  - [x] Fermer
  - [x] télécharger en XML
  - [x] ajout de la donnée
- [x] diminuer les margin et spacing des layouts
- [x] déplacer le bouton "Éditer" dans un VerticalLayout en dessous du menu des onglets
- [x] affichage correcte des informations techniques
  ![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/41120579/f93b2027-0024-49d2-8e03-1d07b11aa319)
  --> tout afficher dans une seule colonne
- [x] retravailler l’icône `cube.svg` pour le rendre carré
- [x] organiser verticalement les groupboxes de l'onglet "Divers"
- [x] supprimer les groupBox, les remplacer par un label + une scrollBarArea dans un QWidget
- [x] ajouter une scrollBar pour le geoContext
- [x] refaire une passe d'i18n

**Comment by SimonSAMPERE** [comment]
# Recette

@Mouzzi-C faut vérifier que les infos s'affichent bien dans la fiche de métadonnées détaillée pour chaque type de fiche

**Comment by Mouzzi-C** [comment]
## recette sur qgis 3.22.7 et 3.28.4

- rasters : ok pour écrans de différentes tailles
- vecteurs : ok pour écrans de différentes tailles. Par contre, le nombre d'entité et le type de gréométrie ne s'affichent pas 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/d584373e-1813-4190-89e1-c52d0cf91103)

[fiche sur app](https://app.isogeo.com/groups/8e02046c031a454690efe71692d25db5/resources/0f15106819244b62a151dc0a0daf4307/geography)

- dtng : ok pour écrans de différentes tailles
- ressources : ok pour écrans de différentes tailles
- services : ok pour écrans de différentes tailles. Par contre, le nombre d'objets s'affiche dans l'onglet géographie
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/3811c6fc-0bdd-4755-b1f4-72b409a92ae5)

**Comment by Mouzzi-C** [comment]
Testé avec qgis 3.22.7 et 3.28.4

C'est bon pour moi. je le passe en checked

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
