### ISSUE TITLE
Display a loading bar when the plugin is working

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#45]
Some operations, like displaying the results, can be long. In this cases, the GUI should show a sign that encourages the user to wait, like this waiting bar : 
![zgpfa](https://cloud.githubusercontent.com/assets/20419317/18469370/45133630-79a8-11e6-8775-8b9b3d5a60b8.jpg)

**Comment by Guts** [comment]
Great!
