### ISSUE TITLE
Fenêtre d'authentification - Supprimer la rubrique "Pas encore de compte ?"

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/isogeo-plugin-qgis#451]
![image](https://user-images.githubusercontent.com/16936198/209646137-a47e396e-172a-4ee9-af08-288f74e7c864.png)

Enlever également la phrase "Il est simple et gratuit...."

**Comment by leodarengosse** [comment]
Retirer également la possibilité de prendre RDV avec la team Isogeo

**Comment by SimonSAMPERE** [comment]
Haha je savais bien que #325 ne durerait pas longtemps...
En gros @leodarengosse il faut supprimer toute la rubrique "Pas encore de compte ?" c'est bien ça ?

**Comment by SimonSAMPERE** [comment]
@leodarengosse tu me confirmes qu'il faut bien supprimer toute la rubrique "Pas encore de compte ?" et les 2 boutons qu'elle contient ?

**Comment by jgrosmaire** [comment]
Si c'est bon pour Léo, la rubrique a bien été enlevée. Par contre dans ma fenêtre par défaut avant de l'agrandir les informations sous coupées. Il est notamment pas possible d'importer un fichier. 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/66669475/e17a0895-cffd-4f97-a051-3637ac534b90)

Avec la version de prod actuelle, tout est affiché et il n'est pas possible de changer la taille de la fenêtre : 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/66669475/1445b678-9e4a-4862-a22a-47bf45218b57)

**Comment by SimonSAMPERE** [comment]
Merci @jgrosmaire jmen occupe
