### ISSUE TITLE
[SUPPORT - COMPA] Certaines données ne sont pas ajoutables à la carte depuis la bdd

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/isogeo-plugin-qgis#452]
La connexion à la Base de donnée est bien configurée dans qgis. La cliente arrive à ajouter certaines données de la BDD mais à un "non ajoutable" pour d'autres. 

Exemple de donnée ajoutable : bati_construction_ponctuelle
Exemple de donnée non ajoutable : troncon_hydrographique

Ces deux données ont été scannées depuis [le même point d'entrée](https://scan.isogeo.com/g/85eae5ea76cb4b58977f1359dff0bd87/entrypoints/62b1c61ebf5114698544eccf/requests/63b83b2e6bb2a478f3e74b67).

Voilà le fichier de [logs](https://github.com/isogeo/isogeo-plugin-qgis/files/10381151/log_isogeo_plugin.log) envoyé par la cliente.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C il semble que l'emplacement de la fiche de métadonnées de la donnée que la cliente n'arrive pas à ajouter ait été modifié : https://app.isogeo.com/groups/85eae5ea76cb4b58977f1359dff0bd87/resources/45d31a1a96a74222b0ad23a0642d744f/identification.
Je ne pense pas que le scan soit à l'origine de la valeur "db_compa.BD_Carthage", a mon avis ça a été modifié manuellement dans app. Le plugin QGIS ne détecte donc pas que la couche est ajoutable puisqu'il ne trouve aucune connexion à la BDD "db_compa.BD_Carthage" configurée dans QGIS, en revanche ça fonctionne sans problème pour les fiches dont l'emplacement est "db_compa" (emplacement d'origine du Scan j'imagine).

Je te laisse en informer la cliente et t'assurer qu'en modifiant l'emplacement de la fiche, la table est bien ajoutable dans le plugin.

**Comment by SimonSAMPERE** [comment]
Il est possible que ça soit le scan qui ait mis cette valeur d'emplacement, il faudrait se renseigner auprès de la cliente car ça pourrait impliquer une nécessité de correction des workbenchs.

**Comment by Mouzzi-C** [comment]
parfait merci man. J'ai envoyé ça à la cliente et j'ai modifié l'emplacement dans la fiche pour que la cliente puisse refaire le test directement. 

J'attends sa réponse pour savoir si ça avait été modifié manuellement ou non. Mais ça serait étonnant que le Scan ait remonté la mauvaise info parce qu'on trouve le bon emplacement dans les autres fiches. Je te teisn au courant

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C je ferme le ticket, rajoute toi dans un doc de penser à checker l'emplacement de la fiche quand ya un soucis d'ajout de table dans le plugin QGIS.
