### ISSUE TITLE
Déclenchement de l'ajout de couche en utilisant la molette

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#455]
Dans le cas où plusieurs option d'ajout sont disponible pour une fiche de métadonnées, une liste déroulante est présente dans la 4ème colonne du tableau d'affichage des résultats pour la ligne correspondante. Si on place le curseur de la souris sur cette liste déroulante et qu'on actionne la molette, certaines options d'ajout de la liste sont activées et des couches sont ajoutées. Aucun problème en revanche pour utiliser la molette après avoir cliqué sur la liste déroulante.

Il faut faire en sorte que seul le clique déclenche l'ajout et donc réussir à exclure l'événement d'utilisation de la molette.

* https://doc.qt.io/qtforpython-6/overviews/eventsandfilters.html
* https://gist.github.com/stevenliebregt/8e4211937b671ac637b610650a11914f
* https://www.pythonguis.com/tutorials/pyqt6-signals-slots-events/

**Comment by SimonSAMPERE** [comment]
# Recette

Il faut vérifier sur les listes déroulantes d'ajout de couche et aussi sur toutes les autres (notamment celles de filtre) qu'utiliser la molette lorsqu'on a le curseur dessus ne déclenche rien mais qu'elle reste utilisable pour scroller une fois la liste déroulante dépliée.

**Comment by Mouzzi-C** [comment]
## recette sur qgis 3.22.7 et 3.28.4

- test réalisé pour les différents liste de filtres : 

1. scroll sans ouvrir la liste ;
2. affichange de la liste ;
3. scroll dans la liste. 

les 3 étapes fonctionnent pour la liste de mots-clés et de thématiques inspire. les autres liste n'ont pas assez de choix pour pouvoir scroller. 

Je n'ai pas pu tester la 3ème étape du test sur les autres listes mais les 2 premières étapes fonctionnaient bien. 

- Liste d'option d'ajout à la carte : la liste s'agrandie à l'infini. Il n'est donc pas possible de scroller

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/864c2b1d-a9ec-400b-94bf-dd09fb8b0868)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C merci amigo, du coup tu me confirmes que quand on a la souri sur la liste déroulante (sans avoir cliqué) et qu'on utilise la molette pour scroller ça n'active pas la liste déroulante ?

**Comment by Mouzzi-C** [comment]
yes je confirme 👍

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
