### ISSUE TITLE
Ajustements graphiques de la fenêtre d'authentification

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#459]
conséquences de #451

**Comment by Mouzzi-C** [comment]
## recette sur qgis 3.22.7 et 3.28.4

1. Affichage initiale et après changement de client_secret (sur petit écran) : 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/3f848bd2-a33c-4881-8e18-f283c0fe686a)

2. passage de la fenêtre sur grand écran : 
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/bf20adc9-508d-4d48-bf4f-c57119d63c30)

3. passage de la fenêtre du grand au petit écran : 
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/ad6c5ee3-9542-4d88-b435-54d08f37ef46)


Même comportment observé dans les deux versions de qgis

**Comment by Mouzzi-C** [comment]
## Recette sur qgis 3.22.7 et 3.28.4

- client_secret valide, sur 2 tailles d'écrans. --> ok
- client_sercet avec faux id sur 2 écrans --> ok
- client_sercet avec secret et id avec uniquement un espace --> ok
- client_sercet avec id et user vides --> affiche un résultat grisé
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/b2c90219-76ba-4ed3-85e3-35fbcb81116a)

@SimonSAMPERE si le dernier point est ok pour toi, c'est bon pour moi 👍

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
