### ISSUE TITLE
Ajustements graphiques de la fenêtre de configuration des connexions BDD

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#460]
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/41120579/205182ba-38be-484b-bd75-b4079cb2c0aa)

**Comment by Mouzzi-C** [comment]
## recette sur qgis 3.22.7 et 3.28.4

la fenêtre n'est pas ajustable mais toutes les inforamtions s'affiche bien. test réalisé sur 2 écran avec les fenêtre de config oracle et postgis

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/d81e4f05-cc21-49d7-a13c-3afea07a039e)

C'est bon pour moi, je le passe en checked.

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
