### ISSUE TITLE
[MD] la couche de l'enveloppe convexe persiste à la fermeture de la boîte de Dialogue

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#461]
La conséquence est que si on veut fermer QGIS après avoir affiché une fiche complète dotée d'une emprise, on a systématiquement cette popup qui apparaît : 
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/41120579/72ce81ee-1def-406c-8f7d-aa0adf61a677)

Il faudrait supprimer la couche en même temps que la fenêtre est fermée.

**Comment by SimonSAMPERE** [comment]
# Recette

Comportement souhaité : si on ouvre une fihce détaillée de type vecteur ou raster et qu'on la ferme, à la fermeture de QGIS la popup n'apparaît pas.

**Comment by Mouzzi-C** [comment]
### recette sur qgis 3.22.7
ça a fonctionné les premières fois puis après quelques tests d'ajout à la carte, d'ouverture de fiches et de sélection d'utilisateur postgis (...), ça a recommencé à afficher le message 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/63340073/9a75fc32-7a15-4546-ae2d-ef26ae9b3987)

Voilà le fichier de [logs.log](https://github.com/isogeo/isogeo-plugin-qgis/files/11879411/log_isogeo_plugin.log)


## recette sur qgis 3.28.4

même compotement observé.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C si t'as fais des tests d'ajout à la carte ça a pu créer des couches temporaires justement. Dans ce ticket je considère que les 2 couches que sont l'enveloppe convexe et le fond carte de l'enveloppe convexe dans la fiche de métadonnées détaillée. Mais si t'as fait d'autres manip qui ont créé des couches temporaires c'est normale que cette popup apparaisse. Donc je considère que c'est good.

**Comment by Mouzzi-C** [comment]
laisse tombé man, j'ai supprimé mon commentaire. j'avais pas la bonne version du plugin. je refait ça et je te tiens au courant

**Comment by Mouzzi-C** [comment]
c'est retesté avec la bonne version du plugin, la 3.4.2-beta 👍 

C'est tout bon. je le passe en checked
