### ISSUE TITLE
Gestion des layers de type "table"

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#462]
- [x] WFS
- [x] ~EFS~
- [x] ~EMS~

Adaptation à ce ticket de l'API : https://github.com/isogeo/isogeo-api/issues/107

A voir si on a des modifications à effectuer mais globalement ça implique de prendre en compte le nouvel attribut `type` des ServiceLayers.

L'ajout d'une table de WFS entraîne une erreur Python : 
```
modules\layer\geo_service.py", line 676, in build_wfs_url
              srs_id = [
             IndexError: list index out of range
```
Pour les EFS ça semble pas fonctionne non plus (même dans QGSI 3.22) : 
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/41120579/daec4e8a-7de9-4d98-98bc-24797d75d98f)

Apparemment QGIS ne permet pas d'ajouter les tables d'EMS ou d'EFS, il faudrait donc ne pas les proposer dans la liste déroulante.

**Comment by SimonSAMPERE** [comment]
@leodarengosse j'ai commencé à me préparer [des métadonnées pour le dev](https://app.isogeo.com/groups/0929bd0968bc4e19a6b58f65bdb4dda8/inventory/search?p=1&ob=%23relevance&od=des&q=keyword%3Aisogeo%3Adev) donc j'ai créé 4 fiches de services pour l'EFS, l'EMS, le WFS et le WMS. J'ai utilisé le service EMS_EFS_WMS_WFS à chaque fois parce qu'il me semble qu'il a des groupe de couches et des "table" de service.

Je me suis rendu compte que les tables ont été créées uniquement dans la [fiche EMS](https://app.isogeo.com/groups/0929bd0968bc4e19a6b58f65bdb4dda8/resources/5cc0939ed50445818237665c8f9cb4df/resources).

Quand je lis le [ticket de l'API](https://github.com/isogeo/isogeo-api/issues/107) je trouve pas à quel endroit on a spécifié les formats de services pouvant diffuser des tables.

Tu peux m'indiquer si c'est un bug on si on veut effectivement gérer les tables de service uniquement pour les services EMS ?

**Comment by SimonSAMPERE** [comment]
# Recette

Vérifier qu'on peut ajouter les tables WFS et EFS avec le plugin Isogeo dans QGIS 3.22 et 3.28.

**Comment by jgrosmaire** [comment]
## Recette

* ça fonctionne bien pour les WFS
* Les tables ne sont pas dans la liste pour les [EFS](https://app.isogeo.com/groups/dfcf38b8ef2a49528dfd4f5a3ebbd47b/resources/4097073cf022461d9d46e4deee7bdde2/identification) avec les deux versions de QGIS (ci dessous différence entre les affichages du même service juste avec le changement des couches en table) : 
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/66669475/59dbc8ca-8dbd-45a0-bde6-3b91de324938)
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/66669475/59eda25b-45c7-4589-841e-f6eb5ce71af4)

**Comment by SimonSAMPERE** [comment]
@jgrosmaire au temps pour moi, je me suis emmêlé les bâtons dans les roues, apparemment QGIS ne propose ni les tables d'EFS ni celles d'EMS.

Le nouveau comportement à tester est donc le suivant : 
* les `layers` de type "table" ne s'affichent pas dans les options d'ajout des fiches EFS
* les `layers` de type "table" ne s'affichent pas dans les options d'ajout des fiches EMS
* les `layers` EFS de type "table" associés à une fiche dataset ne s'affichent pas dans les options d'ajout de cette fiche
* les `layers` EMS de type "table" associés à une fiche dataset ne s'affichent pas dans les options d'ajout de cette fiche

Désolé pour le dérangement.

**Comment by jgrosmaire** [comment]
## Recette

- [x] les `layers` de type "table" ne s'affichent pas dans les options d'ajout des fiches EFS
- [x] les `layers` de type "table" ne s'affichent pas dans les options d'ajout des fiches EMS
- [x] les `layers` EFS de type "table" associés à une fiche dataset ne s'affichent pas dans les options d'ajout de cette fiche
- [x] les `layers` EMS de type "table" associés à une fiche dataset ne s'affichent pas dans les options d'ajout de cette fiche

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
