### ISSUE TITLE
Authentification aux EFS et EMS privés

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/isogeo-plugin-qgis#467]
J'ai découvert lors d'un atelier plugin avec la MAMP qu'il était possible d'ajouter à la carte les services Esri soumis à une authentification dans QGIS. 

Pour cela, il faut configurer dans les paramètres de QGIS / authentification une entrée d'authentification OAuth2 (cf. capture ci-dessous).

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/16936198/9af2f2b2-31e1-4ef5-b9ce-788b7f376441)

La question est donc de savoir s'il est possible de récupérer dans QGIS le token d'authentification pour l'ajouter à la requête qui demande l'ajout du service à la carte. 

Cela nous permettrait de gérer dans le plugin QGIS l'ajout des services privés et qu'il soit acheté par la MAMP au passage.

Pour le moment ça ne fonctionne pas sur mon poste mais on est censé pouvoir y arriver avec nos comptes Presta @SimonSAMPERE. J'organiserai un atelier spécifique sur le paramétrage dans nos QGIS pour qu'on puisse tester.

**Comment by leodarengosse** [comment]
J'ai trouvé de la [doc officielle](https://plugins.qgis.org/planet/tag/oauth2/) à ce sujet, je vais essayer de le mettre en place avec notre portal.

**Comment by SimonSAMPERE** [comment]
@leodarengosse c'est une bonne chose que ça soit gérable en théorie, si on arrive à le configurer en interne je pourrai faire des tests, voir si c'est techniquement réalisable et envisager un chiffrage. En tous cas ça ne sera pas anodin comme fonctionnalité étant donné le code impliqué.

**Comment by SimonSAMPERE** [comment]
+ checker pour Geoserver même si ya pas chez client ça pourrait être l'occas de faire d'une pierre 2 coups

**Comment by leodarengosse** [comment]
J'ai désactivé IIS sur mon poste en faisant les étapes indiquées par le gars + powershell  https://learn.microsoft.com/en-us/answers/questions/40665/how-to-uninstall-disable-iis-on-windows-10

**Comment by leodarengosse** [comment]
En fait c'est Anydesk qui ecoute sur le port 7070 et qui bloque. Il faut donc aller dans les paramètres de Anydesk et changer de port par défaut :

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/16936198/af296eb1-0379-419e-890a-9fa96633297f)

**Comment by SimonSAMPERE** [comment]
https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/authentication.html

**Comment by SimonSAMPERE** [comment]
Il faudrait déjà réussir avec un script Python à ajouter une couche de services privé ESRI auquel l'authentification a été configurée dans QGIS.

**Comment by SimonSAMPERE** [comment]
Il semble y avoir un problème avec l'outil de débogage/développement, si la case "Désactiver le cache" n'est pas cochée, l'ajout de couches de services ESRI Privé depuis le plugin QGIS ne fonctionne pas

**Comment by SimonSAMPERE** [comment]
Une étape consistera à fouiller dans les QSettings pour récupérer les différentes connexions OAuth2 utilisées pour se connecter à un serveur ESRI. Donc dans `connexion/argisfeatureserver/items` on trouve la liste des connexions à des ArcGIS Server sous forme de sous-dossiers contenant notamment : 
* l'URL du serveur `connexion/argisfeatureserver/items/<nom>/url`
* l'identifiant de la connexion utilisée pour s'y connecter `connexion/argisfeatureserver/items/<nom>/authcfg`

Il faudrait donc extraire des QSettings ces infos pour pouvoir déterminer, au moment où l'utilisateur souhaite ajouter une couche de services EFS ou EMS, si on a un `authcfg` qui correspond à l'URL du service et qui pourra être utilisé pour que le plugin QGIS interagisse avec.

Le **`SettingsManager`** sera en charge d'extraire ces infos des QSettings et de les rendre disponibles au **`GeoServiceManager`** et éventuellement au **`LayerAdder`**. A priori, pas besoin de passer l'info au **`LayerAdder`**, le **`GeoServiceManager`** pourra se charger d'ajouter le paramètre `authcfg` à l'URL de la couche.

**Comment by SimonSAMPERE** [comment]
La faisabilité technique n'est pas 100% établie selon moi, mais je ferai un premier chiffrage approximatif à 5 jours de travaille. Sans compter d'éventuelles échanges avec les futurs utilisateurs de la MAMP pour valider leur expérience.

**Comment by SimonSAMPERE** [comment]
@leodarengosse suite à mes derniers tests, j'ai pu établir la faisabilité technique pour les EMS et les EFS avec le service Isogeo.

Faut-il également faire des tests avec les WMS et WFS issus d'ArcGIS Server ?

**Comment by SimonSAMPERE** [comment]
la branche `3.6.0` a été créée et contient notamment les modifications du code source effectuées au cours du chiffrage

**Comment by leodarengosse** [comment]
> Faut-il également faire des tests avec les WMS et WFS issus d'ArcGIS Server ? oui mais ce n'est pas prioritaire

**Comment by SimonSAMPERE** [comment]
Toujours 8 jours @leodarengosse

**Comment by SimonSAMPERE** [comment]
# SPET

Ajouter dans le **`SettingsManager`** la récupération des connexions enregistrées dans `connexion/argisfeatureserver/items/<nom>/authcfg`. Attention, le folder `connnexion` peut changer de nom selon la langue de QGIS. Stocker dans une propriété du **`SettingsManager`** `authcfg` et `url` de chaque connexion : 
```python
afs_connections = {
    "connection_name" : {
        "url": "service_url",
        "authcfg": "authcfg_id"
    }
}
```

Dans la méthode *`check_esri_service`* du **`GeoServiceManager`**, récupérer l'info dans le **`SettingsManager`** de s'il existe une connexion ArcGISFeatureServer pour le service testé. Si elle existe, faire la requête *GetCapabilitites* avec le bout de code suivant : 
```python
qnam = QgsNetworkAccessManager.instance()
request = QNetworkRequest(QUrl(service_dict["getCap_url"]))
reply = qnam.blockingGet(request, "authcfg_id")

reply_content_str = reply.content().data().decode("utf8")
reply_content_json = json.loads(reply_content_str)

getCap_content = reply_content_json
service_dict["reachable"] = 1

del qnam
```

Toujours dans la méthode *`check_esri_service`* du **`GeoServiceManager`**, si la requête *GetCapabilitites*  a fonctionné en utilisant le `authcfg`, stocker l'info dans le `service_dict`.

Dans les méthodes *`build_efs_url`* et *`build_ems_url`* du **`GeoServiceManager`**, récupérer l'info dans le `service_dict` et ajouter le paramètre `authcfg` à l'URL. De cette manière yaura potentiellement rien à gérer côté LayerAdder à part le vidage du cache avec `QgsNetworkAccessManager.instance().cache().clear()`

**Comment by SimonSAMPERE** [comment]
Comportement actuellement développé : 

Le plugin QGIS inspecte toutes les connexions à des Serveurs ArcGIS REST et garde en mémoire, pour les connexions qui ont une Authentification configurée : 
* nom de la connexion
* url
* identifiant de l'authentification

Au moment d'ajouter une couche de service, le plugin cherche dans les connexions gardées en mémoire s'il y en a une configurée pour une URL qui correspond à celle du service dont on veut ajouter une couche, si c'est le cas, il récupère l'identifiant de l'authentification et s'en sert pour requêter le service.

**Comment by SimonSAMPERE** [comment]
@leodarengosse je pense que tu peux déjà recetter ce comportement, avec une authentification OAuth2 différente si possible.

Si le comportement te semble satisfaisant, on pourra ensuite lancer des échanges avec la MAMP et leur envoyer une version bêta pour qu'ils puissent tester et valider que ça répond à leurs besoins.

**Comment by SimonSAMPERE** [comment]
@leodarengosse, voici la version à installer pour faire le test :
[isogeo_search_engine.zip](https://github.com/user-attachments/files/16009708/isogeo_search_engine.zip)

**Comment by SimonSAMPERE** [comment]
Possibilité de contacter directement Céline de la MAMP pour organiser un test avec elle

**Comment by leodarengosse** [comment]
Test avec les données de la MAMP 

![image](https://github.com/user-attachments/assets/28db85f6-a6ee-4d56-a611-967c2393e0a5)

Pourtant, j'ai bien accès à la couche du service via l'explorateur QGIS

**Comment by SimonSAMPERE** [comment]
@leodarengosse le zip de mon précédent commentaire semble effectivement incorrecte, essaye avec celui-ci : 
[isogeo_search_engine.zip](https://github.com/user-attachments/files/16192286/isogeo_search_engine.zip)

**Comment by leodarengosse** [comment]
Toujours le même message malheureusement 

![image](https://github.com/user-attachments/assets/fe8cf09d-efc2-4a35-861d-7d015d33a371)

**Comment by SimonSAMPERE** [comment]
BIS - @leodarengosse peux-tu réessayer avec la version ci-dessous stp ?
[isogeo_search_engine.zip](https://github.com/user-attachments/files/16194490/isogeo_search_engine.zip)

**Comment by leodarengosse** [comment]
## Recette 

- [ ] EMS couches vectorielles
- [ ] EFS
  - [ ] couches vectorielles
  - [ ] tables 
![image](https://github.com/user-attachments/assets/3d0b7996-0da1-4a8e-a14b-39fedffe7e85)

**Comment by SimonSAMPERE** [comment]
@leodarengosse est-ce que la table est ajoutable nativement dans QGIS ?

**Comment by SimonSAMPERE** [comment]
Version testée à la MAMP le 16/07/2024 : 
[isogeo_search_engine.zip](https://github.com/user-attachments/files/16244890/isogeo_search_engine.zip)

**Comment by SimonSAMPERE** [comment]
Le test s'est bien déroulé, RAS concernant la fonctionnalité mais un bug détecté (#485 )

@leodarengosse est-ce qu'on aurait une table EFS dans nos services privés internes ?

**Comment by SimonSAMPERE** [comment]
J'ai créé ce ticket pour les tables : https://github.com/isogeo/isogeo-plugin-qgis/issues/486
