### ISSUE TITLE
Results can't be sorted

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#47]
It should be possible for research results to be sorted by : 

- [x] Title
- [x] Data creation date
- [x] Data last modification date
- [x] Metadata creation date
- [x] Metadata last modification date
- [x] Relevance

**Comment by Guts** [comment]
Add 2 elements near the results display button:

- one to pick the order/sort option (combobox)
- another one to choose (alternate?) the order direction: ascending or descending

**Comment by TheoSinatti** [comment]
@Guts To be tested, and closed.
