### ISSUE TITLE
[SUPPORT - CD 94] Impossible d'ajouter à la carte des couches ayant plusieurs types d'objets

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/isogeo-plugin-qgis#470]
Impossible d'ajouter à la carte des couches ayant plusieurs types d'objets. La cliente a testé l'ajout depuis QGIS directement et ça fonctionne. 

[log_isogeo_plugin (1).zip](https://github.com/isogeo/isogeo-plugin-qgis/files/13632906/log_isogeo_plugin.1.zip)

Je vais voir avec la cliente si elle peut nous envoyer la donnée

**Comment by SimonSAMPERE** [comment]
http://www.postgis.fr/chrome/site/docs/workshop-foss4g/doc/geometries.html

**Comment by SimonSAMPERE** [comment]
J'ai créé une donnée contenu plusieurs types de géométrie dans le schema sample de la base PostGIS interne, je l'ai appelé "multigeom_2154" (comme celle de la base Oracle).

J'ai fait le test et quand j'essaye de l'ajouter à la carte à partir du plugin ça génère effectivement une erreur. QGIS ne gère pas les couches avec des entités géométriques de plusieurs types différents. C'est pourquoi quand je passe directement pas la fonctionnalité d'ajout de couches de QGIS, ma table est splittée en plusieurs couches (une par type de géométrie) : 
![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/41120579/12eb37fd-63c2-4c85-b1b7-fee34b19e265)

A priori il faudrait que je développe la même chose que pour Oracle, c'est à dire qu'on détecte si la table à des entités géo de différents types et si c'est le cas on ajoute une couche par type de géométrie.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C  tu peux dire à Catherine que j'ai investigué sur le sujet, qu'actuellement ça n'est tout simplement pas gérer dans le plugin QGIS et qu'il faut encore que je fasse les SPET et le chiffrage. Aussi, je suis carrément preneur pour le fichier de Geofit qu'elle évoque dans son mail mais que j'ai l'impression qu'elle a oublié de le mettre en PJ.

**Comment by SimonSAMPERE** [comment]
Après avoir étudié le fichier envoyé par le CD94 il apparaît que les interactions avec les bases de données sont gérées tellement différemment que ce code n'aidera pas.

Actuellement, pour les tables Oracle, la gestion des types de géométrie multiples se fait au moment de l'ajout de la couche, dans la méthode `add_from_ora_database` du module `LayerAdder`. Je vais donc ajouter cette gestion pour les tables PostGIS dans la méthode `add_from_pg_database` du même module.

Ça nécessite de modifier les méthodes suivantes : 
* `add_from_pg_database` du  `LayerAdder` (fichier `add_layer.py`)
* `establish_postgis_connection` du  `DataBaseManager` (fichier `database.py`)
* `show_results` du  `ResultsManager` (fichier `display.py`)

**Comment by SimonSAMPERE** [comment]
# Recette

> Ne fonctionne pas dans QGIS < 3.16 mais a priori le client utilise QGIS 3.28 donc pas de soucis

En plus de s'assurer que l'ajout d'une table PostGIS comportant plusieurs types de géométrie entraîne bien l'ajout d'une couche par type de géométrie (comportement similaire au Table Oracle Spatial comportant plusieurs type de géométrie), il faudra s'assurer que l'ajout des données PostGIS suivantes fonctionne toujours : 
* tables avec géométrie
* DTNG
* vues
* vues dynamiques

**Comment by jgrosmaire** [comment]
J'ai refait un test ce matin avec une nouvelle vue. Je pense qu'il y avait un problème avec celle utilisée mercredi mais je ne sais pas pourquoi : 

Cette nouvelle vue s'affiche correctement dans QGIS directement : 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/66669475/704ef42e-8938-42b9-b6f1-43557faa158f)

Mais deux fois la même couche (seulement couche ponctuelle) en passant par le plugin : 

![image](https://github.com/isogeo/isogeo-plugin-qgis/assets/66669475/93bca919-7fc4-46c9-b5b6-8ee2f5dda41b)

**Comment by SimonSAMPERE** [comment]
Merci @jgrosmaire effectivement je me rend compte grâce à ton retour que je n'avais pas du tout pensé à tester les vues comportant des entités aux types de géométrie variés. My bad 🙏🏼 

Je vais investiguer, corriger et je te dirai quand tu pourras reprendre la recette.

**Comment by SimonSAMPERE** [comment]
Ça concerne les vues et les vues matérialisées. Le plugin ajoute une couche par type de géométrie mais toujours une couche ponctuelle

**Comment by SimonSAMPERE** [comment]
@jgrosmaire j'ai fini de traiter tes retours et remis en QA le plugin QGIS. Pas besoin de recetter pour Oracle mais tu peux reprendre la recette pour Postgres. Idéalement il faudrait tester des tables, des vues et des vues matérialisées dans les configurations suivantes : 
* seulement des points
* seulement des lignes
* seulement des polygones
* 2 ou 3 types "simples" différents (points et lignes ou points et polygones ou points lignes et polygones...)
* le type "simple" et son type "multi" (points et multipoints, lignes et multilignes, polygones et multipolygones) --> le comportement attendu est que toutes les entités soient rassemblées dans une même couche car QGIS parvient à le gérer
* 3 ou 4 types "simples" et "multiples" différents (points et multipoints et lignes ou points et polygones et multipolygones  ou points, lignes, multilignes et polygones...) --> comme susmentionné, le comportement attendu est d'avoir une même couche pour les points et multipoints, pour les lignes et multilignes, pour les polygones et multipolygones

Dis-moi si tu as besoin de plus d'infos

**Comment by jgrosmaire** [comment]
**Combinaisons testées** (P = Point, Poly = Polygone, L = Ligne) : 
|       Combinaisons testées        | P  | L  | Poly | P + Poly | L+ Poly | P+ L + Poly | P + MultiP | Poly + MultiPoly | L + MultiL | P + MultiP + MultiPoly + L | P + MultiPoly + MultiL + MultiP | P + MultiP + L + MultiL + Poly + MultiPoly |
| ---------------- | -- | -- | ---- | -------- | ------- | ----------- | ---------- | ---------------- | ---------- | -------------------------- | ---------------------------     | ------------------------------------------ |
| Nom    `{type}_recette_{?}`          | t1 | t2 | t3   | t4_pp    | t4_ lp  | t4_ppl      | t5_p1      | t5_p2            | t5_l       | t6_1                       | t6_2                            | t6_3                                       |
| Table            | Ok | Ok | Ok   | Ok       | Ok      | Ok          | Ok         | Ok               | Ok         | Ok                         | Ok                              | Ok                                         |
| Vue              | Ok | Ok | Ok   | Ok       | Ok      | Ok          | Ok         | Ok               | Ok         | Ok                         | Ok                              | Ok                                         |
| Vue matérialisée | Ok | Ok | Ok   | Ok       | Ok      | Ok          | Ok         | Ok               | Ok         | Ok                         | Ok                              | Ok                                         |


Comme QGIS, les _GeometryCollection_ ne sont pas gérées.

**Comment by SimonSAMPERE** [comment]
Nickel @jgrosmaire , merci beaucoup !

**Comment by SimonSAMPERE** [comment]
https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/3.5.0
