### ISSUE TITLE
Plugin is in English unless you force French

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#48]
When you open the plug-in for the first time, the interface is in English, yet QGis is in French. To switch the plug- in French you have to force the nationality of the system in the Menu Preferences > Option > Languages then close and open QGis

**Comment by Guts** [comment]
related to #31

**Comment by Guts** [comment]
This is not a plugin bug.
It's related to QGIS and Operating System (could you precise the versions?).

Nevertheless, we'll try something :).
