### ISSUE TITLE
Mettre en place la pérennité du contenu du db_connections.json en cas de mise à jour

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#487]
Suite à une sollicitation du support par le CD94 qui a constaté en mettant à jour le plugin que le fichier `db_connections.json` avait été supprimé, coupant l'accès à leur BDD et les empêchant d'ajouter des données.

Ce sujet est très lié à #258 : lors d'une mise à jour, tout le répertoire d'installation du plugin est supprimé avant d'être re-rempli avec les fichiers de la nouvelle version. Donc le fichier `db_connections.json` a été supprimé et quand on le plugin a été lancé, il a constaté qu'il n'y avait pas de fichier et en a recréé un vierge. Pour que cela n'arrive pas, il faudrait (comme avec le fichier `quicksearches.json`) enregistrer le contenu du fichier `db_connections.json` dans les QSettings. De cette manière, en cas d'absence du fichier, le plugin pourrait en recréer un qui soit rempli avec les infos stockées dans les QSettings.

Un point est organisé le 04/09/2024 avec les utilisateurs et utilisatrices du CD94 pour : 

* expliquer le problème
* demander pourquoi ça leur pose problème de recréer le fichier `db_connections.json` étant donnée leur méthode de déploiement
* demander si la solution peut convenir, si c'est OK pour stocker des mdp de BDD dans les QSettings de QGIS
* expliquer que si cette solution est adoptée, la mise à jour vers la prochaine version 3.6.1 supprimera également le fichier `db_connections.json` mais qu'à partir de cette version les mises à jour du plugin n'occasionneront plus ce problème

(@Mouzzi-C je t'assigne juste pour que tu aies les notifs)

**Comment by SimonSAMPERE** [comment]
# SPET

- prépondérance du contenu du fichier `db_connections.json` sur les *`QSettings`* `isogeo/user/db_connections`
- pas de modifications du contenu du fichier `db_connections.json` par l'utilisateur via le plugin (à l'inverse des *quicksearches*)
- recours aux *`QSettings`* après chargement du contenu du fichier `isogeo/user/db_connections` pour :
  - y récupérer les infos
  - y écrire des infos après le merge des contenus des *`QSettings`* et du fichier

- [ ] ajout méthodes au **`SettingsManager`** :
  - [ ] *`load_db_connections_from_json`*
  - [ ] *`load_db_connections_from_qsettings`*
  - [ ] *`merge_db_connections`*
  - [ ] *`write_db_connections_qsettings`* *seulement si nécessaire*
  - [ ] *`update_db_connections_qsettings`*
- [ ] modification de la méthode *`load_db_connections`* du **`SettingsManager`**

**Comment by SimonSAMPERE** [comment]
# Point du 04/09/2024 avec le CD94 avec @Mouzzi-C 

## Ce que @SimonSAMPERE a compris de nouveau sur le Centre Logiciel du CD94

Le Package de QGIS déployé dans le centre logiciel est généré par la DSI à partir des ressources fournies par Stéphanie :

* l'exécutable `.msi` d'installation d'une version spécifique de QGIS (directement récupéré sur le site Internet)
* les fichiers qui composent les différents modules, dont le module Isogeo

Le déploiement sur le poste d'un utilisateur peut se faire via une action volontaire de sa part sans qu'on le sache. Donc pas moyen d'avoir la liste des utilisateurs qui ont mis à jour QGIS. D'autre part, les utilisateurs ont la possibilité de mettre à jour le plugin directement sur leur poste via le gestionnaire des extensions, là encore pas moyen d'avoir la liste des utilisateurs qui ont mis à jour le plugin Isogeo.

Mais il est également possible de demander à la DSI de déployer de manière automatique une nouvelle version de QGIS (et de ses modules) sur le poste de tous les utilisateurs.

## Ce qui a été décidé pour la suite

Le développement décrit [ici](https://github.com/isogeo/isogeo-plugin-qgis/issues/487#issuecomment-2326657014) est la seule manière de s'assurer qu'un utilisateur de QGIS du CD94 qui mettrait à jour le plugin Isogeo sur son poste ne perde pas la connexion à la BDD.

En attendant la publication de la version 3.6.1 du plugin qui comprendra ce développement, il est conseillé de redéployer automatiquement la dernière version du plugin Isogeo (avec le fichier `db_connections.json` correctement rempli) pour être sur que tous les utilisateurs ont bien la possibilité d'ajouter les données de la BDD via le plugin Isogeo. A priori, un déploiement de QGIS 3.34 est prévu prochainement et il serait possible de faire d'une pierre deux coups.

Une fois la version 3.6.1 publiée, il faudra refaire un déploiement automatique généralisé de QGIS comprenant cette nouvelle version du plugin et un fichier `db_connections.json` correctement rempli. Lorsque l'utilisateur lancera cette nouvelle version du plugin Isogeo, le contenu du fichier `db_connections.json` sera "sauvegardé" dans les *settings* de QGIS. Lors d'une mise à jour du plugin Isogeo, même si le fichier `db_connections.json` sera vidé, le plugin pourra récupérer les informations qu'il renfermait dans les *settings* de QGIS et ainsi établir la connexion à la BDD.

Néanmoins, il serait préférable, à chaque déploiement d'une nouvelle version de QGIS dans le centre logiciel, de veiller à ce que le fichier `db_connections.json` correctement rempli soit présent dans le dossier `_user` du module Isogeo. Il me semble que c'est la seule manière de s'assurer qu'un nouvel utilisateur puisse bénéficier de la connexion à la base de données. De même pour le fichier d'authentification `client_secrets.json` dans le dossier `_auth` du module Isogeo pour s'assurer que le module installé chez les nouveaux utilisateurs puisse s'authentifier à l'API Isogeo et donc être fonctionnel.

**Comment by SimonSAMPERE** [comment]
Pour info, sur mon poste, les settings de QGIS s'enregistre dans un fichier `QGIS3.ini` qui se trouve dans le dossier `C:\Users\SimonSAMPERE\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS`

Voici un code à exécuter dans la console Python de QGIS pour obtenir l'information : 
```python
from qgis.PyQt.QtCore import QSettings

qsettings = QSettings()

print(qsettings.fileName())
```

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C pour info, comme vu avec @leodarengosse ça sera pas avant octobre cette évolution
Mais du coup vu qu'il peuvent forcer la mise à jour de QGIS embarquant la dernière version du plugin avec un `db_connections.json` correctement rempli ils sont pas bloqués.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C la version 3.6.1 comprenant notamment l'évolution décrite dans ce ticket est prête à être déployées (la version est déjà disponible en expérimentale).

Il faudrait relancer le CD94 pour les prévenir et qu'elles se préparent à refaire un déploiement automatique généralisé de QGIS comprenant cette nouvelle version 3.6.1 du plugin **et un fichier `db_connections.json`** correctement rempli. Pour rappel :
> Lorsque l'utilisateur lancera cette nouvelle version du plugin Isogeo, le contenu du fichier `db_connections.json` sera "sauvegardé" dans les *settings* de QGIS. Lors d'une mise à jour du plugin Isogeo vers une version supérieure à 3.6.1, même si le fichier `db_connections.json` sera vidé, le plugin pourra récupérer les informations qu'il renfermait dans les *settings* de QGIS et ainsi établir la connexion à la BDD.

*voir [ce commentaire](https://github.com/isogeo/isogeo-plugin-qgis/issues/487#issuecomment-2328558666)*

De cette manière, à l'avenir : 
* elles n'auront plus besoin de déployer le plugin avec le fichier `db_connections.json`
* lorsqu'un utilisateur mettra à jour le plugin de son propre chef, il ne perdra pas la connexion à la base de données

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C est-ce que tu as pu prendre connaissance de mon message ci-dessus ? En fait c'était pas claire mais j'attends que le CD94 soit informé avant de publier la version 3.6.1 du plugin pour éviter qu'un de leurs utilisateurs ne mette à jour son plugin Isogeo de son côté et perde sa connexion à leur BDD.

**Comment by leodarengosse** [comment]
J'ai pris le relais en envoyant le mail au client car il faudrait qu'ils testent rapidement avant la mise en Prod pour EGIS. J'ai repris l'échange de mail initial.

**Comment by SimonSAMPERE** [comment]
no soucy @Mouzzi-C 

La version 3.6.1 du plugin comprenant l'enregistrement du contenu du fichier `db_connections.json` dans les *settings* de QGIS et la récupération du contenu du fichier `db_connections.json` depuis les *settings* de QGIS dans le cas où le fichier serait vide au lancement du plugin (par exemple juste après une mise à jour ou une installation du plugin) a été soumise à l'approbation du staff de QGIS à l'instant
