### ISSUE TITLE
Add 2 buttons for make beta test easier

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#6]
In order to make betatesters report easier, it should be a good idea to add 2 buttons up to the UI:

- one to report a bug linkng to this repository issues page
- a second to write a preformatted mail to projets+qgis@isogeo.fr to request a feature

**Comment by TheoSinatti** [comment]
After discussion, we agreed that one button pointing to the bug tracker was enough.
And it's done.
1821f5f86eb119edad6b4a113943516e86af352b
