### ISSUE TITLE
Geographical filter into a combobox

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#61]
- [x] delete the collapisble frame
- [x] insert the geographical option as a combobox in the "Advanced search" collapsible frame
- [ ] combobox includes geographical options: none, #9, #10 and QGIS bookmarks
- [x] move geographical operation option to settings tab ( #53 )

**Comment by TheoSinatti** [comment]
@Guts To be tested and closed.

**Comment by Guts** [comment]
>  combobox includes geographical options: none, #9, #10 and QGIS bookmarks
Will be done in version 1.5
