### ISSUE TITLE
Recast detailed metadata sheet

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#64]
For now, the detailed metadata sheet is working but not well designed. See: #34 and #65.

Solution:
- implement a window with different horizontal tabs (or menu)
- above tabs list, add buttons to: add to the map and edit on Isogeo
- tabs:
  - General: abstract, title, path, type, keywords, INSPIRE themes and technical informations
  - Attributes
  - Contacts
  - History
  - Geography: only if QGIS allows to easily display an envelope on static map
  - CGUs, limitations and quality
  - Metadata (language, date)

Quick OSM example:

![image](https://cloud.githubusercontent.com/assets/1596222/18557127/f7943edc-7b6d-11e6-84b1-3f1ae87f47ba.png)

**Comment by Guts** [comment]
Set the window title from the metadata title ([here](https://github.com/isogeo/isogeo-plugin-qgis/blob/master/isogeo.py#L1904-L1906)):

```python
self.IsogeoMdDetails.setWindowTitle("{} - {}".format(self.tr(u"Isogeo Metadata"), title))
```

Take care about title encoding...

**Comment by vblanlot** [comment]
Décisions :
La fiche de métadonnée doit être consultable dans une fenêtre indépendante composée de plusieurs onglets. A partir de cette fiche, l'utilisateur doit pouvoir ajouter la donnée à sa carte.
Si une métadonnée n'est pas disponible indiquer "Non renseigner"

Composition de la fenêtre :
* 1 titre égal à "Fiche de métadonnée" + [Titre de la fiche]
* 7 onglets verticaux disponibles à gauche, chacun composé d'une icône issue d'Isogeo et d'un titre
* 1 action "Ajouter à la carte" toujours disponible en bas à gauche 

Organisation et contenu des menus : 
1. général : titre, résumé, mots-clés, thème Inspire, format, systèmes de coordonnées
2. attributs : liste (nom, type, description)
3. contacts : rôle, nom, organisation, mail (mailto), téléphone, adresse
4. historique : date de création, date de modification, période de validité, fréquence de mise à jour, contexte de collecte, méthode de collecte
5. géographie : géométrie, nombre d'entité, systémes de coordonnées, emprise sur une carte
6. cgu : conditions, limitations
7. métadonnées : date de mise à jour, langue, point de contact, export XML ISO 19139

Actions :
* Ajouter (ajouter la donnée à la carte) est toujours disponible en bas à gauche de la fenêtre
* Exporter (exporter la fiche au format XML ISO 19139) est disponible dans l'onglet "métadonnées"

Nb : l'action editer la fiche de métadonnée ne sera pas proposée car il est impossible de connaitre les droits d'édition de l'utilisateur sur la fiche consultée

**Comment by Guts** [comment]
@vblanlot : tu peux éditer ton commentaire et déposer les dessins à l'endroit stp ? :)

**Comment by vblanlot** [comment]
Les images sont à l'endroit lorsque tu les ouvres

**Comment by vblanlot** [comment]
Après vérification sur la version 1.5 bêta 2 et sur la fiche "Attractions - Disneyland Paris" voici mes remarques :

- L'interface n'est pas traduite en français
- Le bouton "ajouter à la carte" est absent
- Dans l'onglet "Contact" si un contact n'a pas de mail, un hyperlien (mailto) est tout de même affiché
- Dans l'onglet "Historique" le commentaire sur la période de validité n'est pas affiché
- Dans l'onglet "Géographie" les informations suivantes ne sont pas affichées : nombre d'entités, type de géométrie, echelle, réolution et emprise
- Dans l'onglet "Avancé" l'export XML ne fonctionne pas

En bas au centre de la fenêtre apparaît un bouton "Add button"

**Comment by Guts** [comment]
> Après vérification sur la version 1.5 bêta 2 
La dernière version bêta et celle servant de recette est la [1.5 beta 3](https://github.com/isogeo/isogeo-plugin-qgis/releases/tag/v1.5-beta3)...

**Comment by vblanlot** [comment]
> La dernière version bêta et celle servant de recette est la 1.5 beta 3... 
Mise à jour 👍 

Corrigé :
> L'interface n'est pas traduite en français
> Dans l'onglet "Géographie" les informations suivantes ne sont pas affichées : nombre d'entités, type de géométrie, échelle, résolution et emprise
> En bas au centre de la fenêtre apparaît un bouton "Add button"

A corriger / a implémenter :
- Ajouter le bouton "ajouter à la carte" est absent
- Dans l'onglet "Contact" si un contact n'a pas de mail, un hyperlien (mailto) est tout de même affiché
- Dans l'onglet "Historique" le commentaire sur la période de validité n'est pas affiché
- Dans l'onglet "Avancé" l'export XML ne fonctionne pas
- Lors de l'ouverture de la fenêtre, l'onglet affiché par défaut n'est pas activé
- Dans l'onglet "Divers" la date de modification est rognée (pour plus de clarté et d'homogénéité, il serait pertinent d'appliquer aux dates, la charte graphique utilisée dans l'onglet "historique"
- Le bouton "Editer sur Isogeo" ouvre deux fois la fiche dans le navigateur. De plus cette action n'a pas la forme d'un bouton

**Comment by Guts** [comment]
> Dans l'onglet "Avancé" l'export XML ne fonctionne pas

Reporté. Faire une issue dédiée.

**Comment by Guts** [comment]
>  Lors de l'ouverture de la fenêtre, l'onglet affiché par défaut n'est pas activé

Pas compris.

**Comment by Guts** [comment]
Et sinon @vblanlot on n'affiche pas les infos qualité ?

**Comment by vblanlot** [comment]
Après vérification sur la version 1.5 bêta 4, dans l'application "Plugin QGIS - Dév" et sur la fiche "Attractions - Disneyland Paris" voici mes remarques :

- Dans l'onglet "Géométrie" les informations suivantes ne sont pas affichées : type de géométrie, nombre d'entités, format, systèmes de coordonnées, échelle et résolution

- Dans l'onglet"Géométrie" le terme qualité n'est pas traduit en français
![geometrie](https://cloud.githubusercontent.com/assets/14051239/25520566/a059acca-2bfc-11e7-943c-e7baf115746c.PNG)

- Dans l'onglet "Géométrie" lorsque le nom de la spécification dépasse un certain nombre de caractères il est rogné et la conformité n'est pas visible (test réalisé sur la fiche "Service de téléchargement direct (WFS) des jeux de données des réseaux routiers du département de la Mayenne"
![qualite](https://cloud.githubusercontent.com/assets/14051239/25520525/84630476-2bfc-11e7-9a2d-ab1bec8a722c.PNG)

- Dans l'onglet "Licence" quand une limitation légale liée à Inspire et affiché, le terme "Tea" s'affiche systématiquement
![licences](https://cloud.githubusercontent.com/assets/14051239/25520556/95656e9e-2bfc-11e7-8490-ab2f8805ed83.PNG)
