### ISSUE TITLE
Plugin doesn't load ecw file

### ISSUE THREAD

**Issue by smavd** [isogeo/isogeo-plugin-qgis#68]
It's not possible to load ecw file from the plugin. ecw files can be load with the regular way
![prb_ecw](https://cloud.githubusercontent.com/assets/20684784/18637082/8aab28b4-7e8b-11e6-8034-abd9dac30d93.JPG)

**Comment by Guts** [comment]
You're not using the correct version.
Wait for the plugin validation please.
