### ISSUE TITLE
QGIS crashes with minidump - layer extent filter

### ISSUE THREAD

**Issue by TheoSinatti** [isogeo/isogeo-plugin-qgis#77]
- A layer is chosen to set the extent of the search
- The layer is removed
- A new search is launched with still the layer chosen in the geographical filter combobox
- Plugin crashes

The layer doesn't exist anymore, so this is a bad use of the plugin, but still, it shouldn't crash the whole application.

**Comment by Guts** [comment]
Plugin freezes too with an existing layer.

![2016-10-24 26](https://cloud.githubusercontent.com/assets/1596222/19651933/2d029ae0-9a0f-11e6-8cb5-207ef7f2dfa4.png)

**Comment by vblanlot** [comment]
Le plugin crash tjs

**Comment by Guts** [comment]
En effet, puisque corrigé après la distribution de la 1.5 beta 3 : https://github.com/isogeo/isogeo-plugin-qgis/compare/v1.5-beta3...master

Sera donc dans la beta 4... :)
