### ISSUE TITLE
Add a WMTS to the map canvas

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#79]
WMS and WFS services can be "easily" added through the PyQGIS API but it's more difficult to add WMTS.

Inherited from #16.

**Comment by vblanlot** [comment]
Quand je recherche les services WMTS disponibles, une erreur python survient.
Test effectué sur la version en développement avec l'application Plugin QGIS - Dév

Pour reproduire :

1. rechercher les services WMTS
2. afficher les résultats
3. une erreur python survient (voir la copie d'écran et le fichier de log ci-joint)
4. le plugin se fige, obligé de redemarrer Qgis

![recherche_wmts](https://cloud.githubusercontent.com/assets/14051239/23653572/5a55ad70-032d-11e7-8e1b-6f56ce28df00.PNG)

[log_isogeo_plugin.zip](https://github.com/isogeo/isogeo-plugin-qgis/files/824156/log_isogeo_plugin.zip)

**Comment by vblanlot** [comment]
Quand je recherche les services WMTS disponibles, une erreur python survient.
Test effectué sur la version en développement avec l'application Plugin QGIS - Dév

Pour reproduire :

1. rechercher les services WMTS
2. afficher les résultats
3. une erreur python survient (voir la copie d'écran et le fichier de log ci-joint)
4. le plugin se fige, obligé de redemarrer Qgis

![recherche_wmts](https://cloud.githubusercontent.com/assets/14051239/23653572/5a55ad70-032d-11e7-8e1b-6f56ce28df00.PNG)

[log_isogeo_plugin.zip](https://github.com/isogeo/isogeo-plugin-qgis/files/824156/log_isogeo_plugin.zip)

**Comment by Guts** [comment]
Il s'agit d'un souci d'encodage au moment de la création de l'étiquette du bouton d'ajout. Ce n'est pas lié spécifiquement à l'ajout de WMTS.

Je crée une autre issue dédiée.

**Comment by Guts** [comment]
Un problème présent dans la version d'OWSLib intégrée à QGIS (2.14.x) empêchait la lecture de certains WMTS.

Il a été signalé puis résolu: https://hub.qgis.org/issues/16333#change-75188 (dérivé vers https://github.com/geopython/OWSLib/issues/361).

Le correctif devrait être présent dans les versions de QGIS compilées début avril.
