### ISSUE TITLE
Gérer l'ajout des services web Esri à la carte

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#84]
### Idée

Depuis QGIS 2.16 (aujourd'hui dépréciée au profit de la 2.18), il est possible d'ajouter les couches des services géographiques web Esri. Compte-tenu qu'Isogeo est également capable de les référencer, il s'agit de permettre à l'utilisateur d'ajouter ces couches via le plugin.

Il est également envisageable de l'implémenter pour les versions précédentes de QGIS, en s'appuyant sur le plugin [ArcGIS REST API Connector](http://plugins.qgis.org/plugins/connector/). Il faut évaluer le retour sur investissement de ce développement supplémentaire.

### Fonctionnement attendu

Le comportement doit être similaire à celui de l'ajout de couches via les services OGC.

**Comment by vblanlot** [comment]
Après plusieurs tests réalisé à partir de la fiche de métadonnées TEST-Services automatiques du groupe de travail Isogeo Tests, je constate que :

- aucune couche EMS ne s'affiche (cf.capture d'écran)
- seul la couche EFS "PYLONE" s'affiche
- la couche EPCI en EFS et EMS génère un avertissement

Pour reproduire :

1. Ouvrir le plugin isogeo pour QGIS
2. Rechercher la fiche "TEST - Services automatiques"
3. Ajouter les EMS et les EFS à la carte
4. Les couches sont ajoutées à la table des matiéres
5. Les couches EMS ne s'affichent pas sur la carte (cf.capture)
6. la couche EFS "Décehterrie" ne s'affiche pas
7. La couche EFS "Pylone" s'affiche :)
8. La couche EFS et EMS "EPCI" génère un avertissement lié à l'impossibilité de QGIS à lire la référence spatiale (cf.capture)
9. La couche EMS "Communes" génère un avertissement lié à l'impossibilité de QGIS à lire la référence spatiale (cf.capture)
10. en passant par les fonctionnalités standards de QGIS pour ajouter des cartes et des couches d'entité ArcGis sa fonctionne sauf pour le service Isogeo : http://noisy.hq.isogeo.fr:6080/arcgis/rest/services/DEV_tests/TEST_ADMIN_EXPRESS/MapServer

![ems_efs_qgis](https://user-images.githubusercontent.com/14051239/36855231-34a20c84-1d73-11e8-8809-7b2fd678c094.PNG)

**Comment by vblanlot** [comment]
Fichier de log 👍 
[log_isogeo_plugin.log](https://github.com/isogeo/isogeo-plugin-qgis/files/1771865/log_isogeo_plugin.log)

**Comment by Guts** [comment]
Certains services Esri ne sont pas ajoutables dans QGIS à cause de leur référence spatiale :
![image](https://user-images.githubusercontent.com/1596222/38568585-4ca93a38-3ce9-11e8-901f-56a24e244344.png)

Une erreur qu'il est difficile pour le plugin de traiter. Je continue d'investiguer...
