### ISSUE TITLE
Impossible to change authentification parameters

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#91]
When i want to change the authentification parameters, Qgis crash.

![scrennshot](https://cloud.githubusercontent.com/assets/14051239/22030342/9d58281c-dcdd-11e6-9d18-e4eb0660ff86.png)

[log_isogeo_plugin.zip](https://github.com/isogeo/isogeo-plugin-qgis/files/711734/log_isogeo_plugin.zip)

**Comment by Guts** [comment]
Already fixed but not packaged: #89 (see the dedicated comment to you ;) )
