### ISSUE TITLE
Ajouter une couche WMS

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#93]
Le problème : lors de l'ajout d'un couche WMS disponibles dans plusieurs systèmes de coordonnées mais sans projection associée, l'utilisateur doit systématiquement spécifier le SCR de la couche à afficher.

Le besoin : lors de l'ajout d'un couche WMS disponibles dans plusieurs systèmes de coordonnées mais sans projection associée, afficher la couche dans le même système de coordonnées que le projet

Solution possible : reprendre le comportement de la fonctionnalité QGIS "Ajouter des couches d'un serveur WM(T)S) 

Cette insuffisance provient du fait que le(s) SRS de la couche indiqué(s) dans le GetCapabilities du service n'est pas consigné dans la fiche de métadonnées de service fournie par Isogeo et donc non servies par l'API

**Comment by vblanlot** [comment]
Cette insuffisance provient du fait que le(s) SRS de la couche indiqué(s) dans le GetCapabilities du service n'est pas consigné dans la fiche de métadonnées de service fournie par Isogeo et donc non servies par l'API

**Comment by Guts** [comment]
Sera probablement résolu avec #90.
Plus de précisions serait souhaitable => à enrichir.

**Comment by vblanlot** [comment]
Tests réalisés :

- dans le groupe de travail "CD Calvados"
- sur ce service WMS http://geocalvados.calvados.fr/arcgis/services/Flux_WMS/WMS_ReseauRoutier/MapServer/WMSServer?qui dispose de 4 SRS possibles (EPSG: 4326, 2154 et 102110)

Test 1 :

1. Ouvrir un nouveau projet Qgis
2. Dans les Propriétés du projet > SCR, activer la projection à la volée et sélectionner le SCR RGF93/Lambert93 EPSG:2154
3. Ouvrir le plug-in Isogeo
4. Dans l'onglet Recherche filtrer les résultat sur le format = WMS
5. Afficher les résultats
6. Ajouter la couche 0 du Flux WMS du réseau routier départemental du calvados
7. Une pop-up s'ouvre, spécifier le SCR de la couche en recherchant et en sélectionnant le SCR WGS84 EPSG:4326
8. La couche est ajoutée dans votre projet, elle est correctement re-projetée en RGF93/Lambert 93

Test 2 : 

1. Ouvrir un nouveau projet Qgis
2. Dans les Propriétés du projet > SCR, activer la projection à la volée et sélectionner le SCR RGF93/Lambert93 EPSG:2154
3. Ouvrir le plug-in Isogeo
4. Dans l'onglet Recherche filtrer les résultat sur le format = WMS
5. Afficher les résultats
6. Ajouter la couche 0 du Flux WMS du réseau routier départemental du calvados
7. Une pop-up s'ouvre, spécifier le SCR de la couche en recherchant et en sélectionnant le SCR RGF93/Lambert93 EPSG:2154
8. La couche est ajoutée dans votre projet, elle n'est pas re-projetée en RGF93/Lambert 93
