### ISSUE TITLE
Reduce results list to 10 items

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#94]
Performance enhancement and linked to #90

**Comment by vblanlot** [comment]
10 résultats s'affichent bien par page. En revanche tous les résultats ne sont pas affichés et il y a plus de pages que nécessaires pour afficher tous les résultats

Pour reproduire :

1. Afficher entre 50 et 59 résultats
2. 6 page sont proposées, or il n'y a par exemple que 57 résultats
3. Afficher la page 5/6 aucun résultats n'est proposés or il devrait y en avoir 7
4. Afficher la page 6/6 il y a aucun résultats ce qui est normal. Dans ce cas la page ne devrait pas être proposée

![pagination](https://cloud.githubusercontent.com/assets/14051239/23655783/da3805b6-0336-11e7-84ec-88ab326cdff0.PNG)
