### ISSUE TITLE
Revoir la fenêtre d'authentification de l'application à l'API Isogeo

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-plugin-qgis#99]
Dans la fenêtre "paramètres d'authentification à Isogeo" 

- [x] afficher l'ID et le secret si déjà renseigné
- [x] proposer à l'utilisateur de valider l'id et le secret de l'application avant d'enregistrer

![authentification_api](https://cloud.githubusercontent.com/assets/14051239/23661354/cac2c52e-034c-11e7-861f-9a2481b18b1d.PNG)

**Comment by Guts** [comment]
Au-delà de l'aspect fonctionnel (bouton de check), quitte à retravailler sur cette fenêtre, autant la repenser de manière globale :

* besoin de réflexion / décision sur la formulation du bouton de demande d'accès. Pour info :
  - en français : "Pas encore de compte Isogeo ?" / "Demander des identifiants"
  - en anglais : "Don't have an account yet ?" / "Request plugin access"

* indiquer des informations pour donner envie de faire la demande ou du moins la documenter : lien fonctionnalités ? gratuit ou pas ? etc.

**Comment by Guts** [comment]
Voici une proposition (texte à traduire évidemment).

![qgis_isogeo_auth_proposal](https://cloud.githubusercontent.com/assets/1596222/24244675/30cbcbf2-0fc0-11e7-9684-fda32631169a.png)

**Comment by vblanlot** [comment]
Fenêtre dispo est fonctionnelle.

Remarque : après modification des paramètres d'authentification, les informations relatives au partage ne semble pas être rafraîchie. Il faut nécessairement ré-ouvrir le plugin pour voir les infos à jour. C'est un détail qui ne concerne qu'une minorité d'utilisateurs.

**Comment by Guts** [comment]
En effet. On tentera d'améliorer le rafraîchissement à l'occasion.
